### ISSUE TITLE
Papa John's

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#10]
https://www.papajohns.com/order/stores-near-me

**Comment by aleherrera** [comment]
on it https://www.papajohns.com/locations/

**Comment by iandees** [comment]
Removing the assignee on this because there's been no update for 6 days.

**Comment by kristinepetrosyan** [comment]
@iandees how do you want the hours? https://www.papajohns.com/locations/usa/ar/benton/72019/1000-hwy-35-north-%2314/3683

There are delivery hours and also carryout hours. Which one should we take?

**Comment by iandees** [comment]
Let's do carryout.

**Comment by kristinepetrosyan** [comment]
@iandees ok will make the changes.
