### ISSUE TITLE
Amai Promap store locator

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#10032]
Marketing info here https://amai.com/apps/promap-store-locator/

_Originally posted by @arrival-spring in https://github.com/alltheplaces/alltheplaces/issues/10026#issuecomment-2323147454_

https://github.com/search?q=repo%3Aalltheplaces%2Falltheplaces%20amaicdn.com&type=code

Indicator:
Request to https://amaicdn.com/storelocator-prod/wtb/*.js

### Others

- [x] https://github.com/alltheplaces/alltheplaces/pull/10913
- [x] https://github.com/alltheplaces/alltheplaces/pull/10912
- [x] https://sl.amaicdn.com/

Via publicwww

### Manufacturers listing resellers

- [x] gestalten.com
- [x] https://beabongiasca.com/pages/boutique ?
- [x] http://discountair1.com/
- [x] http://warmiesshop.com/
- [x] https://ajstuarts.com/
- [x] https://americanmetabolix.com/
- [x] https://biorb.com/
- [x] https://bolfoods.com/
- [x] https://bonanzasatrangi.com/
- [x] https://bootjack.com/
- [x] https://codina.fr/
- [x] https://cult-crew.myshopify.com/
- [x] https://evolutionoutdoor.com/
- [x] https://fila.com.ph/
- [x] https://floafers.com/
- [x] https://granitegold.com/
- [x] https://havit.com.au/
- [x] https://imageskincare.co.uk/
- [x] https://iroirocolors.com/
- [x] https://janeiredale.co.uk/
- [x] https://lxmi.com/
- [x] https://maternatura.it/
- [x] https://mjarsenal.com/
- [x] https://myspringenergy.com/
- [x] https://pinktartan.ca/
- [x] https://proraso-usa.com/
- [x] https://redmond.life/
- [x] https://rieker.ca/
- [x] https://shopbioseaweedgel.com/
- [x] https://shoppeninsulas.com/
- [x] https://sippify.com.au/
- [x] https://smashtess.com/en-gb
- [x] https://solarismexico.com/
- [x] https://sottotono.it/
- [x] https://store.vermontsmokeandcure.com/
- [x] https://suterproducts.com/
- [x] https://thenormalbrand.com/
- [x] https://vegepod.com/
- [x] https://waxrx.com/
- [x] https://www.diffeyewear.com/
- [x] https://www.gigi-fratelli.com/en-gb
- [x] https://www.leminimacaron.com/
- [x] https://www.mdnaskin.us/
- [x] https://www.mg-atelier.com/
- [x] https://www.mirrormate.com/
- [x] https://www.proeagle.com/
- [x] https://www.startmycar.co.za/
- [x] https://www.strikeforceenergy.com/
- [x] https://www.sunstonewelders.com/
- [x] https://www.terrenetires.com/
- [x] https://xnihilo.com.au/
- [x] https://yougonatural.com/

**Comment by arrival-spring** [comment]
A number of these I've checked have maps of stockists, so not suitable to spider

**Comment by arrival-spring** [comment]
Store finder added, now I think just check through those to see if any can be added

**Comment by CloCkWeRX** [comment]
Just adding autodetection, do you see any problems if the start_url was swapped to `https://amaicdn.com/storelocator-prod/wtb/dunnssa-1726566545.js?shop=dunnssa.myshopify.com` for the other spiders, or do you feel like it will change frequently

**Comment by CloCkWeRX** [comment]
TODO: Need to tweak the js_urls vs start_urls autodetection
