### ISSUE TITLE
Scrubs & Beyond

### ISSUE THREAD

**Issue by wessport** [alltheplaces/alltheplaces#1005]
https://locations.scrubsandbeyond.com/#/map

**Comment by davidhicks** [comment]
Single API request to `https://maps.scrubsandbeyond.com/api/getAsyncLocations?template=search&level=search&radius=100000&limit=100000&search=Seattle%2C%20WA%2C%20USA` returns all location data in JSON format.

**Comment by CloCkWeRX** [comment]
Scrubs and Beyond exists, is this closable? It does not use the Rio SEO storefinder.

**Comment by davidhicks** [comment]
122 locations returned consistently over last few runs per https://alltheplaces-data.openaddresses.io/runs/2024-04-06-13-31-42/stats/scrubs_and_beyond.json

Can close per @CloCkWeRX suggestion that the spider already exists and is working.
