### ISSUE TITLE
Versace

### ISSUE THREAD

**Issue by wessport** [alltheplaces/alltheplaces#1017]
https://www.versace.com/us/en-us/find-a-store/#country=US&address=United+States&format=ajax

**Comment by davidhicks** [comment]
Probably better crawled through https://www.versace.com/sitemap-pages-international-en-1.xml with a URL filter of `https://www.versace.com/international/en/store/?StoreID=[A-Z]{2}\d{10}`

This returns a single page per store but XPath/CSS selectors would seemingly be needed (no structured data from what I can see).
