### ISSUE TITLE
office=business?

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#10229]
https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/sos_br.py

why not `office=company` ? Is `office=business`  intentional?

**Comment by matkoniecz** [comment]
maybe I should try making CI tool to detect unusual shop/office values...

Or at least automate listing of suspicious ones so I do not need to make reports manually as at this point I find more problems in ATP than own code...

**Comment by CloCkWeRX** [comment]
Translated blurb of the site:
> More than 42 professional course options in the areas of Administration, IT, Design and English. Be prepared for the future, come to SOS!

So, a company that sells professional courses but doesn't rise to the level of an education institution.

**Comment by matkoniecz** [comment]
The question is what is at given POI?

Internal company office? 

Sale point? 

Classroom?
