### ISSUE TITLE
amenity=bakery?

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#10228]
https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/masoutis_gr.py assigns `amenity=bakery` in some cases.

What it is supposed to mean? Maybe it was supposed to be `shop=bakery` ? Or is it production facility with no shop?

**Comment by matkoniecz** [comment]
I see also `            apply_yes_no("amentity=butcher", item, location["IFbutchershop"])`

**Comment by davidhicks** [comment]
I think it's trying to find OSM tags to be able to tag a `shop=supermarket` as having a number of "departments" within such as an in-house bakery or butcher. I don't think the current form of tagging is correct but am unaware of any other suitable OSM tagging convention for "departments" within something like a supermarket.

**Comment by matkoniecz** [comment]
For supermarkets I would assume that it sells bread, meat etc and treat it is covered by `shop=supermarket`

**Comment by davidhicks** [comment]
> For supermarkets I would assume that it sells bread, meat etc and treat it is covered by `shop=supermarket`

I can only speak to Australia where in-store butchers are long gone in supermarkets. In-store bakeries are harder to find and there could be some minimal and declining value in denoting which stores finish the baking process in-store (from refrigerated/frozen dough) versus the stores which only bring in pre-baked bread. Generally I just ignore the specifics of what goods are made/sold in each location of a chain as I'm not aware of anyone using such data with OSM.

In other countries I think it's more common for some stores to sell liquor and some to have a pharmacy, but this isn't consistent across all stores of a chain. If these are separately branded stores-within-stores, spiders are generally extracting multiple features and using the `located_in` key to denote the store-within-store relationship. If there is no separate branding, I think spiders generally just don't denote the optional pharmacies, liquor sales, etc.
