### ISSUE TITLE
office = mortgage ?

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#10230]
undocumented and rarely used, see https://wiki.openstreetmap.org/wiki/Tag:office%3Dmortgage

added by https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/guild_mortgage_us.py

do we have no existing tagging for that?

**Comment by impiaaa** [comment]
In this case the tag [comes from NSI](https://nsi.guide/index.html?t=brands&k=office&v=mortgage#guildmortgagecompany-f8ef9d), perhaps the bug should be filed there
