### ISSUE TITLE
remove call center phones - list of affected spiders

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#10233]
in following cases PR like #9242 may be applied, as I understand those are call center phones

or some pipeline to mass remove them may be helpful

I can regenerate list in better format if it would be useful

* [ ] maserati has call center phone in phone = +44 333 240 7869
* [ ] trussell_trust_gb has call center phone in phone = +44 330 400 4116
* [ ] lloyds_bank_gb has call center phone in phone = +44 345 602 1997
* [ ] apcoa has call center phone in phone = +44 345 301 1151
* [ ] hm has call center phone in phone = +44 344 736 9000
* [ ] argos has call center phone in phone = +44 345 013 0292
* [ ] premier_gb has call center phone in phone = +44 345 722 3344
* [ ] jack_wills_gb has call center phone in phone = +44 343 909 2230
* [ ] nationwide_gb has call center phone in phone = +44 345 266 0732
* [ ] activ_fitness_ch has call center phone in phone = +44 33 553 21 01
* [ ] vets4pets_gb has call center phone in phone = +44 345 266 8522
* [ ] seat has call center phone in phone = +44 330 017 0210
* [ ] ncp_gb has call center phone in phone = +44 345 050 7080
* [ ] holland_and_barrett has call center phone in phone = +44 330 058 2640
* [ ] bensons_for_beds_gb has call center phone in phone = +44 333 222 6800
* [ ] toolstation has call center phone in phone = +44 330 333 3303
* [ ] b_and_m has call center phone in phone = +44 333 034 6851
* [ ] next has call center phone in phone = +44 333 005 5320
* [ ] bella_italia_gb has call center phone in phone = +44 345 646 1048
* [ ] citroen has call center phone in phone = +44 330 096 0478
* [ ] whsmith has call center phone in phone = +44 333 600 5000
* [ ] card_factory_gb has call center phone in phone = +44 330 016 2197
* [ ] my_dentist_gb has call center phone in phone = +44 344 225 2000
* [ ] renault has call center phone in phone = +44 330 017 6673
* [ ] indigo has call center phone in phone = +44 330 123 5247
* [ ] bmw_group has call center phone in phone = +44 330 108 1276
* [ ] space_nk_gb has call center phone in phone = +44 300 124 6029
* [ ] ihg_hotels has call center phone in phone = +44 371 942 9014
* [ ] shoe_zone_gb has call center phone in phone = +44 330 016 0702
* [ ] halifax_gb has call center phone in phone = +44 345 720 3040
* [ ] best_western has call center phone in phone = +44 371 942 9040
* [ ] mamas_and_papas_gb has call center phone in phone = +44 330 094 7552
* [ ] river_island_ie_gb has call center phone in phone = +44 344 334 0531
* [ ] bank_of_scotland_gb has call center phone in phone = +44 345 721 3141
* [ ] puregym_gb has call center phone in phone = +44 344 477 0005
* [ ] shell has call center phone in phone = +44 330 355 9233
* [ ] kia_gb has call center phone in phone = +44 344 659 0628
* [ ] away_resorts has call center phone in phone = +44 330 053 7000
* [ ] sofology_gb has call center phone in phone = +44 330 190 0223
* [ ] rexel_gb has call center phone in phone = +44 330 045 0800
* [ ] ford has call center phone in phone = +44 343 308 3954
* [ ] pets_at_home_gb has call center phone in phone = +44 345 266 0589
* [ ] church_of_england_gb has call center phone in phone = +44 333 050 4891
* [ ] easy_bathrooms_gb has call center phone in phone = +44 330 660 1120
* [ ] homebase_gb_ie has call center phone in phone = +44 345 640 7675
* [ ] exxon_mobil has call center phone in phone = +44 345 268 0856
* [ ] sainsburys has call center phone in phone = +44 330 013 8113
* [ ] trade_point_gb has call center phone in phone = +44 330 123 9243
* [ ] bq has call center phone in phone = +44 330 123 9243
* [ ] boots has call center phone in phone = +44 345 125 3776
* [ ] starbucks_eu has call center phone in phone = +44 330 016 4042
* [ ] avis has call center phone in phone = +44 344 544 6002
* [ ] french_connection has call center phone in phone = +44 344 800 3708
* [ ] poundbakery_gb has call center phone in phone = +44 300 373 0158
* [ ] volvo has call center phone in phone = +44 333 455 9519
* [ ] travelodge_gb has call center phone in phone = +44 371 984 6554
* [ ] better_gb has call center phone in phone = +44 300 003 0616
* [ ] baskin_robbins_gb_ie_je has call center phone in phone = +44 333 003 3444
* [ ] halfords_gb has call center phone in phone = +44 333 016 6550
* [ ] subway has call center phone in phone = +44 333 009 5141
* [ ] costcutter_gb has call center phone in phone = +44 303 030 1010
* [ ] screwfix_gb has call center phone in phone = +44 333 011 2112
* [ ] tesco_gb has call center phone in phone = +44 333 345 0914
* [ ] wyndham has call center phone in phone = +44 330 440 7800
* [ ] tsb_gb has call center phone in phone = +44 345 975 8758

**Comment by AbhiKamp** [comment]
Sir can you explain the issue more briefly,what changes do you want?

**Comment by matkoniecz** [comment]
I think that these should be skipped as these are https://en.wikipedia.org/wiki/Non-geographic_telephone_numbers_in_the_United_Kingdom (confusingly, described there as being 03 prefixed but 0 is trunk code that can be omitted...)

but highly repeated one phone numbers are more problematic, so I will close this issue
