### ISSUE TITLE
kfc_hk has apparently not valid geojson

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#10231]
it is not a valid geojson geometry, right?

`"geometry": [114.029062, 22.44215]}`

`{"type": "Feature", "id": "hs3bXuMMqLbaupOfe3OxKqEcj78=", "properties": {"ref": "253", "@source_uri": "https://ordering.kfchk.com/Action", "@spider": "kfc_hk", "amenity": "fast_food", "brand:en": "KFC", "brand:zh": "\u80af\u5fb7\u57fa", "brand:zh-Hans": "\u80af\u5fb7\u57fa", "brand:zh-Hant": "\u80af\u5fb7\u57fa", "cuisine": "chicken", "name:en": "KFC", "name:zh": "\u80af\u5fb7\u57fa", "name:zh-Hans": "\u80af\u5fb7\u57fa", "name:zh-Hant": "\u80af\u5fb7\u57fa", "takeaway": "yes", "addr:full": "Shop G06-070, G/F, Yuen Long Plaza, 249-251 Castle Peak Road, Yuen Long", "addr:country": "HK", "name": "\u80af\u5fb7\u57fa KFC", "branch": "\u5143\u6717\u5ee3\u5834", "phone": "+852 2719 6178", "website": "https://www.kfchk.com/", "brand": "KFC", "brand:wikidata": "Q524757", "nsi_id": "kfc-17dd9a"}, "geometry": [114.029062, 22.44215]},`

I expected something like `"geometry": {"type": "Point", "coordinates": [115.7817664, -31.9814376]}`

**Comment by arrival-spring** [comment]
Added in #9953

I think this shows an issue with the checking, as the logs on that build show an error but it still says that it was a success.
