### ISSUE TITLE
HSBC UK Spider broken

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#10258]
### Spider name

hsbc_uk_gb

### Log output

https://alltheplaces-data.openaddresses.io/runs/2024-09-07-13-32-11/logs/hsbc_uk_gb.txt

### Example bad data or results

No branches are returned by the spider.

### Expected behaviour or results

Somewhere between 300 and 400 branches are returned.

### Possible causes?

I'm unsure what the problem is here. The sitemap start-point https://www.hsbc.co.uk/sitemaps-pages.xml lists plenty of branch pages matching the regex, and the spider stats show https://alltheplaces-data.openaddresses.io/runs/2024-09-07-13-32-11/stats/hsbc_uk_gb.json 400+ successful page requests. Yet the error log at https://alltheplaces-data.openaddresses.io/runs/2024-09-07-13-32-11/logs/hsbc_uk_gb.txt is blank, and no branches are returned.

Is something in the post_process_item code breaking and not writing to the error log? Does anyone have any ideas?

**Comment by Cj-Malone** [comment]
The website now has malformed linked data (missing `@type`).
