### ISSUE TITLE
Fotoprix (shop/photo) (ES) (215 stores)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#10278]
### Brand name

Fotoprix

### Wikidata ID

Q99196842
https://www.wikidata.org/wiki/Q99196842
https://www.wikidata.org/wiki/Special:EntityData/Q99196842.json

### Store finder url(s)
https://www.fotoprix.com/tiendas
https://www.fotoprix.com/tiendas/a-coruna/boiro
Official Url(s): https://www.fotoprix.com/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q99196842 https://www.fotoprix.com/`
```
```

**Comment by davidhicks** [comment]
Sitemap: https://www.fotoprix.com/sitemaps/pages-1.xml

Example store page: https://www.fotoprix.com/tiendas/tarragona/reus
