### ISSUE TITLE
Ron Jon Surf Shop

### ISSUE THREAD

**Issue by wessport** [alltheplaces/alltheplaces#1040]
https://www.ronjonsurfshop.com/location/default.aspx

**Comment by davidhicks** [comment]
Paginated custom JSON API that returns all 13 locations in a single query per `https://www.ronjonsurfshop.com/ajax/store-locator?searchText=&pagesize=15&pageNumber=1`

**Comment by Exterminator11** [comment]
Hey @davidhicks, I would like to work on this!!
