### ISSUE TITLE
Inquiry About Stability Metric Calculation

### ISSUE THREAD

**Issue by Ebadm** [alltheplaces/alltheplaces#10523]
Hello,

I am currently exploring the [All the Places](https://www.alltheplaces.xyz/spiders) project and came across the stability metric displayed on the spiders page. I would love to understand how this stability metric is calculated.

Additionally, is there a way to access this metric programmatically or through any API? Also, for accessing the [wikidata table](https://www.alltheplaces.xyz/wikidata) ?

Thank you for your time, and I appreciate any insights you can provide!

**Comment by davidhicks** [comment]
It's the `getColorGradient` function at https://github.com/alltheplaces/alltheplaces.xyz/blob/master/spiders.html

**Comment by iandees** [comment]
The stability score is calculated in your browser and isn't available via the API at this point.

The wikidata table is generated using the "insights" JSON. The latest of which is here: https://alltheplaces-data.openaddresses.io/runs/2024-09-21-13-32-12/stats/_insights.json
