### ISSUE TITLE
Williams-Sonoma

### ISSUE THREAD

**Issue by hereticaneue** [alltheplaces/alltheplaces#1053]
https://www.williams-sonoma.com/customer-service/store-locator.html?cm_type=fnav

Has a list of Williams Sonoma stores and another list of Williams Sonoma Home stores.

**Comment by davidhicks** [comment]
Single API call returning location JSON data for USA/Canada: `https://www.williams-sonoma.com/api/phygital/v1/storesbylocation.json?brands=WS&lat=40.71304703&lng=-74.00723267&radius=100000&includeOutlets=true`

The handful of international stores in Kuwait, Korea, Australia and Mexico (if anyone can be bothered collecting) need a CrawlSpider approach for the store locator page per search error message:
>  We're sorry, our 'Enter Location' is only available for U.S. & Canadian stores at this time. Please visit our 'Filter a Store' module for our international store locations.
