### ISSUE TITLE
FitActive

### ISSUE THREAD

**Issue by ivanbranco** [alltheplaces/alltheplaces#10574]
### Brand name

FitActive

### Wikidata ID

Q123807531

### Store finder url(s)

https://www.fitactive.it/Club/Club

### Sample store page url

https://www.fitactive.it/i-club/Vercelli.php

### Countries?

IT,BR,RO,ES,CH

### Difficulty?

None

### Number of POI?

100+

### Behaviours

- [X] Has coordinates?
- [X] Has opening hours?
- [ ] JSON API?
- [ ] Embedded JSON?
- [ ] HTML markup?
- [ ] Structured Data? (`pipenv run scrapy sd (specific page url)`) or [validator](https://validator.schema.org/) has content
- [ ] Open Graph Data?
- [ ] Sitemap? (`pipenv run scrapy sitemap (url)`)
- [ ] Requires proxy?
- [ ] Has 'bot protection' (Cloudflare, etc)?

**Comment by ivanbranco** [comment]
Sorry, I don't really know what to flag in Behaviours and what difficult to set.

**Comment by CloCkWeRX** [comment]
All good @ivanbranco you've added a lot of good detail to get folks started :)

**Comment by CloCkWeRX** [comment]
https://validator.schema.org/#url=https%3A%2F%2Fwww.fitactive.it%2Fi-club%2FFitActiveAprilia.phpb limited structured data (postal address only)
