### ISSUE TITLE
Foot Locker

### ISSUE THREAD

**Issue by hereticaneue** [alltheplaces/alltheplaces#1058]
https://stores.footlocker.com/index.html

**Comment by rkpatel7** [comment]
I've started work on this one!

**Comment by rkpatel7** [comment]
@iandees I am thinking of using [extruct](https://github.com/scrapinghub/extruct) to help with the extraction since Foot Locker neatly identifies their elements using schema.org schemes. Do you have any opposition to adding a new dependency to extruct?

**Comment by iandees** [comment]
I'd be interested in seeing a PR if it would make it easier to extract the microdata, but there are several other spiders that use regular `xpath()` calls to extract microdata without further dependencies, so it would have to be significantly easier 😄

**Comment by rkpatel7** [comment]
@iandees, before I make a PR with it, here's what it looks like:

```
from extruct.w3cmicrodata import MicrodataExtractor

mde = MicrodataExtractor()
mde.extract(response.body_as_unicode(), response.url)
```

This will output [this data structure](https://pastebin.com/Hs1fe1Y6), at least for footlocker. So I guess you still have to then traverse that appropriate dict in the list of dicts checking to see if the key exists in the dict. It may not be significantly easier.

I've found another library called [microdata](https://github.com/edsu/microdata/blob/master/microdata.py) that actually makes `Item` objects that can then be used like this:
```
>>> import microdata
>>> items = microdata.get_items(response.body_as_unicode())
>>> items
[<microdata.Item object at 0x7f940d16f750>, <microdata.Item object at 0x7f940d160ed0>]
>>> items[1].name
'House of Hoops by Foot Locker Dededo'
>>> pprint(items[1].geo)
<microdata.Item object at 0x7f940d16fd90>
>>> items[1].geo.latitude
'13.520249529593947'
```

Given that this is my first contribution, I think I'll just go with how other spiders are doing regular xpath in this issue and then open a separate one to see if there's a way to effectively use one of these libraries.
