### ISSUE TITLE
Sample of cases where image or phone is the same in over 1000 POI, indicating that it is likely not POI-specific

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#10621]
* [ ] image = https://dynl.mktgcdn.com/p/SwUIly_6zpFTSdZxbmDDWpdbvAwmIZ-1covWYzFlk4Q/150x150.jpg repeated 1101 times in quiktrip_us
* [ ] phone = +1 844-401-8500 repeated 2130 times in bank_of_america
* [ ] image = https://dynl.mktgcdn.com/p/irgrRvtNhff6VLubiBfb0wXj66qCmjjWiKJVpjROaBo/150x150.jpg repeated 1242 times in dominos_pizza_gb
* [ ] image = https://locations.where2getit.com/burlington/images/new/burlington-details.png repeated 1051 times in burlington_us
* [ ] phone = +27 860 999 119 repeated 1032 times in tymebank_za
* [ ] phone = 20000000 repeated 1019 times in seven_eleven_ph
* [ ] phone = +44 800 440011 repeated 1112 times in coral_gb
* [ ] image = https://locations.baskinrobbins.com/assets/static/capuccino-734598ab.png repeated 2254 times in baskin_robbins_us
* [ ] image = https://dynl.mktgcdn.com/p/vVQvY4pkSyF7r1hz-Md07mKAaUyXFlbiOSBA3l1GXzg/150x150.png repeated 7825 times in taco_bell
* [ ] phone = +49 800 7234870 repeated 2142 times in aldi_nord_de
* [ ] image = https://stores.foodlion.com/permanent-b0b701/assets/images/hero-fallback.3d0b8665.png repeated 1174 times in food_lion_us
* [ ] image = https://assets.rbl.ms/25637742/origin.jpg repeated 2500 times in penske
* [ ] image = https://www.ameriprise.com/binaries/content/gallery/ampcom/ameriprise-social-image.png repeated 1175 times in ameriprise_us
* [ ] phone = +44 800 731 6191 repeated 1442 times in ladbrokes_gb
* [ ] image = https://dynl.mktgcdn.com/p/x09r9louvg69_KeYHPnS2M0C8liZgK2TVvn8GDn7uR8/196x196.jpg repeated 1321 times in big_lots
* [ ] phone = +52 55 4510 9999 repeated 2239 times in tiendas_3b_mx
* [ ] image = https://locations.papajohns.com/assets/static/ogImage-PQRQWxIY.webp repeated 3345 times in papa_johns
* [ ] phone = 0528001103990 repeated 1626 times in citi
* [ ] phone = +44 800 042 0800 repeated 1031 times in aldi_sud_gb
* [ ] image = https://dynl.mktgcdn.com/p/Ex6BZ7PegozPldmWvTAsXiuX4zM9mzD8jjVUgMdAYxI/150x150.png repeated 1365 times in petco
* [ ] image = https://cdn.thumbor.leadformance.com/media/clients/5c360bbd772d089b709a3baa/c7a985ef-321a-455c-959e-43f9f6f6f5d9-picard-2.jpeg repeated 1175 times in picard_fr
* [ ] image = https://locations.theupsstore.com/assets/static/storefront_fallback-Bc2t9pGt.svg repeated 3231 times in ups_store
* [ ] phone = +1 855-704-2669 repeated 1549 times in spirit_halloween
* [ ] image = https://dynl.mktgcdn.com/p/0kiNDvmfMqhh1or-XCUjkCfJEVmp3I5y94NWjBaZNZc/1.0000/150x150.png repeated 1010 times in massage_envy
* [ ] image = https://dynl.mktgcdn.com/p/VNkahEa7sRSHyLyMlAx139ar5dy990ORB7RJjweKGQs/196x196.jpg repeated 1451 times in mt_bank_us
* [ ] image = https://dynl.mktgcdn.com/p/oOWgAcHIvnx6ijuwPmyZIkUVJoHIEvFyzbBmbAqdwYk/150x150.png repeated 4999 times in jackson_hewitt
* [ ] phone = +49 231 555770 repeated 1931 times in tedi
* [ ] image = https://dynl.mktgcdn.com/p/ugVeu_I7n9ph4B3cT6SZ6fyDoG9DxqRIS0jD53oN5w8/800x800.png repeated 5860 times in wendys
* [ ] image = https://dynl.mktgcdn.com/p/fKrePdCdx2ELmLmLAhZS4wmMUa0gBGvpkk-lqPcPASc/150x150.jpg repeated 1077 times in fifth_third_bank
* [ ] image = https://agences.sg.fr/banque-assurance/UI/20240628-105709/photos/agence/agence-sg.jpg repeated 1452 times in societe_generale
* [ ] phone = +1 888-365-4266 repeated 1081 times in dollarama
* [ ] image = https://dynl.mktgcdn.com/p/vfVdaxyP_jDZdsuJUp6zjXXz7jkJ87XeGPMuAnvDNYU/150x150.png repeated 1067 times in papa_murphys
* [ ] image = https://dynl.mktgcdn.com/p/aT0JcVtNProJLhR2fnA6l9nUx_qyHFJzDBo90WITFZk/1440x360.jpg repeated 1315 times in auntie_annes
* [ ] phone = +44 870 518 1715 repeated 1318 times in william_hill_gb
* [ ] phone = +1 800-869-3557 repeated 2346 times in wells_fargo
* [ ] image = https://dynl.mktgcdn.com/p/nTcyfpfO8CZssVSdufETsSE5_Entw6NuYztIPH7kwl8/150x150.jpg repeated 2160 times in gnc
* [ ] phone = +1 877-768-2265 repeated 1442 times in santander_us
* [ ] phone = +81 50-3821-8282 repeated 9122 times in gbfs
* [ ] phone = +61 131318 repeated 1574 times in australia_post_au

Once this list is processed I plan to post a new issue, maybe with a lower threshold if full scan will not find enough candidates. Let me know if you prefer this to not happen, skip some keys or check more.

**Comment by matkoniecz** [comment]
Maybe `image` or `phone` that is repeated over 10 times should be thrown out automatically? Without throwing it out manually by changing spider?

**Comment by matkoniecz** [comment]
Also, if that would be easier: feel free to close this issue after some cases were processed and ask for new one if that would be easier than ticking entries.

**Comment by CloCkWeRX** [comment]
What I found out is you can turn check boxes into issues or replace them with links... And when they close they tick themselves.
Rather handy.

**Comment by CloCkWeRX** [comment]
Could you sort the images into their own list? I feel like those it's definitely bad data.

I am less sure about a company wide contact point being "wrong" - I agree that it would be better to be individual; but would I still email or ring a central point for a company? Sometimes.

**Comment by matkoniecz** [comment]
> Could you sort the images into their own list? I feel like those it's definitely bad data.

maybe lets have two separate issues? one of images, one for phones

> I am less sure about a company wide contact point being "wrong" - I agree that it would be better to be individual; but would I still email or ring a central point for a company? Sometimes.

https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md suggests that these should be venue-specific

**Comment by matkoniecz** [comment]
I will close this one and open a new image-only issue. This should provide enough ideas for improvements.

**Comment by matkoniecz** [comment]
image-specific issue: #10630
