### ISSUE TITLE
Iren

### ISSUE THREAD

**Issue by ivanbranco** [alltheplaces/alltheplaces#10867]
### Brand name

Iren

### Wikidata ID

Q3801865

### Store finder url(s)

https://www.irenlucegas.it/assistenza/sportelli

### Countries?

IT

### Difficulty?

None

### Number of POI?

50-100

### Behaviours

- [X] Has coordinates?
- [X] Has opening hours?
- [ ] JSON API?
- [ ] Embedded JSON?
- [ ] HTML markup?
- [ ] Structured Data? (`pipenv run scrapy sd (specific page url)`) or [validator](https://validator.schema.org/) has content
- [ ] Open Graph Data?
- [ ] Sitemap? (`pipenv run scrapy sitemap (url)`)
- [ ] Requires proxy?
- [ ] Has 'bot protection' (Cloudflare, etc)?

**Comment by CloCkWeRX** [comment]
Embedded JSON blob:
```
<div class="d-none" id="store-pin" data-store='[{&#34;citta&#34;:&#34;Torino&#34;,&#34;regione&#34;:&#34;Piemonte&#34;,&#34;in
```
