### ISSUE TITLE
Grainger

### ISSUE THREAD

**Issue by thismakessand** [alltheplaces/alltheplaces#1088]
https://www.grainger.com/content/find-branch-location

**Comment by davidhicks** [comment]
SitemapSpider of `https://www.grainger.com/branch-location-sitemap.xml` + HTML parsing

**Comment by CloCkWeRX** [comment]
### Brand name

W. W. Grainger

American industrial supply company

### Wikidata ID

Q1627894
https://www.wikidata.org/wiki/Q1627894
https://www.wikidata.org/wiki/Special:EntityData/Q1627894.json

### Store finder url(s)

Official Url(s): https://www.grainger.com/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q1627894 https://www.grainger.com/`
```
```
Official Url(s): https://www.grainger.com/category
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q1627894 https://www.grainger.com/category`
```
```

**Comment by CloCkWeRX** [comment]
https://www.grainger.com/branch-location-sitemap.xml is 404 if visited directly
