### ISSUE TITLE
Matalan Spider Missing Stores and Including Closed Stores

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#10926]
### Spider name

matalan_gb.py

### Example bad data or results

There are two issues with the current spider, which lead to incorrect results:

1. Some of the stores returned by the spide appear to be closed closed, e.g. https://www.matalan.co.uk/store/leeds/leeds-city-centre . There seems to be about 8 of these with "CLOSED" in the store name.
2. Counting the numbers at https://www.matalan.co.uk/stores/uk you get 233 whereas the spider only returns 184. So around 50 stores are missing from the output, e.g. https://www.matalan.co.uk/store/rugby/rugby . 

### Expected behaviour or results

Closed stores should not be included in the output, but the missing ~50 should be.

### Possible causes?

1. The closed stores can be detected by filtering out those with "CLOSED" at the start of the name.
2. I think the missing stores are those where the store page is a direct redirect from a link on the region page. e.g. the link for "Rugby" at https://www.matalan.co.uk/stores/uk/west-midlands actually points to https://www.matalan.co.uk/stores/uk/west-midlands/rugby but this redirects to https://www.matalan.co.uk/store/rugby/rugby . Many single-store towns behave like this, but others have a page for the town, which then links to the single store page, e.g. https://www.matalan.co.uk/stores/uk/west-midlands/redditch . I assume the way CrawlSpider works, it doesn't see the final URL of the redirect-to store pages at the right point to know it should parse it. I don't know the intricacies of CrawlSpider, but one possible approach to fix this would be to add a call-back with some custom code to 'parse' the region pages, looking to see if the final URL matches a store page. If so, then if should be passed to parse_sd .

(Note that there's actually a second set of store pages for Matalan of the form https://store.matalan.co.uk/rugby and these contain some conflicting information at least on store opening times. I asked Matalan about this at https://twitter.com/rjw62/status/1842237370231349384 and they suggest that the https://www.matalan.co.uk/store/rugby/rugby versions (which are the ones you get to from their website's store-finder at https://www.matalan.co.uk/store-locator) are the correct ones.)

**Comment by rjw62** [comment]
@TheUKHighStreet - as you wrote the current code for this spider, you might like to take a look at this.

**Comment by Cj-Malone** [comment]
https://github.com/alltheplaces/alltheplaces/pull/10893
