### ISSUE TITLE
at least some vodacom_za miss any feature tag

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#10933]

**Comment by arrival-spring** [comment]
Something's gone wrong with your issue creation here, the feature here is not from vodacom_za The title is correct, and cadillac_us appears to have the same issue.

Vodacom (Q1856518) wasn't matching because of masts and towers in NSI.

**Comment by matkoniecz** [comment]
> feature here is not from vodacom_za

sorry! Apparently I did copy-paste the wrong way and I missed it :(

**Comment by matkoniecz** [comment]
other issues appear fine

I have also switched to more automation for this type of issues (can create more of them, but will do this after what I reported is mostly processed or if someone request N issues with plans to process them)

**Comment by arrival-spring** [comment]
Are there a lot of spiders with missing categories? Would an issue with a list (like you've done for emails and images) be too hard to deal with (for those processing)?

**Comment by matkoniecz** [comment]
oh, and while here example entry was bogus I think it would be useful to have it, especially where only part of features misses main tag

this seems argument for dedicated issues for me

**Comment by arrival-spring** [comment]
> oh, and while here example entry was bogus I think it would be useful to have it, especially where only part of features misses main tag
> 
> this seems argument for dedicated issues for me

That makes sense, yes. There are plenty of maintenance issues to be dealing with anyway 

And actually yes, having example is good as you say if it's only a few locations with no category
