### ISSUE TITLE
At least some of house_au objects miss any feature tag

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#10985]
house_au produces entries without main tag defining them, at least for some cases.

https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/house_au.py

See
```
{
    "geometry": {
        "coordinates": [
            116.009751,
            -31.889656
        ],
        "type": "Point"
    },
    "id": "7UNOSUSvepmjYPRCfX3aX1krGV4=",
    "properties": {
        "@source_uri": "https://www.house.com.au/api/get-stores",
        "@spider": "house_au",
        "addr:city": "Midland",
        "addr:country": "AU",
        "addr:postcode": "6056",
        "addr:state": "WA",
        "addr:street_address": "Shop T024, Midland Gate S/C, 274 Great Eastern Highway",
        "name": "HOUSEB&B - Midland",
        "opening_hours": "Mo-We 09:00-17:30; Th 09:00-21:00; Fr 09:00-17:30; Sa 09:00-17:00; Su 11:00-17:00",
        "phone": "+61 8 6244 8014",
        "ref": "652",
        "website": "https://www.house.com.au/stores/housebb-midland"
    },
    "type": "Feature"
}
````

**Comment by CloCkWeRX** [comment]
What's the correct tagging for "continually pretending to close down?"/selling fear of missing out on a bargain!

Shop homewares/specifically kitchenware

**Comment by matkoniecz** [comment]
> What's the correct tagging for "continually pretending to close down?"/selling fear of missing out on a bargain!

I would say it is a business model, and seen also with clothes shop and shoe shops. I would not tag them with one `shop=` tag. And not sure do we want to classify dark patterns and which kind of predatory marketing they do.

We have https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhouseware and https://wiki.openstreetmap.org/wiki/Tag:shop%3Dkitchen and https://wiki.openstreetmap.org/wiki/Tag:shop%3Dkitchenware

I guess that `shop=kitchenware` (unless they sell also larger furniture, then maybe `shop=kitchen`, though that tag name is not great)

**Comment by CloCkWeRX** [comment]
Knives, pans and chopping boards=kitchenware then.

**Comment by davidhicks** [comment]
They sell other random junk such as toilet brush holders and pet beds so I'd suggest `shop=houseware` is most appropriate as this category is defined on OSM wiki as being broad enough to include kitchenware, bathroomware, etc (a variety of household furnishing types).

**Comment by Cj-Malone** [comment]
NSI has `shop=houseware`, strong vote to follow them.

https://nsi.guide/index.html?t=brands&k=shop&v=houseware&tt=q117921987
