### ISSUE TITLE
At least some of ctm objects miss any feature tag

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#10990]
ctm produces entries without main tag defining them, at least for some cases.

https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/ctm.py

See
```
{
    "geometry": {
        "coordinates": [
            31.198257,
            -29.520771
        ],
        "type": "Point"
    },
    "id": "v6-gaKXsEbOJpS2F-DwjpGwHNYI=",
    "properties": {
        "@source_uri": "https://www.ctm.co.za/storefinder/store/ctm-ballito",
        "@spider": "ctm",
        "addr:country": "ZA",
        "addr:full": "2 Moffat Dr, Ballito Business Park, Ballitoville, 4399",
        "addr:state": "KwaZulu-Natal",
        "branch": "Ballito",
        "brand": "CTM",
        "brand:wikidata": "Q127378361",
        "email": "ballitobm@ctm.co.za",
        "opening_hours": "Mo-Tu 08:00-17:00; We 08:30-17:00; Th-Fr 08:00-17:00; Sa 08:00-16:00; Su 09:00-14:00",
        "phone": "+27 32 426 0001",
        "ref": "https://www.ctm.co.za/storefinder/store/ctm-ballito",
        "website": "https://www.ctm.co.za/storefinder/store/ctm-ballito"
    },
    "type": "Feature"
}
````

**Comment by arrival-spring** [comment]
See #10878, should be fixed on next NSI update

**Comment by matkoniecz** [comment]
I guess I could and should look at https://github.com/alltheplaces/alltheplaces/commits/master/locations/spiders/ctm.py and https://github.com/osmlab/name-suggestion-index/tags and do not complain about spiders younger than such date + 10 days for ATP run to be completed.

But it requires either manual date checking or adding some fiddly automation. I wonder is there some good way to get both of this dates.

There is, probably, some way to get file history dates from git repository.

And https://github.com/osmlab/name-suggestion-index/tags in the end is also from git repository, so should be available with some scripting.
