### ISSUE TITLE
McDonald's Italia

### ISSUE THREAD

**Issue by ivanbranco** [alltheplaces/alltheplaces#11016]
### Brand name

McDonald's

### Wikidata ID

Q38076

### Store finder url(s)

https://www.mcdonalds.it/ristorante

### Sample store page url

https://www.mcdonalds.it/ristorante/liguria/imperia/ventimiglia

### Countries?

IT

### Difficulty?

None

### Number of POI?

100+ (726)

### Behaviours

- [X] Has coordinates?
- [X] Has opening hours?
- [ ] JSON API?
- [ ] Embedded JSON?
- [ ] HTML markup?
- [ ] Structured Data? (`pipenv run scrapy sd (specific page url)`) or [validator](https://validator.schema.org/) has content
- [ ] Open Graph Data?
- [ ] Sitemap? (`pipenv run scrapy sitemap (url)`)
- [ ] Requires proxy?
- [ ] Has 'bot protection' (Cloudflare, etc)?

**Comment by ivanbranco** [comment]
Stefano from the Italian OSM Telegram group reported that there's already this: https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/mcdonalds_it.py
So maybe I should have reported it as a broken spider? Not sure

**Comment by ivanbranco** [comment]
The latest release still have 0 McDonald's in Italy, when will they be featured? I'm not really aware of ATP technicalities.

**Comment by iandees** [comment]
Looks like the CDN gave the spider 403s: https://alltheplaces-data.openaddresses.io/runs/2024-10-19-13-32-19/stats/mcdonalds_it.json. I don't see anything in the logs, though: https://alltheplaces-data.openaddresses.io/runs/2024-10-19-13-32-19/logs/mcdonalds_it.txt
