### ISSUE TITLE
mussala_bg has unparsed opening hours in data source, maybe parsable and useful (maybe not)

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#11028]
https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/mussala_bg.py

https://mussalains.com/wp-admin/admin-ajax.php?action=store_search&lat=43.21405&lng=27.914733&autoload=1

`'<table role="presentation" class="wpsl-opening-hours"><tr><td>Понеделник</td><td><time>09:00 - 18:00</time></td></tr><tr><td>Вторник</td><td><time>09:00 - 18:00</time></td></tr><tr><td>Сряда</td><td><time>09:00 - 18:00</time></td></tr><tr><td>Четвъртък</td><td><time>09:00 - 18:00</time></td></tr><tr><td>Петък</td><td><time>09:00 - 18:00</time></td></tr><tr><td>Събота</td><td>Затворено</td></tr><tr><td>Неделя</td><td>Затворено</td></tr></table>'`

**Comment by Dimitar5555** [comment]
Thank you for noticing it! In the future, feel free to ping me if it relates to any Bulgarian spider.

**Comment by matkoniecz** [comment]
Will try to do it in future!
