### ISSUE TITLE
starbucks_jp - seems that it should have Japanese name

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#11048]
No local knowledge, not verified this deeply, maybe we should ask local community - but Japanese name seems to be used for Starbucks in Japan (but it may be also just NSI pushing some tagging).

See https://www.openstreetmap.org/search?query=starbucks%2C%20japan#map=19/35.658902/139.732012

See https://www.openstreetmap.org/search?query=%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%83%83%E3%82%AF%E3%82%B9%2C%20japan#map=19/35.658902/139.732012

https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/starbucks_jp.py

**Comment by arrival-spring** [comment]
I think the only issue here is that it is showing brand="Starbucks" instead of brand="高山岡本店", so seems an easy fix

**Comment by matkoniecz** [comment]
Yeah, I have not made as I was not entirely sure is `高山岡本店` correct

**Comment by arrival-spring** [comment]
My thinking is that if it's on NSI then it is at least being actively used, and at the moment NSI has more visibility than ATP so errors are fewer

**Comment by j9d3it** [comment]
anything that has 店 at the end is the branch name. brand:en = Starbucks and brand=スターバックス is best.

**Comment by arrival-spring** [comment]
> I think the only issue here is that it is showing brand="Starbucks" instead of brand="高山岡本店", so seems an easy fix

I don't know where I got that from, but I did indeed use `"brand": "スターバックス"` in the fix (as per NSI)
