### ISSUE TITLE
starbucks_cn - seems to be using Chinese letters, not latin ones in mainland China - while ATP has ASCII

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#11058]
https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/starbucks_cn.py

**Comment by arrival-spring** [comment]
(I wrote this spider)

Can you explain more what you think the issue is? 

NSI has 

```
"name": "星巴克",
"name:en": "Starbucks",
"name:zh": "星巴克",
```

And all features here have, where available in the data, similar tagging. So main key in zh and copied into :zh subkey, with en in the :en key.

e.g.

```
addr:city	嘉峪关市
addr:city:en	JIAYUGUAN
addr:city:zh	嘉峪关市
```

**Comment by matkoniecz** [comment]
looking at it again, this one is not having English name

**Comment by matkoniecz** [comment]
Thanks for spotting! It seems I got confused by Taiwan one, this one has `brand = 星巴克`
