### ISSUE TITLE
vestis_uniform_services_us seems to list service areas, not actual POIs

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#11070]
see say https://www.vestis.com/our-locations/vestis-dallas for `atp_ref = 10867`

https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/vestis_uniform_services_us.py

**Comment by davidhicks** [comment]
Each location I checked in Texas has a different physical address and phone number listed though...?

**Comment by matkoniecz** [comment]
hmmm, maybe I misinterpreted something
