### ISSUE TITLE
It seems that Forever New is called Ever New, at least in Canada

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#11088]
https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/ever_new_ca.py

https://www.evernew.ca/

`{"brand": "Forever New", "brand_wikidata": "Q119221929"}`

should it be changed to

`{"brand": "Ever New", "brand_wikidata": "Q119221929"}`

with the same id, or should it have new `brand_wikidata`?

**Comment by Cj-Malone** [comment]
https://nsi.guide/index.html?t=brands&k=shop&v=clothes&tt=q119221929

CA should be `brand=Ever New` everywhere else should be `brand=Forever New`. Same wikidata.
