### ISSUE TITLE
playa_bowls_us spider returns incomplete address

### ISSUE THREAD

**Issue by elevenchars** [alltheplaces/alltheplaces#11116]
### Spider name

playa_bowls_us

### Log output

https://alltheplaces-data.openaddresses.io/runs/2024-10-12-13-32-10/logs/playa_bowls_us.txt

### Example bad data or results

```
addr:full=12400 Highway 290, Suite 440
```

### Expected behaviour or results

```
addr:full=12400 Highway 290, Suite 440, Austin, TX, 78737
```

### Possible causes?

`address` key in API response only contains the street address, the rest is contained in `city`, `state`, and `zip_code` keys, respectively. Here's the relevant excerpt of the response from `/api/locations`:

```
{
  "id": 15225,
  "name": "Dripping Springs",
  "slug": "dripping-springs",
  "link": "https://www.playabowls.com/location/dripping-springs",
  "timing": "Mon - Sat: 8am - 8pm, Sun: 9am - 6pm",
  "status": "publish",
  "address": "12400 Highway 290, Suite 440",
  "city": "Austin",
  "state": "TX",
  "zip_code": "78737",
  "latitude": 30.2080809,
  "longitude": -97.97863609999999,
  "place_id": "EigxMjQwMCBVUy0yOTAgIzQ0MCwgQXVzdGluLCBUWCA3ODczNywgVVNBIh8aHQoWChQKEgn__8MIE0ZbhhHKjLjsuS0VVhIDNDQw",
  "contact_number": "(512) 580-1355",
  "order_now_link": "https://order.tapmango.com/merchant/4760f4df-7def-406b-8bde-a974fb809f89/11479",
  "image_url": null,
  "location_comingsoon": false
}
```

**Comment by matkoniecz** [comment]
In guess that fix is to rename "full" to "street address"

**Comment by matkoniecz** [comment]
https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/playa_bowls_us.py
