### ISSUE TITLE
brand:logo should probably be never kept, as brand is not POI-specific in general

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#11183]
`brand:logo=https://graph.facebook.com/TomTom/picture?type=large`

see also `icon`
```
{
    'ref': 'https://www.openstreetmap.org/node/11099709943',
    'office': 'company',
    'brand:logo': 'https://graph.facebook.com/TomTom/picture?type=large',
    'contact:instagram': 'tomtomglobal',
    'contact:youtube': 'https://www.youtube.com/channel/UC1iURwco4pUIQgoX8vYaO6g',
    'wikimedia_commons': 'Tt live 1000.jpg',
    'icon': 'https://cdn.jsdelivr.net/gh/mapbox/maki/icons/suitcase.svg',
    '@source_uri': 'https://download.tomtom.com/open/fcd/pois.json',
    '@spider': 'tomtom',
    'addr:housenumber': '100',
    'addr:street': 'Century Center Court',
    'addr:city': 'San Jose',
    'addr:state': 'CA',
    'addr:postcode': '95112',
    'addr:country': 'US',
    'name': 'TomTom',
    'website': 'https://www.tomtom.com/',
    'contact:twitter': 'tomtom',
    'contact:facebook': 'https://www.facebook.com/TomTom/',
    'brand': 'TomTom',
    'brand:wikidata': 'Q682144',
    'nsi_id': 'tomtom-4a77e8'
}
```
https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/tomtom.py

**Comment by Cj-Malone** [comment]
There should be no expectation that things in the `brand` namespace are POI specific. Are you expecting a `brand:wikidata` to be unique per POI?

**Comment by matkoniecz** [comment]
I would expect that entries common for the entire brand and not actually POI-relevant would not be duplicated across POIs.

For me `brand:logo` link makes as much sense as having `brand:annual_profit_for_2024_report` link would make.

**Comment by iandees** [comment]
The brand's logo is useful on a POI (for example if a data consumer is interested in displaying the brand logo alongside the POI on a map if that's what appears on the road sign) whereas a financial report is not POI-related and wouldn't make sense to be included with the POI.

I could see a world where the brand-specific information is stored at a higher level than each feature (i.e. in a separate table in parquet or inside the GeoJSON `FeatureCollecton`), but our data model and output systems aren't set up for that. Most data consumers are interested in the individual POI and can normalize the duplicate stuff out if they want.

**Comment by matkoniecz** [comment]
Oh, I see a point here. I guess in my processing I will just throw it away and pretend that it does not exist if it is useful/potentially useful and will not be removed.

What about linking https://commons.wikimedia.org/wiki/File:Tt_live_1000.jpg across multiple POIs? (`    'wikimedia_commons': 'Tt live 1000.jpg',`)
