### ISSUE TITLE
Columbia

### ISSUE THREAD

**Issue by wessport** [alltheplaces/alltheplaces#1124]
https://www.columbia.com/stores

**Comment by davidhicks** [comment]
Appears to use the same locally.com store finder that `asics_us` and `crocs_us` use. We don't yet have a store finder class for locally.com.

Sample API call for brand stores:
`curl 'https://columbia.locally.com/stores/conversion_data?has_data=true&company_id=67&store_mode=&style=&color=&upc=&category=Brand&inline=1&show_links_in_list=&parent_domain=&map_ne_lat=48.60220231134477&map_ne_lng=-92.18225182145208&map_sw_lat=20.342279879097987&map_sw_lng=-135.99572838395235&map_center_lat=34.47224109522138&map_center_lng=-114.08899010270221&map_distance_diag=3000&sort_by=proximity&no_variants=0&only_retailer_id=&dealers_company_id=67&only_store_id=false&uses_alt_coords=false&q=false&zoom_level=4&lang=en-us&currency=USD' --compressed -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/117.0' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'X-Requested-With: XMLHttpRequest' -H 'DNT: 1' -H 'Alt-Used: columbia.locally.com' -H 'Connection: keep-alive' -H 'Referer: https://columbia.locally.com/conversion?company_name=Columbia&company_id=67&inline=1&category=&lang=en-us&currency=USD&dealers_company_id=67&host_domain=www.columbia.com' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-GPC: 1' -H 'TE: trailers'`

Sample API call for factory outlets:
`curl 'https://columbia.locally.com/stores/conversion_data?has_data=true&company_id=67&store_mode=&style=&color=&upc=&category=Factory&inline=1&show_links_in_list=&parent_domain=&map_ne_lat=48.60220231134477&map_ne_lng=-92.18225182145208&map_sw_lat=20.342279879097987&map_sw_lng=-135.99572838395235&map_center_lat=34.47224109522138&map_center_lng=-114.08899010270221&map_distance_diag=3000&sort_by=proximity&no_variants=0&only_retailer_id=&dealers_company_id=67&only_store_id=false&uses_alt_coords=false&q=false&zoom_level=4&lang=en-us&currency=USD' --compressed -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/117.0' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'X-Requested-With: XMLHttpRequest' -H 'DNT: 1' -H 'Alt-Used: columbia.locally.com' -H 'Connection: keep-alive' -H 'Referer: https://columbia.locally.com/conversion?company_name=Columbia&company_id=67&inline=1&category=&lang=en-us&currency=USD&dealers_company_id=67&host_domain=www.columbia.com' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-GPC: 1'`

Sample API call for clearance stores:
`curl 'https://columbia.locally.com/stores/conversion_data?has_data=true&company_id=67&store_mode=&style=&color=&upc=&category=clearancestore&inline=1&show_links_in_list=&parent_domain=&map_ne_lat=48.60220231134477&map_ne_lng=-92.18225182145208&map_sw_lat=20.342279879097987&map_sw_lng=-135.99572838395235&map_center_lat=34.47224109522138&map_center_lng=-114.08899010270221&map_distance_diag=3000&sort_by=proximity&no_variants=0&only_retailer_id=&dealers_company_id=67&only_store_id=false&uses_alt_coords=false&q=false&zoom_level=4&lang=en-us&currency=USD' --compressed -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/117.0' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'X-Requested-With: XMLHttpRequest' -H 'DNT: 1' -H 'Alt-Used: columbia.locally.com' -H 'Connection: keep-alive' -H 'Referer: https://columbia.locally.com/conversion?company_name=Columbia&company_id=67&inline=1&category=&lang=en-us&currency=USD&dealers_company_id=67&host_domain=www.columbia.com' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-GPC: 1'`
