### ISSUE TITLE
EZ Mart (Michigan)

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#1126]
http://blarneycastleoil.com/ez-mart-promo/ez-mart-locations/

**Comment by CloCkWeRX** [comment]
https://blarneycastleoil.com/ez-mart-locations/
https://blarneycastleoil.com/wp-json/wpgmza/v1/features/base64eJyrVkrLzClJLVKyUqqOUcpNLIjPTIlRsopRMopR0gEJFGeUFni6FAPFomOBAsmlxSX5uW6ZqTkpELFapVoABXgWuw
