### ISSUE TITLE
Free People

### ISSUE THREAD

**Issue by wessport** [alltheplaces/alltheplaces#1141]
https://www.freepeople.com/stores/

**Comment by RitikMody** [comment]
I am interested in doing this , can you please assign this to me @wessport @reidab @jleedev @dphiffer @tonyskapunk

**Comment by iandees** [comment]
You can just submit a PR. You don't need to have the issue assigned to you. It's not likely that anyone else is also doing this work.

**Comment by RitikMody** [comment]
okay thank you

**Comment by davidhicks** [comment]
Fixed in #5448
