### ISSUE TITLE
Data Update Frequency

### ISSUE THREAD

**Issue by fishcharlie** [alltheplaces/alltheplaces#1143]
On https://www.alltheplaces.xyz, the last data update was over a week ago. How often does that data get updated?

**Comment by iandees** [comment]
It gets updated roughly weekly. Right now the trigger is me manually running the script to kick off the update.

**Comment by fishcharlie** [comment]
@iandees Any chance we could kick that off? There have been some good PRs merged in over the past week.

**Comment by iandees** [comment]
Sure thing. I usually do it on Friday so that it's ready on Saturday morning. 👍
