### ISSUE TITLE
Global output link not updating on main page

### ISSUE THREAD

**Issue by justinelliotmeyers** [alltheplaces/alltheplaces#11458]
Can the full upload be updated? Thanks!
![image](https://github.com/user-attachments/assets/6bdf16a7-ab58-4dc4-ac27-42316ec29698)

**Comment by iandees** [comment]
Hey Justin! The weekly update process is still running (you can see the latest update was from November 16th [here](https://www.alltheplaces.xyz/spiders.html)), but the thing that updates this download link on the home page must be broken. I'll take a look.

**Comment by iandees** [comment]
I made an attempt to fix this in 793278ce88fc0f96ae045771938c11d607806ef7, but it seems like the history fix didn't work. I'll check it out.

**Comment by iandees** [comment]
This should be fixed now.
