### ISSUE TITLE
Menards

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#116]
http://www.menards.com/main/storeLocator.html

**Comment by iandees** [comment]
Menards uses Incapsula to block scrapers. Could use something like https://github.com/ziplokk1/incapsula-cracker-py3 to get around it.

**Comment by ADWSr** [comment]
unassigned myself, Incapsula a bit more difficult than anticipated.

**Comment by eusid** [comment]
It says there is no way around recaptcha 2, but there actually is. There are API with human solvers that you can use. You can use OCR for all other captcha types.

**Comment by iandees** [comment]
I don't want to work around recaptcha. Let's skip this one for now.

**Comment by DerekMcDaniel** [comment]
Working on this, bypass working on trial run.

**Comment by iandees** [comment]
Reopening to get lat/lon added based on @maxerickson's comment here: https://github.com/alltheplaces/alltheplaces/pull/604#issuecomment-353220111

**Comment by DerekMcDaniel** [comment]
Good find, I saw the storeList originally, however it cuts off at around 30 stores on chrome. I switched to firefox and the list is much longer. :)

**Comment by iandees** [comment]
Closed in #703.
