### ISSUE TITLE
Possible collaboration?

### ISSUE THREAD

**Issue by KAMI911** [alltheplaces/alltheplaces#1160]
Hi Folks!
I am working on a somewhat similar project that has main goal to provide importable osm files for OpenStreetMap project. I am mainly focusing to Hungarian country, but I am open to scrape even more countries info.
The Project is OSM POI Matchmaker, and I built in several tools to check and match POIs compared to OSM dataset. So it mainly fetch from the company data, fix and compare them against OSM, and merge to OSM creating JSOM compatible OSM files.
You can find it here:
https://github.com/KAMI911/osm_poi_matchmaker
Prepared data are here: https://github.com/KAMI911/osm-import-data
poi_address_* files contain the raw parsed data, that you can probably use for you app and
poi_address_merge_* files contain the OSM merged files. The code uses PostgreSQL to load OSM dataset there and do geom operations for match downloaded data and OSM dataset.
I will release a 'docker composed' version soon, so you may can try it, and figure out how can we collaborate. Until that you can use already available datasets, source, as you wish.

I also collect permissions for processing the peers data here: https://wiki.openstreetmap.org/wiki/WikiProject_Hungary/Import%C3%A1l%C3%A1s
Best regards,
KAMI

**Comment by iandees** [comment]
Hi @KAMI911. Thanks for pointing out your project! I'll be sure to point it out when people ask me about using All The Places with OSM.
