### ISSUE TITLE
AMF Bowling

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#1163]
https://www.amf.com/bowlero-location/finder?_format=json

**Comment by RitikMody** [comment]
Can I please be assigned to this?
@iandees

**Comment by RitikMody** [comment]
I have sent a pull request , but it won't be considered for Hacktoberfest if this repository doesn't have Hacktoberfest topic .Please check into it. @thekuiperbelt

**Comment by thekuiperbelt** [comment]
https://github.com/alltheplaces/alltheplaces/pull/1588
