### ISSUE TITLE
Shake Shack

### ISSUE THREAD

**Issue by wessport** [alltheplaces/alltheplaces#1169]
https://www.shakeshack.com/locations/

**Comment by thomas536** [comment]
Looks like this was added in https://github.com/alltheplaces/alltheplaces/pull/901

**Comment by codeser** [comment]
@thomas536 when I download the file, Shake Shack is empty (0 bytes)

**Comment by iandees** [comment]
It's likely that the Shake Shack spider has stopped working. It probably needs to be updated due to some change on the website.

**Comment by Cj-Malone** [comment]
Fixed in #3929
