### ISSUE TITLE
Consider adding a third-party library for assisting with data extraction

### ISSUE THREAD

**Issue by rkpatel7** [alltheplaces/alltheplaces#1209]
I noticed in a lot of spiders repeated xpath declarations for common standards like microdata.

There appear to be libraries that can be used to assist with extraction on sites that use standards like [W3C's HTML Microdata](http://www.w3.org/TR/microdata/) or [embedded JSON-LD](http://www.w3.org/TR/json-ld/#embedding-json-ld-in-html-documents) without having to always repeat the same xpath declarations. It could be easier for newcomers to easily add spiders if there was also documentation on how to use the library in a spider. Some of these libraries are [extruct](https://github.com/scrapinghub/extruct) and [microdata](https://github.com/edsu/microdata) with extruct being the most popular.

This stems from my comment on https://github.com/alltheplaces/alltheplaces/issues/1058 where I was exploring some of these libraries.

To be clear this is not a proposal to refactor all existing spiders to use the libraries or to prevent new spiders from using the existing approach. This is just a proposal for adding a new way of extracting the data.

I am curious to hear about any potential downsides to this approach.

**Comment by iandees** [comment]
This would be pretty nice. Two thoughts:

- We should test how much more time this adds to a spider run – presumably it would be a second parse through the page data after scrapy parses it into the XML document.
- Does scrapy have a base spider that does the microdata parse for you?

**Comment by CloCkWeRX** [comment]
Also solved with StructuredDataSpider I think, closable?
