### ISSUE TITLE
Dominos Pizza

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#122]
https://www.dominos.com/en/pages/order/?locations=1#/locations/

**Comment by vlad555** [comment]
taking this

**Comment by vlad555** [comment]
can I use google place search to get lan/lng of addresses?

**Comment by nvkelso** [comment]
Nope

**Comment by vlad555** [comment]
What should I do if there isn't position information  on the grabbing site?
Just addresses.

**Comment by iandees** [comment]
Pull in the addresses and don't set lat/lon for now.

**Comment by vlad555** [comment]
Ok, thank you for clarification
