### ISSUE TITLE
Quiznos

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#129]
http://restaurants.quiznos.com/

**Comment by iandees** [comment]
No progress for 6 days, re-opening this for others.

**Comment by ADWSr** [comment]
unassigning, appears to be complete and merged (issue was still open)

**Comment by josh0203e** [comment]
This issue is not closed

**Comment by iandees** [comment]
Looks like we've got just about all of them? Reopen if there are more than ~370.
