### ISSUE TITLE
Aldi

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#132]
https://storelocator.aldi.us/Presentation/AldiSued/en-us/Start

**Comment by iandees** [comment]
There's Aldi's all over the world (See https://aldi.de/). We should add spiders for the Aldi's all over the world.

**Comment by Eagle19243** [comment]
https://www.aldi.ie/store-finder
@iandees, As you can see, they want to type place name.
At this point, how can we scrap stores from the above website?
Exactly, we need to know all place names in Ireland?

**Comment by iandees** [comment]
If you type in something like "Dublin" and look at the browser's developer tools when you do the search, you can see an XHR request being made like this:

https://www.aldi.ie/api/store-finder/search?q=dublin&address=Dublin&latitude=53.3498053&longitude=-6.260309699999993

Try adapting that and see what you can get.

**Comment by Eagle19243** [comment]
@iandees, `Aldi LU` and `Aldi BE` has no (lat, lon) info on their website.
So I have ignored lat and lon in spider.

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by Cj-Malone** [comment]
- [ ] Germany - Aldi Nord
- [ ] Germany - Aldi Süd
- [ ] Australia - Aldi Süd
- [ ] Austria - Hofer Austria
- [ ] Belgium - Aldi Nord
- [ ] China - Aldi China Süd
- [ ] Denmark - Aldi Marked Nord
- [ ] France - Aldi Marché Nord
- [ ] Hungary - Aldi Hungary 
- [x] Ireland - Aldi Ireland Süd
- [ ] Italy - Aldi Italy 
- [ ] Luxembourg - Aldi Nord
- [ ] Netherlands - Aldi Nord
- [ ] Poland - Aldi Nord
- [ ] Portugal - Aldi Nord
- [ ] Slovenia - Hofer Slovenia
- [ ] Spain - Aldi Nord
- [ ] Switzerland - Aldi Suisse
- [x] United Kingdom - Aldi UK Süd
- [ ] United States - Aldi US Süd

List from Wikipedia, some of these are already done, some are broken.
