### ISSUE TITLE
Fred Meyer

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#134]
https://www.fredmeyer.com/storeLocator?hash=findStoreLink

**Comment by ianmcorvidae** [comment]
Fred Meyer is a kroger brand, and is most likely already covered by the existing Kroger importer. Double-check with the kroger.com store locator, though!

**Comment by iandees** [comment]
Going to clear the assignee on this so others can work on it. If you're still working on it, please re-assign to yourself and push up what you've got so far.

**Comment by MagnetonIO** [comment]
I checked fredmeyer already. it is same with kroger spider.
