### ISSUE TITLE
Support `brand:wikidata` / Wikidata QID for the brand

### ISSUE THREAD

**Issue by bhousel** [alltheplaces/alltheplaces#1343]
> I think we might want to support `brand:wikidata` to let spiders specify the Wikidata QID for the brand.

_Originally posted by @bhousel in https://github.com/alltheplaces/alltheplaces/pull/1342_

👀 I can help - we have a thing for this! 
https://github.com/osmlab/name-suggestion-index
Check out https://nsi.guide to see what is in there.

I'm not too familiar with alltheplaces scrapers, but would be great to find a way to link these projects.

**Comment by iandees** [comment]
Once we decide on where the data should go (in #1342) we'll need some help populating the field per spider. We can definitely use NSI to help find the QID to use!

**Comment by thomas536** [comment]
Is there any guidance on how to add wikidata metadata to crawlers at this point?

**Comment by iandees** [comment]
What do you think about the documentation change in #1436, @thomas536 ?

**Comment by thomas536** [comment]
@iandees looks good to me

**Comment by Cj-Malone** [comment]
Should All The Places start including NSI id's in the output? or maybe including the NSI tags directly?

**Comment by iandees** [comment]
That's a good question, @Cj-Malone. I pulled it into a different ticket and will close this one because we do the Wikidata stuff now.

**Comment by nvkelso** [comment]
+1 for Wikidata integration, and with the NSI, rad to see all these projects linking up :)
