### ISSUE TITLE
Wawa

### ISSUE THREAD

**Issue by aawiseman** [alltheplaces/alltheplaces#136]
Gas/convenience chain, like Sheetz

**Comment by aawiseman** [comment]
https://www.wawa.com/StoreLocator.aspx

**Comment by ecgreb** [comment]
+1

**Comment by iandees** [comment]
JSON API is:

https://www.wawa.com/Handlers/LocationByLatLong.ashx?limit=50&lat=43.1272254&long=-87.9432837
