### ISSUE TITLE
LA Fitness

### ISSUE THREAD

**Issue by justinelliotmeyers** [alltheplaces/alltheplaces#1366]
https://www.lafitness.com/Pages/findclub.aspx

**Comment by markman123** [comment]
there is a spider at ./locations/spiders/lafitness.py ; it's down atm. Is it not working?

**Comment by iandees** [comment]
Try running it and see if it works. We don't have a great way of seeing the run history of a spider.

**Comment by markman123** [comment]
Can't get the website to open (Australia); perhaps it's geoblocked?

**Comment by iandees** [comment]
Yea, they must be checking one of the headers and/or have geo blocking?

**Comment by davidhicks** [comment]
Spider exists per 4bf30d7ed37380258376c129292790b8d59a21b7

requires_proxy is set to True
