### ISSUE TITLE
Fix item_attribute white space issue

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1391]
There are leading and trailing white spaces in the items_attribute properties:
`item_attributes = { 'brand': "Dierberg's" }`

This should be corrected to remove leading and trailing white spaces:
`item_attributes = {'brand': "Dierberg's"}`

**Comment by thekuiperbelt** [comment]
@blackmad + bump

**Comment by blackmad** [comment]
apologies, just saw this.

this is just a code formatting issue, yes?

will try to get to it in the next few days

**Comment by markman123** [comment]
Perhaps a formatter (such as black) is in order? I've noticed many inconsistencies across spiders

**Comment by CloCkWeRX** [comment]
@iandees, solved by usage of black?

**Comment by iandees** [comment]
Yep!
