### ISSUE TITLE
Stale data download?

### ISSUE THREAD

**Issue by thomas536** [alltheplaces/alltheplaces#1413]
On https://www.alltheplaces.xyz, looks like the dump hasn't been updated in a while. I happened to notice some stale hours for Walgreens, so I was curious if it's expected to be from mid-December or should be more recent?

```
618555 rows from 488 spiders, updated Sat Dec 14 21:02:15 UTC 2019
```

Thanks!
Thomas

**Comment by iandees** [comment]
Thanks for letting me know! It looks like the script that runs it weekly has stopped. I kicked it off manually for now and will look into fixing the script.

**Comment by iandees** [comment]
The manual run recently finished and the info HTML got updated:

```
Download (53.2 MB)
640744 rows from 535 spiders, updated Wed Jan 29 23:47:29 UTC 2020
```

I also fixed the cron so that builds will run once a week automatically, now.
