### ISSUE TITLE
Schlotzsky's

### ISSUE THREAD

**Issue by aawiseman** [alltheplaces/alltheplaces#143]
http://www.schlotzskys.com/find-your-schlotzskys/

**Comment by sean-boothby** [comment]
Hope I am looking at a good place to start this time.
@iandees 
@nvkelso

**Comment by nvkelso** [comment]
Go for it :)

**Comment by sean-boothby** [comment]
@nvkelso 
Been working on this, and I stumbled upon this wonderful library https://geopy.readthedocs.io/en/1.10.0/
Basically it allows for conversion of address to lat and lon. Apparently used by many big tech companies, seems reliable.

Found a list through schlotzsky of all the restaurants, however on quite a number of pages the google maps interface is completely unworking (loading scholotzskys in Turkey for instance). 
Would it be possible to use the above library? 

Just wanted to ask about!

**Comment by nvkelso** [comment]
@iandees what say you? If Mapzen Search, sure?
