### ISSUE TITLE
TravelCenters of America

### ISSUE THREAD

**Issue by thomas536** [alltheplaces/alltheplaces#1430]
They publish a convenient xls with the location data: 

http://www.ta-petro.com/assets/ce/Documents/Master-Location-List.xls

Is there any guidance on how to parse xls in alltheplaces? Are new library dependencies allowed?

**Comment by iandees** [comment]
I'd prefer not to add new library dependencies... but I suppose if it's the only way to get at data like this I'd take a look at a PR for it.

**Comment by thomas536** [comment]
IIRC they did expose a search api, which might be usable using the radius/bounding box method.  

Thanks for the reply. I'll mull over whether or not I'll do a PR.

**Comment by reidab** [comment]
This can be closed, per #1453

**Comment by thomas536** [comment]
Closing
