### ISSUE TITLE
Lidl

### ISSUE THREAD

**Issue by thismakessand** [alltheplaces/alltheplaces#1459]
Lidl operates in 29 countries (in order by # of branches)

- [x] Germany
- [x] France
- [x] United Kingdom
- [x] Poland
- [x] Italy
- [x] Spain
- [x] Netherlands
- [x] Belgium
- [x] Romania
- [x] Portugal
- [x] Greece
- [x] Austria
- [x] Czech Republic
- [x] Finland
- [x] Hungary
- [x] Sweden
- [x] Ireland
- [x] Slovakia
- [x] Denmark
- [x] Bulgaria
- [x] Croatia
- [x] Switzerland
- [x] United States
- [x] Slovenia
- [x] Lithuania
- [x] Serbia
- [x] Cyprus
- [x] Luxembourg
- [x] Malta
- [x] Latvia
- [x] Estonia

**Comment by Dimitar5555** [comment]
Sorry for the late response @Cj-Malone. Feel free to add them when you can.

**Comment by Cj-Malone** [comment]
#10569
