### ISSUE TITLE
Giant

### ISSUE THREAD

**Issue by aawiseman** [alltheplaces/alltheplaces#146]
https://giantfood.com/store/locator/

**Comment by alfbrown** [comment]
working on this

**Comment by alfbrown** [comment]
HI aawiseman, I tried scraping this site for a few days now and I can not find the data source for all their locations. When I type in a zipcode, I can identify all the locations that were returned in the developer tools but this only a subset of all the locations. Any ideas?

**Comment by iandees** [comment]
Going to clear the assignee on this so others can work on it. If you're still working on it, please re-assign to yourself and push up what you've got so far.
