### ISSUE TITLE
King Sooper

### ISSUE THREAD

**Issue by aawiseman** [alltheplaces/alltheplaces#147]
Mostly midwestern https://www.kingsoopers.com/storeLocator?hash=findStoreLink

**Comment by ianmcorvidae** [comment]
King Soopers is a kroger brand, and all kroger-brand stores appear on their main site, so, this is probably covered by https://github.com/iandees/all-the-places/blob/master/locations/spiders/kroger.py -- you should double-check by comparing results from the kroger.com locator though, I imagine

**Comment by sweetdream0729** [comment]
working on this
