### ISSUE TITLE
Harris Teeter

### ISSUE THREAD

**Issue by aawiseman** [alltheplaces/alltheplaces#148]
Mostly southeastern https://www.harristeeter.com/store/#/app/store-locator

**Comment by SelfnessAid** [comment]
working on this

**Comment by SelfnessAid** [comment]
hi, @iandees 
I am working on this issue.
but I found this website is not allowed crawling.
I've changed the User-Agent and tried, but always was blocked to scrape.
do you have any suggestion?

**Comment by iandees** [comment]
I'd recommend un-assigning and finding an easier one for now. We can come back to this later.

**Comment by SelfnessAid** [comment]
okay, got you.
