### ISSUE TITLE
Australian Banks

### ISSUE THREAD

**Issue by sabman** [alltheplaces/alltheplaces#1544]
Major Australian Bank Branches: https://en.wikipedia.org/wiki/Banking_in_Australia

**Comment by devcocup** [comment]
@iandees We resumed the scrapy project now?
I am available to work and can dedicate 40 hours per week.
If there is one position for me, please let me know.

**Comment by iandees** [comment]
@devcocup The project is still running, but we don't have budget to pay. You're welcome to contribute, though!

**Comment by CloCkWeRX** [comment]
Suggest closing this in favor of specific individual banks or moving to discussions area and can merge it with all amenity bank in NSI without scrapers.
