### ISSUE TITLE
Need help getting locations for some fast food chains in US and a few stores - Paid Task

### ISSUE THREAD

**Issue by codeser** [alltheplaces/alltheplaces#1552]
Hi there

First of all thank you for an amazing library! It solves a huge problem many people are having.

I need the help of someone getting locations for some fast food chains. More than happy to pay for their time and effort of course. I hope it's okay posting paid requests on here?

My email is hasswa@gmail.com

Cheers,
Ahmed

**Comment by thekuiperbelt** [comment]
Perhaps opening an issue for the specific company might be the better route?

**Comment by iandees** [comment]
Yep, please open tickets for the chains you'd like to see scraped
