### ISSUE TITLE
Burger King US

### ISSUE THREAD

**Issue by codeser** [alltheplaces/alltheplaces#1554]
The file is there but 0 bytes / empty.

Why are some files empty out of curiosity?

**Comment by iandees** [comment]
An empty file means the spider ran but didn't produce any data. Usually because the website it's running against changed in some way that broke the spider.

**Comment by codeser** [comment]
@iandees thanks for explaining. In this case is there a way to access the archives maybe at some point the spider did download the data?

**Comment by iandees** [comment]
Not right now. Adding access to the archives is on my todo list, but it's not easily done at this point.
