### ISSUE TITLE
Aurecon

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1556]
https://www.aurecongroup.com/locations

**Comment by chethanagopinath** [comment]
@thekuiperbelt Hi, I was looking for beginner-friendly issues for Hacktoberfest and I was wondering if you could provide more detail to this?

**Comment by thekuiperbelt** [comment]
@chethanagopinath Hello, thanks for reaching out. I've labeled issues in the repository that are good options for creating your first spider. The ultimate goal is to scrape the URL linked above (or a better one if you find it) for [location information](https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md) regarding the business.  The project is built using [scrapy](https://docs.scrapy.org/en/latest/topics/spiders.html), so there is more documentation there the can also assist you as well. Feel free to comn through the spiders in the [locations folder ](https://github.com/alltheplaces/alltheplaces/tree/master/locations/spiders) as well. If you find one that you think looks interesting, go ahead and assign it to youself and feel free to reach out if you have more questions.

**Comment by rubyruins** [comment]
@thekuiperbelt, I would like to work on this. Will you guys be adding the `Hacktoberfest` label to the repository? Without it, contributions will not be counted, unfortunately.

**Comment by rubyruins** [comment]
@iandees, is this issue available? I'd like to take it up!

**Comment by iandees** [comment]
Yep, go ahead!

**Comment by iandees** [comment]
Pick a string that's unique to each location that will likely stay consistent. Maybe the phone number?

**Comment by rubyruins** [comment]
Makes sense. Will do!

**Comment by thekuiperbelt** [comment]
Closes #1556
