### ISSUE TITLE
Screwfix

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1557]
https://www.screwfix.com/jsp/tradeCounter/tradeCounterAllStoresPage.jsp

**Comment by rubyruins** [comment]
@thekuiperbelt, I would like to work on this. Will you guys be adding the `Hacktoberfest` label to the repository? Without it, contributions will not be counted, unfortunately.

**Comment by iandees** [comment]
I added the label. Go for it!

**Comment by rubyruins** [comment]
Great! Gonna do it soon.
