### ISSUE TITLE
PF Changs

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1561]
https://www.pfchangs.com/locations/us.html

**Comment by rubyruins** [comment]
I'm interested in working on this. Could you provide some more clarification on the issue?

**Comment by thekuiperbelt** [comment]
@rubyruins Hello, thanks for reaching out. I've labeled issues in the repository that are good options for creating your first spider. The ultimate goal is to scrape the URL linked above (or a better one if you find it) for [location information](https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md) regarding the business. The project is built using [scrapy](https://docs.scrapy.org/en/latest/), so there is more documentation there the can also assist you as well. Feel free to comb through the spiders in the [locations folder](https://github.com/alltheplaces/alltheplaces/tree/master/locations) for guidance on completed spiders, see [university_maryland_medical_system.py](https://github.com/alltheplaces/alltheplaces/blob/43ae0183827f340925555029e26b3810730be268/locations/spiders/university_maryland_medical_system.py) and [credit_agricole.py](https://github.com/alltheplaces/alltheplaces/blob/c0b9dfe7379e8fef192fc319fcebe2b10b352204/locations/spiders/credit_agricole.py). If you find an issue that you think looks interesting, go ahead and assign it to yourself and feel free to reach out if you have more questions.

**Comment by rubyruins** [comment]
Thank you! I am interested in working on this issue and am assigning myself, hope that is okay. I will send a PR soon :)

**Comment by rubyruins** [comment]
I am unable to self assign myself since I'm not a collaborator, could you please assign me to this issue?

**Comment by thekuiperbelt** [comment]
@rubyruins My apologies, I didn't realize that. I will assign this to you, and thank you for your collaboration. Happy crawling :) 🕷️

**Comment by thekuiperbelt** [comment]
@rubyruins I think if you would like this to be counted for the Hackbtoberfest 4 PR that are required, the PR's have to be submitted from Oct1-31. Just FYI! 😸

**Comment by rubyruins** [comment]
Yep! Thanks for the heads up :) I will open the PR after October starts!

**Comment by thekuiperbelt** [comment]
#1575
