### ISSUE TITLE
Ralph Lauren

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1562]
https://www.ralphlauren.com/Stores-ShowCountries

**Comment by thekuiperbelt** [comment]
@YorozuyaDev Hello, thanks for reaching out. I've labeled issues in the repository that are good options for creating your first spider. The ultimate goal is to scrape the URL linked above (or a better one if you find it) for [location information](https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md) regarding the business. The project is built using [scrapy](https://docs.scrapy.org/en/latest/), so there is more documentation there the can also assist you as well. Feel free to comb through the spiders in the locations folder as well. If you find an issue that you think looks interesting, go ahead and assign it to yourself and feel free to reach out if you have more questions.

**Comment by moohco** [comment]
@thekuiperbelt I'd like to take this one too!

**Comment by thekuiperbelt** [comment]
@moohco Awesome! Please assign it to yourself. Happy crawling, I hope you enjoy it. 🕷️
