### ISSUE TITLE
Bertuccis 

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1565]
https://locations.bertuccis.com/

**Comment by stephinson** [comment]
Hi @thekuiperbelt, 

I have already submitted one [PR](https://github.com/alltheplaces/alltheplaces/pull/1584). If it is okay to submit multiple PRs, I will be happy to take up this issue.

**Comment by iandees** [comment]
You can work on as many as you'd like, @stephinson.
