### ISSUE TITLE
Langham Hotels

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1566]
https://www.langhamhotels.com/en/locations

**Comment by iriyagupta** [comment]
@thekuiperbelt What exactly are we looking to resolve here?

**Comment by thekuiperbelt** [comment]
@iriyagupta  Hello, thanks for reaching out. I've labeled issues in the repository that are good options for creating your first spider. The ultimate goal is to scrape the URL linked above (or a better one if you find it) for [location information](https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md) regarding the business. The project is built using [scrapy](https://docs.scrapy.org/en/latest/url), so there is more documentation there the can also assist you as well. Feel free to comb through the spiders in the locations folder as well. If you find an issue that you think looks interesting, go ahead and assign it to yourself and feel free to reach out if you have more questions.

**Comment by moohco** [comment]
I'd like to take this

**Comment by thekuiperbelt** [comment]
@moohco Thank you, please go ahead and assign it to yourself! 👍

**Comment by moohco** [comment]
Unless I am missing something I can't assign it to myself?

**Comment by thekuiperbelt** [comment]
@moohco Ohhh thanks for notifying me, I have assigned this to you. Thank you for your collaboration :)

**Comment by moohco** [comment]
@thekuiperbelt thanks, should be fun :) you can assign the other too.
