### ISSUE TITLE
iFly

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1567]
https://www.iflyworld.com/find-a-location/

**Comment by Malthehave** [comment]
I will see if I can scrape this link. Wanted to try out for the Hacktoberfest

**Comment by thekuiperbelt** [comment]
@Malthehave Hello, thanks for reaching out. I've labeled issues in the repository that are good options for creating your first spider. The ultimate goal is to scrape the URL linked above (or a better one if you find it) for [location information](https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md) regarding the business. The project is built using [scrapy](https://docs.scrapy.org/en/latest/), so there is more documentation there the can also assist you as well. Feel free to comb through the spiders in the locations folder as well. If you find an issue that you think looks interesting, go ahead and assign it to yourself and feel free to reach out if you have more questions.

**Comment by davidhicks** [comment]
All locations appear to be returned as JSON data by API call:
`curl 'https://dataanywhereprod.azure-api.net/SL/V2/api/stores/' -H 'Accept: application/json' -H 'Referer: https://www.iflyworld.com/' -H 'ocp-apim-subscription-key: d8c538d6a8de45398f6f1d4a6405102f' -H 'Origin: https://www.iflyworld.com'`
