### ISSUE TITLE
Safelite

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1571]
https://www.safelite.com/store-locator/store-locations-by-state

**Comment by Bharadwaja92** [comment]
Hi @thekuiperbelt Can you pls let me know what needs to be done in this project?

**Comment by thekuiperbelt** [comment]
@Bharadwaja92 Hello, thanks for reaching out. I've labeled issues in the repository that are good options for creating your first spider. The ultimate goal is to scrape the URL linked above (or a better one if you find it) for [location information](https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md) regarding the business. The project is built using [scrapy](https://docs.scrapy.org/en/latest/), so there is more documentation there the can also assist you as well. Feel free to comb through the spiders in the [locations folder](https://github.com/alltheplaces/alltheplaces/tree/master/locations) for guidance on completed spiders, see [university_maryland_medical_system.py](https://github.com/alltheplaces/alltheplaces/blob/43ae0183827f340925555029e26b3810730be268/locations/spiders/university_maryland_medical_system.py) and [credit_agricole.py](https://github.com/alltheplaces/alltheplaces/blob/c0b9dfe7379e8fef192fc319fcebe2b10b352204/locations/spiders/credit_agricole.py) as examples. If you find an issue that you think looks interesting, let me know and I will assign it to you, and feel free to reach out if you have more questions.

**Comment by KatherineMichel** [comment]
I'd like to try to do this one... can I take it?

**Comment by iandees** [comment]
Go for it!

**Comment by KatherineMichel** [comment]
I haven't been able to complete this one. I ended up submitting another one. If someone else wants to work on it, they can!

**Comment by rubyruins** [comment]
I'd like to work on this if it's available

**Comment by Cj-Malone** [comment]
Go for it
