### ISSUE TITLE
🌟 Enhancement: 🌐 Web API

### ISSUE THREAD

**Issue by tisuela** [alltheplaces/alltheplaces#1593]
Hi, I was wondering about the *feasibility* of creating a Web API for people to easily access the data of this project, without downloading the data locally. If you guys think it's cool, I'll start working on a fork or independent repository, whichever seems appropriate as the planning goes on. 

## Why?
For the conveniences of end-users 😊. A Web API would negate the need of users having to re-downloading the latest data or running alltheplaces locally for simple tasks that don't require the entire tool. 

Additionally, this would allow for powerful 💪 queries that clients can be done via a simple request from a REST / GraphQL endpoint. The query would be executed on the servers-side so that users would not have to parse through multiple `geojson` files for, say, every gym in Seoul. 

## How?
The Web API would have REST and GraphQL endpoints. Starting out, it can run on an EC2 instance, such as the free-tier on AWS.

Lemme know what you guys think, or if this is a feature that has already been implemented!

**Comment by iandees** [comment]
What sort of queries and actions do you envision supporting with an API?

**Comment by nananananate** [comment]
Example queries:
* Returning every business on a street
* Returning every business on a street open at 8am
* All other fast food chains in cities with a McDonalds (would probably be multiple requests to a REST endpoint -- more feasible to be one request on a GraphQL end point)

**Comment by iandees** [comment]
Got it. I'm interested in seeing what you build, but keep in mind that all those questions will be very hard to answer with the data we collect.

I'd be more interested in keeping track of what spiders are working (returning data), how many rows each is returning, when they last returned data, and changes in result count over time.

**Comment by nananananate** [comment]
Sounds good, that's useful feedback! 

For monitoring spiders, are you looking more for a report at the end of crawling or would this be included it the web API?

**Comment by iandees** [comment]
Either/both ways would be useful: a report at the end of crawling with the results of each spider (worked/didn't work, # rows output, etc) would be helpful. The same data stored over time could be used to show changes over time to the number of results per spider.

There is some historical data. For example, the weekly build outputs stats like this per spider: https://data.alltheplaces.xyz/runs/2020-09-30-14-42-28/stats/belk.json

**Comment by nananananate** [comment]
gotcha!

**Comment by thomas536** [comment]
Was there ever any movement on historical stats? Or something like last known "good" (for any value of good) run for each spider?

**Comment by iandees** [comment]
Nope, weekly data is still there in the S3 bucket but we haven't made any changes to make it discoverable.

**Comment by thomas536** [comment]
(Ack. It'd be great to have a list of the run directory names.)

**Comment by vfosnar** [comment]
Hi, I'm working on a project where I need to always download the latest build with its timestamp. Has there been any progress on this issue? And if not, is there any way I can help making such data available?

**Comment by Cj-Malone** [comment]
To access releases, there is `https://data.alltheplaces.xyz/runs/history.json` the more recent ones have `output_url` and a bunch of other fields.

**Comment by iandees** [comment]
We haven't documented these endpoints yet because I wasn't sure how long they would last, but I guess they've been around for multiple years at this point so I should add them to some documentation somewhere :)

**Comment by iandees** [comment]
I added some information about the "API" to an API.md document. We can add to it in the future if we want!
