### ISSUE TITLE
KFC

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#16]
https://www.kfc.com/store-locator?query=90210

**Comment by SelfnessAid** [comment]
I'll work on this if anyone hasn't assigned this.

**Comment by iandees** [comment]
Go for it!

**Comment by SelfnessAid** [comment]
thanks.

**Comment by SelfnessAid** [comment]
Hi, @iandees 
Can you let me know more details about the opening_hours?
In this website, opening_hours come from with below format.
```
{
'mondayEnd':'11:00PM',
'sundayEnd':'11:00PM',
'addressLine':'126 Vermont Avenue,
#112', 'distance':9.65551299068785,
'cateringPhone':'',
'thursdayEnd':'11:00PM',
'buffet':False,
'catering':False,
'county':'Los Angeles',
'postalCode':'90004',
'wednesdayStart':'9:30AM',
'thursdayStart':'9:30AM',
'addressLine2':'',
'addressLine3':'',
'wednesdayEnd':'11:00PM',
'saturdayStart':'9:30AM',
'storeNumber':'F437005',
'cateringVendor':'',
'city':'Los Angeles',
'businessPhone':'(213)487-4503',
'sundayStart':'9:30AM',
'cateringDelivery':False,
'url':'',
'wifi':False,
'longitude':-118.291458,
'saturdayEnd':'11:00PM',
'cateringOnline':False,
'state':'CA',
'tuesdayStart':'9:30AM',
'fridayEnd':'11:00PM',
'tuesdayEnd':'11:00PM',
'latitude':34.072287,
'fridayStart':'9:30AM',
'entityID':'1141',
'mondayStart':'9:30AM',
'giftCards':False
},
```

Thanks.

**Comment by iandees** [comment]
@SelfnessAid The opening_hours property should follow the OpenStreetMap opening_hours format. There are examples [in their wiki page](https://wiki.openstreetmap.org/wiki/Key:opening_hours#Examples). All of the other spiders have some code to handle this that could be useful to follow. Let me know if you need some more guidance.

**Comment by SelfnessAid** [comment]
Yes, I saw their works.
But I think each spider has it's own method for opening_hour because each website has different result format.
anyway, let me look at opening_hours again.
Thanks.

**Comment by iandees** [comment]
Yes, each website has its own format for hours so the spider needs to parse that and output it in the expected format.

**Comment by SelfnessAid** [comment]
okay, I added opening_hours to KFCSpider.
