### ISSUE TITLE
Amazon stores, To extract location and time

### ISSUE THREAD

**Issue by Darknez07** [alltheplaces/alltheplaces#1613]

**Comment by iandees** [comment]
https://www.amazon.com/find-your-store/b/?node=17608448011

**Comment by Darknez07** [comment]
exactly i am trying on the same website you shared

**Comment by Darknez07** [comment]
So am i good to go?

**Comment by iandees** [comment]
Yep, go ahead.

**Comment by Darknez07** [comment]
What is the data type specification of longitudes and latitudes, are strings ok

**Comment by iandees** [comment]
They can be strings, yes. The output process converts them to floats for you.

**Comment by Darknez07** [comment]
@iandees  Thanks for feedback
