### ISSUE TITLE
Brass Tap Beer Bar

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1646]
https://www.brasstapbeerbar.com/locations.aspx

**Comment by davidhicks** [comment]
All store locations appear to be returned as JSON data with a single call to `https://www.brasstapbeerbar.com/pinsNearestBrassTap.ashx?lat1=27.950&lon1=-82.45&range=100000&food=%25&lunch=%25&brunch=%25&music=%25`
