### ISSUE TITLE
The Good Feet Store

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1649]
https://www.goodfeet.com/locations

**Comment by davidhicks** [comment]
SitemapSpider using `https://www.goodfeet.com/sitemap.xml` and `/locations/{state}/{slug}` as the filter. Then StructuredDataSpider (LD+JSON) to extract location information from individual store pages such as https://www.goodfeet.com/locations/pa/scranton  Opening hours are included in the structured data.
