### ISSUE TITLE
Sleep Number

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1650]
https://stores.sleepnumber.com/

**Comment by davidhicks** [comment]
This looks like the `YextSpider` with an overridden `request_page` method that overwrites the URL with:
`https://www.sleepnumber.com/yext/v2/accounts/me/entities/geosearch?location={latitude}%2C{longitude}8&limit=50&radius=2500&v=20200501&resolvePlaceholders=true&fields=googlePlaceId%2Caddress%2Cdescription%2Chours%2Cc_storePagesURLURL%2Cc_storeDisplayName%2Cc_siebelNumber%2Cc_landmark%2Cc_scheduleAnAppointmentURL%2Cclosed%2CgeocodedCoordinate%2CmainPhone&offset={offset}`

With `{latitude}` and `{longitude}` adjusted according to the 2500mi (or km?) search radius and `{offset}` used to page through search results 50 at a time.

I couldn't find an API key or other evidence that they're using the cloud hosted Yext API endpoint. It looks self-hosted.

**Comment by CloCkWeRX** [comment]
Cloudfare protection as well.

**Comment by CloCkWeRX** [comment]
Sleep Number

U.S.-based manufacturer of beds, foundations and bedding accessories

### Wikidata ID

Q7447640
https://www.wikidata.org/wiki/Q7447640
https://www.wikidata.org/wiki/Special:EntityData/Q7447640.json

### Store finder url(s)

Official Url(s): http://www.selectcomfort.com/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q7447640 http://www.selectcomfort.com/`
```
```
Official Url(s): https://www.sleepnumber.com/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q7447640 https://www.sleepnumber.com/`
```
```

**Comment by CloCkWeRX** [comment]
https://www.sleepnumber.com/stores/

**Comment by CloCkWeRX** [comment]
https://www.sleepnumber.com/api/storefront/store-locations?lat=-33.86714172363281&lng=151.2071075439453&limit=10&radius=2500

**Comment by CloCkWeRX** [comment]
https://www.sleepnumber.com/sitemap.xml.gz
