### ISSUE TITLE
Nothing Bundt Cakes

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1665]
https://www.nothingbundtcakes.com/bakeries

**Comment by davidhicks** [comment]
CrawlSpider of `https://www.nothingbundtcakes.com/find-a-bakery/` and StructuredDataSpider parse of individual location pages such as `https://www.nothingbundtcakes.com/find-a-bakery/il/mtprospect/bakery-99.html`

**Comment by CloCkWeRX** [comment]
Nothing Bundt Cakes

American retail bakery chain

### Wikidata ID

Q62082526
https://www.wikidata.org/wiki/Q62082526
https://www.wikidata.org/wiki/Special:EntityData/Q62082526.json

### Store finder url(s)

Official Url(s): https://www.nothingbundtcakes.com/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q62082526 https://www.nothingbundtcakes.com/`
```
```

**Comment by CloCkWeRX** [comment]
Added to wikidata
