### ISSUE TITLE
Van Wall

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1674]
https://vanwall.com/locations/

**Comment by davidhicks** [comment]
WPStoreLocator is used per `https://vanwall.com/wp-admin/admin-ajax.php?action=store_search&autoload=1`

Whilst 30 results are returned (the brand doesn't have many locations) it is possible that WPStoreLocator has been configured with a hard-coded results or radius search limit of the 1000mi/50 results that the GUI presents, or a higher number that the GUI doesn't display.

**Comment by CloCkWeRX** [comment]
https://vanwall.com/wp-admin/admin-ajax.php?action=store_search&lat=41.586835&lng=-93.624959&max_results=500&search_radius=10000&autoload=1 31 now
