### ISSUE TITLE
Mavis Discount Tire

### ISSUE THREAD

**Issue by thekuiperbelt** [alltheplaces/alltheplaces#1695]
https://www.mavistire.com/locations/

**Comment by davidhicks** [comment]
This includes a few different brands: `Mavis Tires & Brakes`, `NTB Tire & Service`, `Tuffy Tire & Auto`, `Action Gator Tire`, `Tire Kingdom Service Centers`, `STS Tire`, `Cole Muffler`, `Jack Williams Tire & Auto`, `Melvin's Tire & Auto`.

Individual store location details including opening hours returned as JSON data via: `https://apim-production-eastus.azure-api.net/content-svc/stores/{store_id}` and `https://apim-production-eastus.azure-api.net/content-svc/stores/{store_id}/amenities`

Multiple store location detailed returned as JSON data via:
`https://apim-production-eastus.azure-api.net/content-svc/stores/{store_id_1},{store_id_2},{store_id_3}/multi?include=storeHours%2CmavisMyWay%2Cservices`

For both of these API calls, header `Ocp-Apim-Subscription-Key: 38b1ddf34e6d45da8fcdd6a15a3741dc` needs to be sent, possibly other headers too.

Nearest X (where X can't be too large, e.g. 500 causes server timeout) locations to a coordinate can be returned with `https://www.mavis.com/api/stores/closest/?count=100&lat=0&lng=0`. Note that there is evidence of pagination being possible, but none of the typical `offset`, `skip`, `start`, `page` attributes appear to be accepted. Details such as opening hours are not contained within. From the JSON response, store IDs are within `response.json()["includes"]["Asset"][X]["fields"]["title"]` where X is an iterator for the `Asset` array. These store IDs can be used with the API calls `https://apim-production-eastus.azure-api.net/content-svc/stores/{store_id_1},{store_id_2},{store_id_3}/multi?include=storeHours%2CmavisMyWay%2Cservices` to retrieve store details.

Whilst all locations appear to be returned via JSON data at `https://www.mavis.com/_next/data/C3emQY9AEBGcPhquAi4vg/locations/all-stores.json`, this is only limited marker information with coordinates, sometimes an address, store name. There is no `{store_id}` in this JSON data. A slug is provided for a location page that has limited LD+JSON structured data, but dynamic calls are made to `https://apim-production-eastus.azure-api.net/content-svc/stores/{store_id}` and `https://apim-production-eastus.azure-api.net/content-svc/stores/{store_id}/amenities` to retrieve opening hours and other details.

**Comment by CloCkWeRX** [comment]
Mavis Discount Tire

tire retailer

### Wikidata ID

Q65058420
https://www.wikidata.org/wiki/Q65058420
https://www.wikidata.org/wiki/Special:EntityData/Q65058420.json

### Store finder url(s)

Official Url(s): https://www.mavistire.com/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q65058420 https://www.mavistire.com/`
```
```

**Comment by CloCkWeRX** [comment]
Added storefinder to wikidata

**Comment by CloCkWeRX** [comment]
Closable @iandees
