### ISSUE TITLE
Fix ExxonMobil scraper

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#176]
The ExxonMobil station finder website seems to have changed and no longer lists all stations. The scraper needs to be adjusted to scrape using this bounding-box API:

```
https://www.exxon.com/api/v1/Retail/retailstation/GetStationsByBoundingBox?Latitude1=29.7&Latitude2=29.8&Longitude1=-95.2&Longitude2=-95.5
```

This API seems to return 250 results at most.

I'm interested in hearing suggestions for how to handle APIs like this that only support geographic queries. In other similar situations (e.g. for the Esri scraper) I query in quadtile-like bounding boxes until I get fewer than the maximum results.

**Comment by sledjama** [comment]
i will be glad to fix this learn from this

**Comment by sledjama** [comment]
One approach that seems plausible, i guess that's what you meant by 

> I query in quadtile-like bounding boxes until I get fewer than the maximum results.

I got a large box,  the latitude and longitude of the north-west, somewhere in the north pacific ocean and 
that of the southeast somewhere in the bermuda. (will pick Alaska later)

then loop through from left to right/up to down with a mini box size to cover all US states.
only to reduce the box size till i get fewer than the maxumum result like you stated up there.
At 0.8 by 0.8 box, i got a max result of 232, and made 2612 requests

unfortunately this approach picked some parts of Canada, Mexico and the ocean
i will look forward to a way to cut the oceans out, maybe have an exclude list, but my questions are
 
1. Is this supposed to crawl just the United States or North America, or America. Exxon seems to be everywhere
2. What is your view as to excluding all boxes that returned 0 results, Exxonmobil may open a new outlet
there after excluding the area in my opinion

**Comment by iandees** [comment]
1. We want to get locations from around the world. Pulling in international locations would be great.
1. We should probably exclude water-only boxes, but I'd prefer to include all boxes including ones that return zero results.
