### ISSUE TITLE
No US McDonalds

### ISSUE THREAD

**Issue by fgomez828** [alltheplaces/alltheplaces#1781]

**Comment by iandees** [comment]
Thanks for letting us know that there the US McDonald's scraper isn't working. I can try to take a look next week, but it would be great if someone else had some time to look and see what's going on.

**Comment by davidhicks** [comment]
15192 locations returned in the 12 August 2023 run per https://data.alltheplaces.xyz/runs/2023-08-12-13-32-51/output/mcdonalds.geojson

Working right now from Australia too for at least the first few requests.

403 errors are being returned usually per 19 August 2023 run results at https://data.alltheplaces.xyz/runs/2023-08-19-13-31-56/stats/mcdonalds.json

It's likely data centre IPs are blocked or custom bot blocking is used.
