### ISSUE TITLE
Walgreens

### ISSUE THREAD

**Issue by ianmcorvidae** [alltheplaces/alltheplaces#18]
https://www.walgreens.com/storelocator/find.jsp?tab=store+locator&requestType=locator

**Comment by colanzio5** [comment]
working on this

**Comment by iandees** [comment]
No progress for 7 days, re-opening this for others.

**Comment by vlad555** [comment]
Have problems
Walgreen's page sends requests to google to get lat/lon and then second request to walgreen's server to get list of near shops (radius only 50miles)
scrapy don't do all these requests
I can use google API to request city positions and then ask list of near shops

**Comment by iandees** [comment]
They have a "Browse by state" listing: https://www.walgreens.com/storelistings/storesbystate.jsp?requestType=locator

**Comment by vlad555** [comment]
Of course I did
But at final stage they use algorythm I've described
![image](https://user-images.githubusercontent.com/9920034/34075055-501cba74-e270-11e7-9e00-021df3918ef6.png)
![image](https://user-images.githubusercontent.com/9920034/34075078-b81ed288-e270-11e7-8955-c276a73394b7.png)
![image](https://user-images.githubusercontent.com/9920034/34075092-02c1636e-e271-11e7-9993-44dd396325df.png)

I just ask you to let me using google API in spyder 
Or I can prepare table of cities and lan/lon pair to integrate it into spider
Thank you

**Comment by SelfnessAid** [comment]
@vlad555 
please look at this url.
https://customersearch.walgreens.com/storelocator/v1/stores/search
you may can put some static data with big radius and limit.
{"r":"50","lat":"38.5830","lng":"-77.3158","requestType":"locator","s":"15","p":"1"}
here lat and lng will be static.

**Comment by vlad555** [comment]
@SelfnessAid 
If you checked my 3-rd screenshot I already got this this link and parameters
But Ian said searching by lat/lng with small radius (50 miles in this case) isn't good solution.
In one project I had 9 circles for 800-mile radius.
With 50-mile circles we will have them much more and much more overlapped zones.
As you can see I've  asked about integrating  lat/lon points into spider.
But Ian still not answered

**Comment by iandees** [comment]
Yep, please hold off on writing these spiders until we come up with a way to efficiently crawl sites like these without tens of thousands of requests.
