### ISSUE TITLE
Health Centers

### ISSUE THREAD

**Issue by dianashk** [alltheplaces/alltheplaces#185]
- [x] [Planned Parenthood](https://www.plannedparenthood.org/health-center) (tracked in #184)
- [x] [Premier Urgent Care](http://www.premierimc.com/all-locations/)

Urgent Care Centers (source: https://www.healthdatamanagement.com/list/top-urgent-care-centers many more in that list)
- [x] [Concentra Clinics](https://www.concentra.com/urgent-care-centers/#g=&gtext=)
- [x] [MedExpress](https://www.medexpress.com/find-center.html)
- [x] [American Family Care](https://www.afcurgentcare.com/national-map-american-family-care-locations/)
- [x] [NextCare](https://nextcare.com/locations/)

**Comment by bealbrown** [comment]
I'll take Premier Urgent Care
