### ISSUE TITLE
Merge results from each source into one big results file for download

### ISSUE THREAD

**Issue by nvkelso** [alltheplaces/alltheplaces#187]
Right now each source is run independently. As part of a weekly chron job we should merge all the results into one big file (like GeoJSON, and also make available as CSV?).

**Comment by eusid** [comment]
hi, from Upwork. I can take this ticket or any of the spiders. I looked at 2 or 3 but they all required you input  a location, but one had an API that could be used. Was lookin for an easy one.

**Comment by iandees** [comment]
This is done. The output is on http://www.alltheplaces.xyz/.
