### ISSUE TITLE
Chipotle

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#205]

**Comment by sledjama** [comment]
https://www.chipotle.com/locations/
https://chipotle.ca/locations/
https://chipotle.fr/locations
https://chipotle.de/locations
https://chipotle.co.uk/locations

**Comment by sledjama** [comment]
@iandees Pls dont forget this issue has been resolved. Thanks.

**Comment by iandees** [comment]
Fixed in #232 .
