### ISSUE TITLE
CVS

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#209]

**Comment by kristinepetrosyan** [comment]
@iandees  working on this.

**Comment by kristinepetrosyan** [comment]
`
{"type":"FeatureCollection","features":[{"type": "Feature", "properties": {"addr:full": "520 Highway 119", "phone": "205-663-5405", "addr:city": "Alabaster", "addr:state": "AL", "addr:postcode": "35007", "ref": "https://www.cvs.com/store-locator/cvs-pharmacy-address/520+Highway+119-Alabaster-AL-35007/storeid=4867", "website:": "https://www.cvs.com/store-locator/cvs-pharmacy-address/520+Highway+119-Alabaster-AL-35007/storeid=4867"}, "geometry": {"type": "Point", "coordinates": [33.2388, -86.8178]}},
{"type": "Feature", "properties": {"addr:full": "250 S Colonial Dr", "phone": "205-564-2609", "addr:city": "Alabaster", "addr:state": "AL", "addr:postcode": "35007", "ref": "https://www.cvs.com/store-locator/cvs-pharmacy-address/250+S+Colonial+Dr-Alabaster-AL-35007/storeid=17350", "website:": "https://www.cvs.com/store-locator/cvs-pharmacy-address/250+S+Colonial+Dr-Alabaster-AL-35007/storeid=17350"}, "geometry": {"type": "Point", "coordinates": [33.2244, -86.8043]}}]}`
