### ISSUE TITLE
Best Buy

### ISSUE THREAD

**Issue by brentajones** [alltheplaces/alltheplaces#21]
http://www.bestbuy.com/site/store-locator/

**Comment by iandees** [comment]
No progress for 6 days, re-opening this for others.

**Comment by vikranthkr** [comment]
I had assigned it to myself on Friday night. I am done with Bestbuy US & Bestbuy Mexico. Working on Bestbuy Canada. @kristinepetrosyan are you working on this as well? I can push my code for US & Mexico if you want to work on it further.

**Comment by nvkelso** [comment]
Thanks for the update. In the future please only self assign when starting
work on an issue (not in anticipation of starting work).

**Comment by vikranthkr** [comment]
Thank you for getting back. I did self-assign it after starting work. I'll continue and assign it to myself

**Comment by kristinepetrosyan** [comment]
@iandees I had completed work on it. We can go with either implementation.
https://github.com/alltheplaces/alltheplaces/pull/600
