### ISSUE TITLE
No coordinates spider

### ISSUE THREAD

**Issue by fishcharlie** [alltheplaces/alltheplaces#2100]
How should spiders handle it if a site has no coordinates publicly listed and only has an address?

**Comment by iandees** [comment]
There's a good overview of this in the data format doc here: https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md#geometry

Basically: the spider should not set lat/lon in these cases.

**Comment by CloCkWeRX** [comment]
Move to discussions area? Useful question

**Comment by Cj-Malone** [comment]
It's been answered, along with many examples by now. We simply output the POI without coords. You may want to discus geocoding, but ultimately, it doesn't work technically in the scrapy context, also it will licensing drama.
