### ISSUE TITLE
MAPCO

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#2285]
https://www.mapcorewards.com/store-locator

Chain currently owned by a Chilean energy company https://en.wikipedia.org/wiki/Empresas_Copec

**Comment by davidhicks** [comment]
Paginated JSON API with 100 maximum locations returned per page: `https://web.mapcorewards.com/api/content/spaces/stores/types/store/entries?per_page=100&page=1`

**Comment by davidhicks** [comment]
316 locations according to https://web.mapcorewards.com/api/content/spaces/stores/types/store/entries?per_page=100&page=1

**Comment by CloCkWeRX** [comment]
This is now storerocket.
