### ISSUE TITLE
Help wanted adapting the code for lidl_uk.py to create a spider for Lidl Northern Ireland

### ISSUE THREAD

**Issue by ChrisSoderberg** [alltheplaces/alltheplaces#2337]
Lidl UK and Lidl Northern Ireland both use bing maps for their online store locations. I believe the author for lidl_uk.py targets bing maps directly and creates a bing maps query (https://docs.microsoft.com/en-us/bingmaps/spatial-data-services/query-api/query-by-id) to output a URL containing json data for Lidl UK branches which is then fed to the spider. I'm struggling to figure out how I might create a bing query that could do the same job for Lidl Northern Ireland

**Comment by CloCkWeRX** [comment]
https://www.lidl-ni.co.uk/
https://spatial.virtualearth.net/REST/v1/data/91bdba818b3c4f5e8b109f223ac4a9f0/Filialdaten-NIE/Filialdaten-NIE?$select=*,__Distance&$filter=Adresstyp%20eq%201&key=Asz4OJrOqSHy-1xEWYGLbFhH4TnVP0LL1xgj0YBkewA5ZrtHRB2nlpfqzm1lqKPK&$format=json&jsonp=Microsoft_Maps_Network_QueryAPI_2&spatialFilter=nearby(54.5578,-5.7589,4.9864904999999995)

**Comment by CloCkWeRX** [comment]
This spider already exists - 
```
class LidlNISpider(VirtualEarthSpider):
    name = "lidl_ni"
    item_attributes = LidlGBSpider.item_attributes

    dataset_id = "91bdba818b3c4f5e8b109f223ac4a9f0"
    dataset_name = "Filialdaten-NIE/Filialdaten-NIE"
```
Closable @iandees

**Comment by Cj-Malone** [comment]
I don't think NI is a real country code.
