### ISSUE TITLE
Geopy

### ISSUE THREAD

**Issue by sean-boothby** [alltheplaces/alltheplaces#319]
Never really got a total answer to use the library geopy. https://pypi.python.org/pypi/geopy
It is a great library and really helped with the schlotzskys scrape. 

Is quite reliable, and used by many companies. Just curious as I think it may help for some of the pages.
@iandees

**Comment by iandees** [comment]
I would prefer not to use geopy at this point. If we want to geocode I'd like to make it a pipeline step later. For now, if a site doesn't have lat/lon then we should leave it out and make sure there's enough address information to geocode it later.
