### ISSUE TITLE
Continuous integration issues

### ISSUE THREAD

**Issue by sean-boothby** [alltheplaces/alltheplaces#332]
Hey @iandees I ran into some issues when I put the pull request through for my spider. I am no github pro by any means, but it seems like my issue is with Travis CI.
Really not sure what this error means, but I was hoping since you have been working on this for a while you may be able to help.

Sorry to bother you.
Attached is a picture of the job log with what seems to be the error. Thanks!
![travis ci](https://user-images.githubusercontent.com/28799007/33807701-5039c10c-dda0-11e7-9e26-cecd0a3adf29.png)

P.S. sorry if I put this in the wrong place. Still getting used to github.

**Comment by iandees** [comment]
Sean, at this point the Travis build will only work if the PR is opened with a branch on this repository and not a fork. I can add you as a contributor so you can use this repo instead of your fork when I get home in a few hours.
