### ISSUE TITLE
Quality Inn

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#334]

**Comment by sledjama** [comment]
I am not familiar with Quality Inn, Google search points to https://www.choicehotels.com
can you confirm this URL?
 and any reason why all issues are self assigned and none to pick.

**Comment by iandees** [comment]
Yes, it looks like Quality Inn is part of Choice Hotels.

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.
