### ISSUE TITLE
Edeka

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#348]
Supermarket in Germany

https://www.edeka.de/marktsuche.jsp

**Comment by ethan626** [comment]
Unable to get latitude and longitude of the stores. 
Tried to replicate the JS created request to get the latitude and longitude which is sent in the response. 
Any ideas?

**Comment by iandees** [comment]
If you search for something like "Berlin" there's a POST to `https://www.edeka.de/search.xml` that you can use to get access to the locations.
