### ISSUE TITLE
AttributeError: 'TextResponse' object has no attribute 'body_as_unicode'

### ISSUE THREAD

**Issue by jleedev** [alltheplaces/alltheplaces#3491]
The update to Scrapy 2.6.0 (https://github.com/alltheplaces/alltheplaces/pull/3473) removed `scrapy.http.TextResponse.body_as_unicode`.

Should replace with `response.text` instead, but in many cases we should replace with `response.json()`.

**Comment by iandees** [comment]
Thanks for digging into that. I should have checked more closely.
