### ISSUE TITLE
Shell station

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#350]
http://www.shell.com/motorist/shell-station-locator.html

**Comment by kristinepetrosyan** [comment]
@iandees do you want information for only the us? or canada and mexico will also do?

**Comment by iandees** [comment]
US, Canada, and Mexico (and anywhere else), please.

**Comment by kristinepetrosyan** [comment]
👍 cool

**Comment by whoissteven** [comment]
If this is NOT being worked on please unassign yourself so I can assign myself. Thank you.

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by reidab** [comment]
This can be closed, per #1475
