### ISSUE TITLE
Poundland

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#3571]
[Store finder](https://www.poundland.co.uk/store-finder/)
[Store page](https://www.poundland.co.uk/store-finder/store_page/view/id/456/) includes a interesting JSON blob

[API](https://www.poundland.co.uk/rest/poundland/V1/locator) unsure how to call this, it returns JSON or XML.

**Comment by mjoe999** [comment]
From "my world":

`class PoundlandSpider(scrapy.Spider):`

    name = "poundland"
    start_urls = ['https://www.poundland.co.uk/rest/poundland/V1/locator/?'
                  'searchCriteria%5Bscope%5D=store-locator'
                  '&searchCriteria%5Blatitude%5D=55.95&searchCriteria%5Blongitude%5D=-3.18'
                  '&searchCriteria%5Bcurrent_page%5D=1&searchCriteria%5Bpage_size%5D=1000']

    def parse(self, response):
        obj = xmltodict.parse(response.text)
        converted = json.loads(json.dumps(obj))
        for store in converted['response']['locations']['item']:
            if not 'store' == store['type']:
                self.logger.warning("ignoring store type %s", store['type'])
                continue
            url = 'https://www.poundland.co.uk/store-finder/store_page/view/id/' + store['store_id']
            yield scrapy.Request(url, callback=self.parse_store_page, cb_kwargs=dict(store=store))

    def parse_store_page(self, response, store):
        # TODO: says if has ATM, parking and also quite interestingly if on high street, retail park etc!
        item = Brand.POUNDLAND.item(response)
        Util.extract_details(item, store)
        Util.postal_address(item)['streetAddress'] = ", ".join(list(Util.get_all_keys(store['address']['line'])))
        Util.extract_details(item, store['address'])
        Util.source_data(item)['bespoke_json'] = store
        yield Util.extract_location(item, store['geolocation'])
`

**Comment by mjoe999** [comment]
The above illustrates the concept of adding the response HTML into the "item" which is then picked up by pipeline code to decorate the item with social media links and other data. This is one item produced by the spider above, obviously the structure is different from the "All The Places" output but that is by the by. Note that the response HTML is removed by the pipeline as that can be rather unwieldy. I find it convenient to keep original JSON around (be it "standard" or bespoke) with the item as that has proved useful in a good many cases. It can also be a potential help in detecting per site differences between runs, helping answer the question "is it my code or is it the site that has changed".

`{"brand_data": {"name": "Poundland", "website": "https://www.poundland.co.uk/", "logo": "https://graph.facebook.com/poundland/picture?
type=large", "wikidata": "Q1434528"}, "logo": "https://graph.facebook.com/poundland/picture?type=large", "name": "Poundland", "name_st
ore": "Poundland", "website": "https://www.poundland.co.uk/store-finder/store_page/view/id/626/", "website_store": "https://www.poundl
and.co.uk/store-finder/store_page/view/id/626/", "brand_wikidata": "Q1434528", "brand_logo": "https://graph.facebook.com/poundland/pic
ture?type=large", "secondary": false, "dense": false, "category": {"primary": "SHOP", "secondary": "DEPARTMENTSTORE"}, "response": nul
l, "phone_number": "0131 226 3243", "postal_address": {"streetAddress": "120A Princes Street", "postalCode": "EH2 4AD", "addressLocali
ty": "Edinburgh", "addressCountry": "UK", "addr_full": "120A Princes Street, Edinburgh, UK, EH2 4AD"}, "source_data": {"bespoke_json":
 {"id": "2281", "name": "2281 Edinburgh Princes Street", "type": "store", "distance": "0.72", "address": {"company": "Poundland", "lin
e": "120A Princes Street", "city": "Edinburgh", "country": "UK", "postcode": "EH2 4AD"}, "geolocation": {"latitude": "55.95175000", "l
ongitude": "-3.19839000"}, "store_id": "626", "url_key": "2281", "description": null, "store_manager": null, "fax": null, "tel": "0131
 226 3243", "email": null, "store_features": "{\"atm\":\"false\",\"pepshopinshop\":\"false\",\"icestore\":\"false\",\"parking\":\"true
\",\"clickandcollect\":\"false\",\"storetype\":{\"highstreet\":\"true\",\"shoppingprecinct\":\"false\",\"shoppingcentre\":\"false\",\"
retailpark\":\"false\"}}", "close_date": null, "atm": "0", "pepshopinshop": "0", "icestore": "0", "parking": "1", "clickandcollect": "
0", "highstreet": "1", "retailpark": "0", "shoppingprecinct": "0", "shoppingcentre": "0", "is_pep_co_only": "0", "route": "store-finde
r/2281", "opening_hours": {"item": [{"day": "Monday", "hours": "08:00 - 19:00"}, {"day": "Tuesday", "hours": "08:00 - 19:00"}, {"day":
 "Wednesday", "hours": "08:00 - 19:00"}, {"day": "Thursday", "hours": "08:00 - 19:00"}, {"day": "Friday", "hours": "08:00 - 19:00"}, {"day": "Saturday", "hours": "08:00 - 19:00"}, {"day": "Sunday", "hours": "09:00 - 18:00"}]}, "open_today": "08:00 - 19:00"}}, "geo": {"latitude": "55.95175000", "longitude": "-3.19839000"}, "map_links": {"google": "http://maps.google.com/maps?q=55.95175000,-3.19839000", "osm": "https://www.openstreetmap.org/#map=19/55.95175000/-3.19839000", "bing": "https://www.bing.com/maps?lvl=19&cp=55.95175000~-3.19839000&sp=point.55.95175000_-3.19839000_X", "wikidata": "https://www.wikidata.org/wiki/Q1434528"}, "source_supplier": {"ingest_utc_secs": 1652940724, "name": "spiders/gbr/poundland_spider.py"}, "social_links": {"facebook": "https://www.facebook.com/Poundland", "twitter": "https://twitter.com/Poundland", "instagram": "https://www.instagram.com/poundland"}}`

**Comment by Cj-Malone** [comment]
Thank you, I was missing the `searchCriteria[scope]=store-locator` part of the URL.

Do you want to turn this into All the Places code and open a PR? I've got time this morning if you wanted me to help you

**Comment by JoeDixon-TomTom** [comment]
For myself I'm going to wait on the outcome of https://github.com/alltheplaces/alltheplaces/pull/3648 as this will make the integration of a whole bunch of my spiders simpler
