### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#3578]
What's the opinion on tests? In my opinion each spider should probably have a few tests to help let us know when they break.

**Comment by iandees** [comment]
Generally tests are a good thing. But can we just the output of the spider to determine if it's broken? If a spider is modified then we'll run it for 1 minute here in Github and get notified for what the output looks like. On the weekly run we can see if it had any errors or if it produced any output places.

**Comment by Cj-Malone** [comment]
> On the weekly run we can see if it had any errors or if it produced any output places.

What is the weekly run/how could I see the output?

If it's like #3391 the log and output give an "AccessDenied" error, and https://data.alltheplaces.xyz/ give me a 403.

**Comment by iandees** [comment]
The auto-runs from Github Actions expire after 30 days, so those links will stop working after a while.

The weekly run is the data at https://alltheplaces.xyz. We recently made https://data.alltheplaces.xyz/runs/latest.json work to programmatically get the details about the most recent build and a corresponding https://data.alltheplaces.xyz/runs/history.json to get the known previous runs.

**Comment by Cj-Malone** [comment]
Back to tests, I don't think the current system about subtle errors?

So if the "link discovery" stage failed to cycle through pages and only got links from the first page, you'd have a some outputted data but drastically fewer. A test to check if certain URLs were "discovered" could help.

Or if the site is updated and an xpath starts to return bogus data, or good data prefixed/suffixed with bad data. You wouldn't know until someone reported it. Tests to say we expect this data to come from this URL could help.

**Comment by Cj-Malone** [comment]
The Specsavers spider is an example of a spider continuing to run without errors, but no longer returns any of the address data it originally did. It's moved from Microdata to Linked Data.

**Comment by iandees** [comment]
I think in examples like that I'd rather detect changes in the amount of data returned, flagging unexpected changes in row count or completed attribute count. I worry that tests will be hard to maintain alongside the spider itself.

**Comment by mjoe999** [comment]
I think the testing comes in two basic themes. To make writing spiders more simple / quicke / forwards compatible then we should attempt to push more boiler plate into common code.

I've started down the road with this pull request: https://github.com/alltheplaces/alltheplaces/pull/3648

Take the common LD JSON mark up as an example. The adherence of individual sites to a "standard" is fairly loose. Any library code starts to grow arms and legs to deal with various cases, think "beautiful soup".

We need a few static pages as test fixtures that illustrate the various vagaries of real world websites. As the number of spiders using shared code grows (a good thing?) then people become more fearful of changing that code. This is where tests come in. Nothing new here! I think there are scrapy mechanisms to help this but am not an expert.

The second major theme to the testing is dealing with changes to the brand sites which will always happen: big and small changes. This is where we need a process for comparing one spider run to a previous one. This mechanism is obviously useful to a developer editing an already existing spider also. The short GitHub actions history looks a useful starting point.

So once again I think I agree with Ian. Code and experience as ever will tell.

**Comment by mjoe999** [comment]
See my comments against @Cj-Malone generated issue: https://github.com/alltheplaces/alltheplaces/issues/3571

It has a comment of mine on how perhaps to detect significant changes in site **source** data between spider runs. Not for all sites but those for which we would get most data from ld+json or bespoke JSON, which in my experience is a very large number.

**Comment by Cj-Malone** [comment]
So, in spider tests are not wanted. Output tests are, [eg](https://www.alltheplaces.xyz/spiders.html). Core code can use `pytest`.
