### ISSUE TITLE
Post proccess addr_full

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#3579]
Would there be any desire to populate `addr:full` by joining the address tags after a spider has ran but not added one? This may get more complicated with addresses in other countries, but they aren't really supported with the current `addr:*` tags anyway.

I think in Scrapy terms this would be a "pipeline"?

**Comment by iandees** [comment]
I think generally I would prefer that we not artificially add data to the output that our customers could calculate themselves. But I don't hold that opinion very strongly.

One thing I notice is that the OSM convention of splitting "line 1" of an address into `addr:housenumber` and `addr:street` doesn't really fit the way data is available on place listing websites. I've long thought about adding an `addr:line1` or something to contain the housenumber and street information, as that's usually what's available without parsing. What do you think of that?

**Comment by Cj-Malone** [comment]
The idea of using OSM address tags is a nice goal, but it's unrealistic IMO.

I ended up using [this structure](https://schema.org/PostalAddress), prefixed with `addr:`. It makes producing the data so much easier, and if a consumer is just displaying the data (to a human) it's easier for them but if they need to parse it further to (like to `addr:housenumber` and `addr:street`) it'll be a headache for them.

**Comment by iandees** [comment]
What we have is pretty darn close to the schema.org model, with the exception of the housenumber/street separation. Maybe we could deprecate `addr:housenumber` and `addr:street` and replace it with `streetaddress` to represent the "first line" of the address?

**Comment by Cj-Malone** [comment]
That's what I'd do. If a spider has access to `addr:housenumber` or `addr:street` they could also be added via `extras`.

FYI I'm pretty sure some spiders are misusing `addr:full` as `addr:streetAddress` anyway.

**Comment by Cj-Malone** [comment]
> Maybe we could deprecate `addr:housenumber` and `addr:street`

I don't think deprecating them is the best, if a spider can collect them, they are great to have. However most of the time they aren't split in source data, that's when we should encourage `street_address`.

**Comment by Cj-Malone** [comment]
Since `street_address` has been added and automatically adding `addr_full` isn't wanted this can be closed.
