### ISSUE TITLE
Include Name Suggestion Index IDs in output?

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#3585]
Should All The Places start including NSI ids in the output? or maybe including the NSI tags directly?

This would start including OSM "top level" tags like 'shop=*' or 'amenity=*', along with extra metadata.

_Originally posted by @Cj-Malone in https://github.com/alltheplaces/alltheplaces/issues/1343#issuecomment-1104434637_

**Comment by iandees** [comment]
I don't really want to adopt OSM's multiple-tag system for specifying categories (amenity=restaurant, cuisine=burger means "burger restaurant").

I do see value in including category information for spider output, though. I don't know that there's a good "general purpose" set of POI categories out there, so I'm open to suggestions there!

**Comment by iandees** [comment]
Another requirement for categorization would be to make it relatively easy for spider authors to find acceptable category options. Ideally the categories we pick would have an easy list to search and good documentation for what each means (for our spider authors and data consumers).

**Comment by iandees** [comment]
Name Suggestion Index IDs would be good to add, but I don't know that they would help non-OSM data consumers. That's probably OK, because those data consumers could look at the data in the NSI to help map to their internal categorization scheme.

**Comment by Cj-Malone** [comment]
Hmm, I'd stick with OSM over new categories as they are a (relatively) known concept, well discussed already and reasonably [documented](https://wiki.openstreetmap.org/wiki/Shops) (and that links to [shop=*](https://wiki.openstreetmap.org/wiki/Key:shop) and [amenity=*](https://wiki.openstreetmap.org/wiki/Key:amenity)).

If you decided against OSM tags, [schema.org types](https://schema.org/LocalBusiness#subtypes) are a thing. I don't know how well they cover things though, I'm an OSM person.

(I know I just recommended moving away from OSM address tags in #3579. The irony isn't lost on me.)

**Comment by Cj-Malone** [comment]
For cuisine, I don't think `amenity=restaurant` and `cuisine=burger` is a massive issue. But I do dislike how OSM treats it as an array, eg `cuisine=burger;kebab`. I moved towards cuisine as a "namespace" in [KAFF Places](https://gitlab.com/KAFF/places), eg `cuisine:burger=yes` + `cuisine:kebab=yes` (backwards compatibility is really easy too).

**Comment by jleedev** [comment]
Any item that includes a `brand:wikidata` can be looked up to find the NSI index with the canonical amenity tags if needed. Only issue might be if a brand points to multiple NSI items. I don't see much value in making sure that e.g. the most up-to-date `cuisine=*` value is used in this particular dataset.

**Comment by iandees** [comment]
@thekuiperbelt @wessport do y'all have any thoughts on categories? Do you apply categorization when you consume the data?

**Comment by Cj-Malone** [comment]
> Any item that includes a `brand:wikidata` can be looked up to find the NSI index with the canonical amenity tags if needed. Only issue might be if a brand points to multiple NSI items.

Yeah, 1 `brand:wikidata` can be used on multiple NSI items. Including the NSI id here would make that a concentrate match.

Another issue is some data in here looks to be including warehouses/delivery infrastructure. I think it should, but we should also (try to) signal that to data consumers, eg by removing a top level tag, or having a different one.

> I don't see much value in making sure that e.g. the most up-to-date `cuisine=*` value is used in this particular dataset.

I think it depends on how much post processing we want people to do. I don't have an answer to that, previously I've argued that this type of data should just be a conversion from upstream. But the more I use it, the more I see that needs post processing to be useful. Upstream data sucks.

**Comment by bhousel** [comment]
> Any item that includes a `brand:wikidata` can be looked up to find the NSI index with the canonical amenity tags if needed. Only issue might be if a brand points to multiple NSI items

Yes, this gets a little complicated, but it is something something that NSI code can handle as long as each location comes with a reasonable name that NSI can match.  For example NSI tracks separately formats like "Gap", "Baby Gap", "Kids Gap", "Gap Factory", but they all have `"brand:wikidata": "Q420822"`.  

I know alltheplaces has a [Gap scraper](https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/gap.py) - I guess I'd have to look more closely at what it actually generates.

Maybe the best option is to process alltheplaces output through NSI's matcher to generate a different dataset that's more OSM-like and can churn more - like if people decide to rework the `cuisine` tags. 

This is interesting too because for a while I've also been thinking about moving NSI away from using OSM tags for categorization, [for similar reasons](https://github.com/osmlab/name-suggestion-index/issues/4765) (it's complicated when it takes multiple tags to define _what a thing is_ ).

**Comment by iandees** [comment]
> I know alltheplaces has a [Gap scraper](https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/gap.py) - I guess I'd have to look more closely at what it actually generates.

I don't know if this happens now, but it should be up to the spider to output correct brand and category information when the spider is working data that could span different brands/categories.

There's a feature in our spiders that lets you specify the default tag for all features, but you can also add an if-block that would do something like "if placeIsGapKids(): brand = kidsGapWikidata", etc.

**Comment by wessport** [comment]
Hey a bit late to the conversation, but yes, to answer your question @iandees we apply a basic categorization. It’s very nascent at the moment so we’d likely benefit from an upstream top-level categorization. Agree that OSM's multiple-tag system could be tricky (but opened minded).

> Another issue is some data in here looks to be including warehouses/delivery infrastructure. I think it should, but we should also (try to) signal that to data consumers

Agreed, this would be really helpful in particular.

**Comment by jleedev** [comment]
Here's the values seen on Gap, FWIW:

1 "Gap, GapKids, GapBody, Gap Factory Store"
1 "Gap, babyGap, GapKids, GapMaternity, GapBody"
1 "Gap"
3 "babyGap"
4 "GapKids"
4 "Gap, GapBody"
6 "babyGap, GapKids"
9 "Gap, GapKids"
28 "Gap, babyGap, GapKids"
32 "Gap, GapKids, GapBody"
132 "Gap, babyGap, GapKids, GapBody"
214 "Gap Factory Store"

**Comment by Cj-Malone** [comment]
Should all those Gap stores share a Wikidata id? In the UK there is [Tesco](https://www.wikidata.org/wiki/Q487494), they operate different types of store like [Tesco Express](https://www.wikidata.org/wiki/Q98456772) and [Tesco Extra](https://www.wikidata.org/wiki/Q25172225) but they have different Wikidata ids.

We might need someone who knows more about Wikidata to answer this, but if they should have different ids? If each fascia/shop type should have different ids maybe we don't need to do shop type at all.

**Comment by iandees** [comment]
I think I like the idea of adding NSI IDs. It's (1) a "friendly" project that we can suggest additions to fairly easily (and those additions would also improve OSM) and (2) it allows us to set up connections to brands, which connect to Wikidata and OSM tags if people want to use the data to contribute to OSM.

We could also include a separate category identifier to make the lives of data consumers easier. I imagine NSI would do this, too, at some point. I don't really feel like maintaining our own category system, so maybe we could use Foursquare/Factual's list [here](https://github.com/Factual/places/blob/master/categories/utils/Foursquare_to_NAICS_and_SIC.tsv)?

**Comment by nvkelso** [comment]
There's also Tilezen's kind system for POIs, which is more oriented around what they would look like on a map (versus detailed breakdown of different types of shops):

- https://github.com/tilezen/vector-datasource/blob/master/docs/layers.md#poi-kind-values

**Comment by bhousel** [comment]
@nvkelso said:
> There's also Tilezen's kind system for POIs, which is more oriented around what they would look like on a map (versus detailed breakdown of different types of shops):

Thanks for the link - I hadn't seen this before and these docs are _really_ well done. ❤️ 
I've been thinking about the problem of identifying things a lot lately (both for RapiD and NSI) and it's very helpful to see how others have approached it!

@iandees said:
> think I like the idea of adding NSI IDs. It's (1) a "friendly" project that we can suggest additions to fairly easily (and those additions would also improve OSM) and (2) it allows us to set up connections to brands, which connect to Wikidata and OSM tags if people want to use the data to contribute to OSM.

A concern would be that the NSI IDs aren't quite as stable as I had hoped for them to be.  

They are necessarily based on the location of the brand (e.g so Target USA and Target AUS have different NSI IDs) and the OSM tags (so Target department store and Target pharmacy have different NSI IDs).  So when NSI contributors change any of these things, the item will get a new NSI ID.  We run a script that syncs them all to WIkidata.org , but these IDs change more than I'd like.

A while ago I thought NSI might link to your scraper IDs - but either way I think we have a many-to-many problem.  My gut says we need a new project to merge them together. 😆

**Comment by mjoe999** [comment]
I think both NSI and ATP are jolly good projects. NSI and ATP share something in common in that they only make sense for brands / chains of a certain size.

I wrote a good number of scrapy brand (mainly UK) spiders before recently coming across ATP and NSI (in that order). I'm here as I would like to contribute. Previously I got to the point of having a brand enumeration that my spiders would use for POI metadata e.g. todays example brand:

CLAIRES = "Claire's", 'Q2974996', CAT.SHOP_JEWELRY, 'claires', 'https://www.claires.com'

where all is obvious apart from 'CAT.SHOP_JEWELRY' which is another POI category scheme (http://slipo.eu/) and 'claires' which is the Facebook ID used to generate a brand logo link. I always knew I could automate most of the above from wikidata but somehow never got around to doing it.

I'd like to start to contribute some of my code to ATP if you think it is of merit. I reference a pull request (my first ever!) that I have just generated:

https://github.com/alltheplaces/alltheplaces/pull/3648

I am keeping the concept of a brand enumeration, but for now more constrained:

CLAIRES = "Claire's", 'Q2974996'

This allows brands to be referenced in code (i.e. Brand.CLAIRES). The language and my IDE gives me that extra support above typing in brittle Q-codes. The enumerated type allows other simple maps to be built from it more readily. The enumeration can be more simply sanity checked, by code, against NSI and / or wikidata.

I would like to see the option of ATP spiders being able to weave in data from NSI / wikidata but that is a bridge to be crossed a little later. It is surely the case that we can overthink the complexity associated with this. Most brands will be simple and not exhibit the "Gap" complexity above. These cases should be made simple and the more complex cases simply generate more complex spiders, I guess I am agreeing with Ian's comment above.

**Comment by jleedev** [comment]
Unclear what's the exact benefit of writing

```python
# claires.py
brand_wikidata = "Q2974996"
```

vs.

```python
# brands.py
CLAIRES = "Q2974996"
# claires.py
from brands import CLAIRES
```

Since in both cases it's a magic number that's used precisely once, with the only context that it's expected to be the value associated with the human readable name that's right there on the same line.

**Comment by mjoe999** [comment]
I think the difference is that it is an enumerated type vs. a magic number and so gets a bit more support from knowledgable clients such as an IDE or event GitHub:

![image](https://user-images.githubusercontent.com/1497536/169109036-feb26251-6380-4ced-bd14-b152577fc2e5.png)

I don't know what it is like in the USA these days but in the UK our big supermarkets start to have quite a few branded outlets embedded within so you see (in my spiders at least) lots of calls like located_in(item, Brand.SAINSBURYS) etc where the relationship is explicit in the output. So more than one usage. I have not suggested that step yet for the core data structure. Too far, too fast?! Such relationships are important both for location improvement and also visualisation. The "enclosing" entity being the logical item to display at lower zoom if space is constrained.

This goes beyond supermarkets of course but it is a clear example.

The enumeration is also a good place to see "well what have you got?". The single directory structure for spiders will get more unwieldy as more get added. The enumeration would be large ... but not impossibly so.

**Comment by Cj-Malone** [comment]
So we now add `nsi_id` automatically to most spiders, and the coverage will increase as get better at matching in `ApplyNSICategoriesPipeline`. We also apply the NSI tags (OSM categories) from them.

I can't speak for @iandees, but I think we'd be open to adding a pipeline to convert the OSM tags into another category system if a data consumer really wanted it. But for now, we've settled on OSM categories.

**Comment by iandees** [comment]
Yep, that's a good summary of where we're at.
