### ISSUE TITLE
Mail Boxes Etc.

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#3677]
https://www.mbe.co.uk/huddersfield

**Comment by davidhicks** [comment]
`https://www.mbe.co.uk/Services/StoreLocationWebService.asmx/ShowAllStores` returns all locations.

Parsed with:
```for location in json.loads(response.json()["d"]["StoreLocationResults"]):```

**Comment by davidhicks** [comment]
Fixed in #5508
