### ISSUE TITLE
Burger Fi

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#3681]
`burger_fi` is currently broken. It API has [moved](https://api.dineengine.io/burgerfi/custom/dineengine/vendor/olo/restaurants), but Cloudflare is blocking us. Possibly related to https://github.com/alltheplaces/alltheplaces/pull/3632#issuecomment-1138304090.

**Comment by Cj-Malone** [comment]
`freddys` is the exact same. Cloudflare is now blocking the spider, there is an [API](https://nomnom-prod-api.freddys.com/restaurants/), but that's also blocked by Cloudflare.

**Comment by iandees** [comment]
Maybe if we ask really nicely...

**Comment by Cj-Malone** [comment]
Who? Cloudflare or the brands? For the brands, I'm pessimistic that we could contact the right people. For Cloudflare, they are there to block bots. We are a bot... I think we're a good bot, but we're still a bot.

**Comment by iandees** [comment]
I was thinking either, but was mostly joking. We can try using Cloudflare's "friendly bots" form mentioned [here](https://blog.cloudflare.com/friendly-bots/)?

**Comment by Cj-Malone** [comment]
That's interesting, I'd never heard of that. Yeah I think we should try it.


Oh, and these aren't directly related to #3632, these get a captcha, that gets no response when using OpenSSL for TLS. But it's still Cloudflare.

**Comment by davidhicks** [comment]
Fixed previously with https://github.com/alltheplaces/alltheplaces/pull/3947
