### ISSUE TITLE
Cath Kidston

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#3717]
https://www.cathkidston.com/en-gb/storefinder/
https://www.cathkidston.com/on/demandware.store/Sites-ckidst-uk-Site/en_GB/Stores-FindStores?pagename=storeLocator&ajax=true
https://www.cathkidston.com/on/demandware.store/Sites-ckidst-uk-Site/en_GB/Stores-StoreDetails?storeID=105&current=false&countryCode=GB&searchQuery=

**Comment by davidhicks** [comment]
The last Cath Kidston store closed by 30 June 2023 according to https://www.thesun.co.uk/money/22713126/iconic-brand-cath-kidson-closing-stores/ and Next (`next` spider) acquired the brand, but none of the old physical stores (of which only apparently 4 were remaining at time of acquisition).
