### ISSUE TITLE
When does spieder.html update?

### ISSUE THREAD

**Issue by Romeo-PHILLIPS** [alltheplaces/alltheplaces#3726]
Hi, when does https://www.alltheplaces.xyz/spiders.html update? I'm using this to figure out Spiders that are broken (doesn't return anything)

**Comment by iandees** [comment]
It updates once a week when the global run finishes. This usually happens on Saturday, I think.

**Comment by Romeo-PHILLIPS** [comment]
Alright thanks, then I have another question. Some spiders say they have 0 results, for example the last one I have in mind is **Argos**, but when running it locally it generates 1097 results.  Any ideas what that could be?

**Comment by Romeo-PHILLIPS** [comment]
I thought that too, I went on the website with a US VPN and it still ran..

**Comment by Romeo-PHILLIPS** [comment]
Another one is Tesco, spiders.html says 0 generated, local run generates 2796.

**Comment by jleedev** [comment]
Looks like history.json failed to update this week.

**Comment by iandees** [comment]
> Looks like history.json failed to update this week.

It was updated, but the CDN had it cached with the old version. I manually purged it so it should be good now.
