### ISSUE TITLE
Car charging stations

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#3770]
Are we interesting in collecting data on charging stations? We collect petrol stations, and I don't think it's that different, except there'll presumably me more charging stations.

I just came across [char.gy](https://char.gy/), it would be real easy to add via the [API](https://char.gy/charge_points.geojson?bounds=48,-10,60.716907,2) or a generic [Sitemap](https://char.gy/sitemap.xml)/Linkedata spider.

**Comment by iandees** [comment]
Yup, charging locations are ok. I would prefer that we pull from 1st party sources rather than aggregators, so as long as char.gy runs their charging network I'm ok with including them. I think we have Tesla, for example.

**Comment by Cj-Malone** [comment]
How is the DOE dataset? The UK has, National Chargepoint Registry https://www.gov.uk/guidance/find-and-use-data-on-public-electric-vehicle-chargepoints it has the usual 3rd data errors. Some providers are slow, it has a bunch of old (or not yet installed?) ones, broken ones, bad cords etc.

Char.gy is first party. I'll write a spider at some point.

**Comment by jleedev** [comment]
The DOE dataset is definitely an aggregation of 3rd party coords, but they seem reasonable at first glance.

|count|ev_network|
|-|-|
|1|"AddÉnergie Technologies"|
|3|"Sun Country Highway"|
|4|"EVRANGE"|
|6|"ZEFNET"|
|11|"UNIVERSAL"|
|14|"FPLEV"|
|16|"RIVIAN_ADVENTURE"|
|31|"Electrify Canada"|
|33|"EVGATEWAY"|
|48|"AMPUP"|
|50|"RIVIAN_WAYPOINTS"|
|55|"PETROCAN"|
|57|"EVCS"|
|61|"Webasto"|
|62|"eCharge Network"|
|70|"IVY"|
|78|"POWERFLEX"|
|79|"BCHYDRO"|
|86|"CHARGELAB"|
|117|"FCN"|
|132|"SWTCH"|
|167|"OpConnect"|
|188|"LIVINGSTON"|
|808|"EV Connect"|
|815|"Electrify America"|
|917|"eVgo Network"|
|1122|"Greenlots"|
|1251|"Volta"|
|1293|"Blink Network"|
|1589|"Tesla"|
|1961|"FLO"|
|1980|"Circuit électrique"|
|2178|"SemaCharge Network"|
|4906|"Tesla Destination"|
|6696|"Non-Networked"|
|7932|null|
|29686|"ChargePoint Network"|
