### ISSUE TITLE
Enforce 2 digit country code

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#3795]
As noted in https://github.com/alltheplaces/alltheplaces/pull/3791#pullrequestreview-1071740124, the spiders are currently inconstant in the country output.

I think we all agree that we should follow [OSM](https://wiki.openstreetmap.org/wiki/Key:addr:country), and use "ISO 3166-1 alpha-2".

I can envision a wrapper function, like `ensure_country_code("United Kingdom")` that returns "GB". I'm leaning towards this being in spider code (and shared parsers like the ld one) not a pipeline.

**Comment by mjoe999** [comment]
So I am cooking something up in my forked repo, initial commit:
https://github.com/mjoe999/alltheplaces/commit/ec663801d3a9b03b6536ed4784ed06c3ae51cef3
... just a heads-up in case anyone is doing same.

@Cj-Malone : I see you have ExtractGBPostcodePipeline .... note that geonames country structure has an embedded postcode regex which if generally correct could prove helpful.

@iandees : geonames is a good dependency to pull in as it gives a ton of city names per territory with lat/lng and population. I believe that this is something you have been missing. For some spiders you will want to do the existing centroid thing but then also call with high population cities and a finer lat/lng grid .... higher population means higher desnity. Think Big Macs.

**Comment by Cj-Malone** [comment]
> I see you have ExtractGBPostcodePipeline .... note that geonames country structure has an embedded postcode regex which if generally correct could prove helpful.

I love the idea of expanding the pipeline for more countries. I'm no regex wizard, but I'm not sure `postalcoderegex` from geonames is right for GB, and if it's wrong here, is it wrong for other countries too?

**Comment by Cj-Malone** [comment]
Also in your `to_iso_alpha2_country_code` I'd move `UNHANDLED_COUNTRY_MAPPINGS` a lot higher up so any of our overrides happen first.
