### ISSUE TITLE
The Library

### ISSUE THREAD

**Issue by hampelm** [alltheplaces/alltheplaces#38]
https://www.worldcat.org/libraries

**Comment by iandees** [comment]
Removing the assignee on this so others can give it a shot. If you're still working on this please push up your work and open a pull request so we can help work through any problems.

**Comment by bealbrown** [comment]
> Results for "/":
> 135193 total results matching your search - only the first set of results are returned below. Please narrow your search criteria and try again.

**Comment by bealbrown** [comment]
Site says it's "powered by WorldCat Registry", which led me here: https://www.worldcat.org/webservices/registry/Institutions

This place appears not to have a max result limit on the ajax, so could probably be mostly covered by searching A-Z and removing duplicates.

**Comment by davidhicks** [comment]
Paginated API requests to `curl 'https://www.worldcat.org/api/library?lat=-37.8159&lon=144.9669%20%20%20%20%20%20%20%20&distance=999999&unit=K&offset=1&limit=50' -H 'Referer: https://www.worldcat.org/libraries'` seems to include all location data for libraries around the world, in JSON format.
