### ISSUE TITLE
boots.py spider doesn't correctly pick up all opticians

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#3801]
The current test in boots.py to switch the brand tags for opticians is `properties["name"].startswith("Opticians - ")`:
https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/boots.py#L73

But this is not general enough to catch all of them. The displayed name of some opticians branches only start with "Opticians " or "Opticians-". For example https://www.boots.com/stores/3730-tewkesbury-high-street-opticians-gl20-5jz and https://www.boots.com/stores/3947-camden-high-street-opticians-nw1-0lu

I think you could safely change the test to `properties["name"].startswith("Opticians")` but the code a few lines below to strip out the "Opticians" prefix would need to be more complicated.

**Comment by Cj-Malone** [comment]
`.replace("Opticians", "").strip("- ")` should drop the prefix.
