### ISSUE TITLE
Only about half of stores returned by costacoffee_gb spider

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#3805]
https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/costacoffee_gb.py

I think the Costa Coffee GB spider is only returning around half of the Costa stores. (My attempt to match the non-express stores from AllThePlaces with OSM data has found only about half of the ~1800 OSM objects with brand:wikidata=Q608845 are matched. See https://osm.mathmos.net/chains/Q608845/ )

For example, the Diss Mere Street store at IP22 4AD is not in the AllThePlaces output: store https://www.costa.co.uk/locations/store-locator/map?latitude=52.3749&longitude=1.1089399999999898&open=1

From the comment at line 17 of costacoffee_gb.py:
`# TODO: Can't figure out how to return more than 5 miles`
it seems you may already be aware of this, but I couldn't see an issue about it, so I thought it best to create one.

**Comment by Cj-Malone** [comment]
We can do `maxrec=0` instead of `maxrec=600` to remove the result limit, but that doesn't help us in this case. If we can't get more than 5 miles out of this API, we need to do more requests, at least in the more populated areas.

@costa-coffee help us out on this? We need an efficient API for all the stores, and ideally the vending machines.

**Comment by mjoe999** [comment]
This spider like many similar (Big Mac anyone?) would benefit from adding a geonames dependency to the project. This has cities by population by territory. These brands in general put their outlets where there are people. ALP sits at about 6,500, I sit at about 8,700 with a less scatter gun geographic query approach. Horse for courses - in many cases the scatter gun is just what you want. In other cases scatter gun with an additional layer of finer grain scatter gun in areas of large population (thanks again geonames).

**Comment by Cj-Malone** [comment]
> @costa-coffee help us out on this? We need an efficient API for all the stores, and ideally the vending machines.

@atmos87 ?

**Comment by mjoe999** [comment]
I've added geonames "support" as part of https://githhttps://github.com/alltheplaces/alltheplaces/pull/3831ub.com/alltheplaces/alltheplaces/pull/3831

@rjw62 : if the above makes it into the weekly run this week you will have need McDonald's GB output. I believe the current mcdonals UK output is stunted in a similar manner to Costa here.
