### ISSUE TITLE
Hertz Car Hire 

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#3899]
Micro data, or [API](https://api.hertz.com/rest/geography/country) [2](https://api.hertz.com/rest/location/country/AL/city/Kukes)

**Comment by davidhicks** [comment]
The `hasStates` attribute in `https://api.hertz.com/rest/geography/country` hints at whether a single API call is needed per country, or whether an API call is required for each state of a country. However, only `US`, `CA` and `AU` have `hasStates=True`, and out of these, only `US` requires a state-by-state search per the error message that appears for `https://api.hertz.com/rest/location/country/US/`. The `Please specify a state using the /location/country/{country}/state/{state} web service call.` error message provides incorrect advice though--the stated state-by-state URL returns a HTTP 404 error for `https://api.hertz.com/rest/location/country/US/state/California` and https://api.hertz.com/rest/location/country/US/state/CA` and `https://api.hertz.com/rest/location/country/US/state/`.

Other than finding out how to search for US locations state-by-state, this looks like a fairly simple spider to implement.
