### ISSUE TITLE
Coopland & Son

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#3914]
https://cooplands-bakery.co.uk/locations/cafes
https://cooplands-bakery.co.uk/locations

**Comment by davidhicks** [comment]
URLs have changed. Now uses WPStoreLocator, example: `https://cooplands-bakery.co.uk/wp-admin/admin-ajax.php?action=store_search&lat=54.2359239&lng=-0.4109243&max_results=25&search_radius=50&autoload=1`

WPStoreLocator has been configured with a maximum of 50 results returned, so a radius geographic search is needed across GB with a density ensuring 49 or less results are returned per API call.
