### ISSUE TITLE
Evaluating extruct

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#3926]
Has anybody looked at [extruct](https://github.com/scrapinghub/extruct)?

**Comment by mjoe999** [comment]
No. Thought I'd searched fairly well also! More than interesting I would say .... after all .... who likes writing code? :-)

**Comment by Cj-Malone** [comment]
So IMO, this is great, but because we've already got the microdata -> linkeddata this doesn't add much to atp.
