### ISSUE TITLE
Jelly Belly

### ISSUE THREAD

**Issue by stepps00** [alltheplaces/alltheplaces#399]
https://www.jellybelly.com/store-locator

**Comment by vlad555** [comment]
Hello
I can't see possibility to get all stores list except to pass their search system with all USA ZIPs
I know you didn't like this solution last time, so I want to ask you how to do better
Thank you

**Comment by AnthoneyKalasho** [comment]
This isn't every store but this should be a good start https://hosted.where2getit.com/jellybelly/ajax?&xml_request=%3Crequest%3E%3Cappkey%3E1E7D25FE-5D91-11E1-9AB6-6124DEB2B31E%3C%2Fappkey%3E%3Cformdata+id%3D%22locatorsearch%22%3E%3Cdataview%3Estore_default%3C%2Fdataview%3E%3Climit%3E1500%3C%2Flimit%3E%3Cgeolocs%3E%3Cgeoloc%3E%3Caddressline%3ESan+Diego+CA+92115%3C%2Faddressline%3E%3Clongitude%3E-117.07352409999999%3C%2Flongitude%3E%3Clatitude%3E32.7612759%3C%2Flatitude%3E%3Ccountry%3EUS%3C%2Fcountry%3E%3C%2Fgeoloc%3E%3C%2Fgeolocs%3E%3Csearchradius%3E1000%3C%2Fsearchradius%3E%3Cradiusuom%3Emile%3C%2Fradiusuom%3E%3Cwhere%3E%3Cor%3E%3Cjellybelly%3E%3Cilike%3ETRUE%3C%2Filike%3E%3C%2Fjellybelly%3E%3Cbeanboozled%3E%3Cilike%3ETRUE%3C%2Filike%3E%3C%2Fbeanboozled%3E%3Corganics%3E%3Cilike%3ETRUE%3C%2Filike%3E%3C%2Forganics%3E%3Cconfections%3E%3Cilike%3ETRUE%3C%2Filike%3E%3C%2Fconfections%3E%3Csunkist%3E%3Cilike%3ETRUE%3C%2Filike%3E%3C%2Fsunkist%3E%3Cdips%3E%3Cilike%3E%3C%2Filike%3E%3C%2Fdips%3E%3Csportbeans%3E%3Cilike%3ETRUE%3C%2Filike%3E%3C%2Fsportbeans%3E%3Csugarfree%3E%3Cilike%3ETRUE%3C%2Filike%3E%3C%2Fsugarfree%3E%3Charrypotter%3E%3Cilike%3ETRUE%3C%2Filike%3E%3C%2Fharrypotter%3E%3Cbeanboozledminion%3E%3Cilike%3ETRUE%3C%2Filike%3E%3C%2Fbeanboozledminion%3E%3Cmixedemotions%3E%3Cilike%3ETRUE%3C%2Filike%3E%3C%2Fmixedemotions%3E%3C%2For%3E%3C%2Fwhere%3E%3C%2Fformdata%3E%3C%2Frequest%3E

**Comment by vlad555** [comment]
Thank you for your advice, this request is first I saw on site, but:
1. your request contains ZIP-code(or lat/lon combination). so, my question is still unanswered. 
these shops a huge amount and radius is about just 200 miles to get 1000shops (site limit per request)
So it's to ways: covering USA 200-miles circles or checking by all possible ZIP
As far as I know these solutions are not in favor. So I asked for permission 
2. This request to third-side part. Last time I got negative answer when I asked to use other service than main site (it was google location for getting lat/lon)

**Comment by iandees** [comment]
For now, let's skip over the ones that only expose lat/lon/radius searches like this.

**Comment by vlad555** [comment]
Ok, unsubscribing 
I 'm wondering how you are going to solve this.
Thank you

**Comment by SelfnessAid** [comment]
not sure why this issue labeled as work stopped.
it seems we can crawling this website with some static data.

**Comment by vlad555** [comment]
I've labeled it as Ian said the sites where we need search stories by sending lat/lon pair and small radius we passing now.
If you have better solution with this site you can take it.
I unassigned myself.
Also I have some more shop networks with same logic

**Comment by davidhicks** [comment]
I'm not sure this brand has any own-brand stores? The store locator appears to just return stockists (e.g. relaying third-party location information from other brands).

**Comment by CloCkWeRX** [comment]
https://www.jellybellyinternational.com/storelocator-english

**Comment by CloCkWeRX** [comment]
Recommend close as not scrapable.

**Comment by davidhicks** [comment]
No branded retail outlets exist
