### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#4024]
I've never done one before, but it [looks](https://hacktoberfest.com/participation/#maintainers) like we need to:

- [x] Add `hacktoberfest` tag to repo
- [x] Add `hacktoberfest` tag to issues (I'll probably start this tomorrow)
- [x] Improve/update docs, we will also need a `CONTRIBUTING.md`
- [x] Add a code of conduct, I don't know if this is a requirement, but probably good to have anyway

**Comment by Cj-Malone** [comment]
I've added some tags to issues with "good first issue", we can do more later.

**Comment by Cj-Malone** [comment]
@iandees Opinion on a Code of Conduct? I don't think it's necessary at this stage TBH.

**Comment by iandees** [comment]
A Code of Conduct is a great idea. I'll look for one and add it in.

**Comment by kumanoit** [comment]
@iandees @Cj-Malone 
Pardon me for asking this here. 
Do issues with the label `hacktoberfest` only counts in hacktoberfest-2022 or do all issues qualify?

**Comment by iandees** [comment]
> Do issues with the label `hacktoberfest` only counts in hacktoberfest-2022 or do all issues qualify?

All quality pull requests qualify. Please feel free to fix an existing broken spider or add a new one.

**Comment by Cj-Malone** [comment]
If I missed any `hacktoberfest-accepted` tags let me know, but I don't _think_ are required anymore.

Thanks to everyone who participated, @boomerwv1 @cmecklenborg @rubyruins @Romeo-PHILLIPS @kumanoit @tonyskapunk @nuxper @Dilshan-H @stephinson (and anyone else I missed), I hope you continue to contribute, or we see you next year. :)
