### ISSUE TITLE
StructuredDataSpider's wanted_types duplicates items

### ISSUE THREAD

**Issue by jleedev** [alltheplaces/alltheplaces#4062]
If a JSON-LD contains e.g. `"@type":["HomeGoodsStore","FurnitureStore"]`, then StructuredDataSpider should only consider the item once when given `wanted_types = ["HomeGoodsStore", "FurnitureStore"]`.

(If there's really some reason to handle the item once for each of the types, LinkedDataParser can be invoked directly; if the site contains two distinct items, e.g. "Store" and "Pharmacy", then those are expressed as separate items, not two types on the same item.)

**Comment by Cj-Malone** [comment]
The idea behind it was to be able to get different objects, so "or", I'm open to changes to make it possible to more specifically get items with multiple types "and".

Maybe the end result will be `wanted_types = [["HomeGoodsStore", "FurnitureStore"], "OtherTypeThatWeAlsoWant"]`. I'll think more about this after work.

**Comment by Cj-Malone** [comment]
I also want to add more callbacks, at lease one with the ld before it's parsed. Probably also extend the current one with the raw ld. I'll start doing this tomorrow.
