### ISSUE TITLE
Marks and Spencer

### ISSUE THREAD

**Issue by zerebubuth** [alltheplaces/alltheplaces#407]
Marks and Spencer is a chain of department stores (with some "simply food" grocery-only stores) in the UK.

https://www.marksandspencer.com/s/store-listing

**Comment by josh0203e** [comment]
I can't find out the geo of each store

**Comment by sean-boothby** [comment]
@iandees Marks and Spencer leaves the store hours in military time. Prefer to convert it?

**Comment by iandees** [comment]
The OSM opening hours use 24-hour time, so no need to convert it.
