### ISSUE TITLE
Tesco

### ISSUE THREAD

**Issue by zerebubuth** [alltheplaces/alltheplaces#409]
Tesco is a supermarket chain in the UK.

https://www.tesco.com/store-locator/uk/

**Comment by AustenHolmberg** [comment]
@zerebubuth I believe this issue is a duplicate and should be removed. #349 is Tesco, which I'm currently working on.

**Comment by iandees** [comment]
@AustenHolmberg would it help to keep this one around for Tesco UK? Or will you be able to get all countries with one spider?

**Comment by AustenHolmberg** [comment]
It's just that I've already started working on gathering the UK locations with my spider. I can try to get all the countries with one spider, yeah.

**Comment by josh0203e** [comment]
Oh sorry for my delay . I have done tesco uk,  but no worries. I will remove

**Comment by AustenHolmberg** [comment]
@josh0203e Well, if you're finished, then let's just use yours. I'm not done with mine

**Comment by iandees** [comment]
Thanks @josh0203e and @AustenHolmberg. Apologies for the dupe issue.
