### ISSUE TITLE
Pizza Hut Spider returns some closed outlets

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#4223]
It looks like the GB Pizza Hut spider "pizza_hut_gb" is returning a number of outlets that have closed. These are evident when the website either redirects to https://www.pizzahut.co.uk/restaurants/find or https://www.pizzahut.co.uk/restaurants/error/filenotfound . It seems that Pizza Hut are leaving up the https://www.pizzahut.co.uk/huts/uk-2/... web page after the outlet has closed, presumably for SEO reasons. These pages still contain the old location and web address, which the spider then picks up.

Examples include https://www.pizzahut.co.uk/huts/uk-2/437-ayr/ and https://www.pizzahut.co.uk/huts/uk-2/390-barrow/ .

I think these closed outlets can probably be removed from the dataset returned by looking at the openingHours LD field on the /huts/uk-2/ pages. The closed outlets seem to always have "openingHours":[]. The open branches have some sensible content there.

**Comment by Cj-Malone** [comment]
Yep, that all looks right. I checked 2022-11-12-13-31-47 and there are 23 items without opening hours, and they all redirect like you said. I'll do a PR now.

**Comment by Cj-Malone** [comment]
Thank you
