### ISSUE TITLE
Zip is not installed on image that runs weekly build

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#4258]
In #4255, it was pointed out that the history.json and latest.json files on data.alltheplaces.xyz were blanked out.

It failed because #4239 started calling "zip" instead of "tar", and "zip" isn't installed on the image we use for the build.

- [x] Update the weekly CI script to install zip and check the return code of the zip command to exit gracefully instead of continuing on. (#4259)
- [x] Enable S3 versioning on the bucket so it's easier to recover from this in the future
- [x] Copy the runs from the old S3 bucket in my account to the new S3 bucket in the new account
- [x] Rebuild the history.json and latest.json files based on the current contents of the S3 bucket (#4260)

**Comment by Romeo-PHILLIPS** [comment]
Does the process have to re-run for the pages to update?

**Comment by iandees** [comment]
No, the history.json and latest.json files need to be regenerated, which requires some custom code to search through the S3 bucket and recover as much of the information as possible. I'm writing that code now.

**Comment by iandees** [comment]
Ok, this should be complete. I rebuilt the history.json and latest.json using the script above and copied the output to the S3 bucket. I also manually built the output.zip and logs.zip and sent those to the S3 bucket. I also updated the info_embed.html file used to show the latest download link on alltheplaces.xyz and invalidated the CDN for those files, too.

**Comment by jleedev** [comment]
https://www.alltheplaces.xyz/builds.html is showing "NaN" spider and feature counts.

**Comment by iandees** [comment]
Yep, that's because I didn't go through the trouble of summing up the spider and feature counts when rebuilding the history.json. Is that information useful for you?

**Comment by jleedev** [comment]
Not specifically, just wanted to verify that nothing was broken further.

**Comment by brawer** [comment]
@iandees, I’m very sorry for all the trouble that my change has caused to you! I had tested the zip command before sending you my PR, but only locally on my machine, which is why I hadn’t run into this particular problem.

**Comment by iandees** [comment]
No problem! I thought `zip` was installed by default.

**Comment by Cj-Malone** [comment]
I think this is all sorted now? Good work @iandees
