### ISSUE TITLE
Update spider-pr to use actions/cache@v3

### ISSUE THREAD

**Issue by brawer** [alltheplaces/alltheplaces#4269]
Running the [spider-pr workflow](https://github.com/alltheplaces/alltheplaces/blob/master/.github/workflows/spider-pr.yaml) currently generates [two warnings](https://github.com/alltheplaces/alltheplaces/actions/runs/3591042651) that seem to be caused by [GitHub action cache](https://github.com/actions/cache). Perhaps upgrading from `actions/cache@v2` to `actions/cache@v3` might fix these warnings?

**Comment by iandees** [comment]
Thanks for submitting the PR. I merged it and will watch the next couple builds to see if it helps with caching.

**Comment by CloCkWeRX** [comment]
Closable?
