### ISSUE TITLE
lloyds_bank_gb spider doesn't capture addresses

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#4284]
I'm not sure how easy / feasible this would be to fix, but the lloyds_bank_gb spider doesn't currently pick up the postcode or address for each branch. I don't know the details of what the spidering framework can detect by default, but the address data does seem to be included in the HTML in some sort of structured way.

**Comment by Cj-Malone** [comment]
```python
'address': [{'@type': 'PostalAddress'},
             {'@type': 'PostalAddress',
              'addressLocality': 'Aldershot',
              'streetAddress': '115 Victoria Road',
              'postalCode': 'GU11 1JQ',
              'addressCountry': 'GB'}]
```

The issue here is that they actually give us 2 addresses. We currently just take the first (and I think we reversed the order recently). We could easily use the last in this spider.

```python
    def pre_process_data(self, ld_data, **kwargs):
        ld_data["address"] = ld_data["address"][-1]
```

Or maybe we should merge multiple addresses in shared code... I don't know if that would backfire in any other spider though.

**Comment by jleedev** [comment]
When we see a `schema:PostalAddress` that has no other properties (or a `schema:GeoCoordinates` or really anything) it's probably safe to ignore it entirely.

Could do this here:

https://github.com/alltheplaces/alltheplaces/blob/51b0d65c4d6bd37ff4b8c4765dc421d4d0bcde72/locations/microdata_parser.py#L257

e.g.

```python
if not item["properties"]:
    return None
```

**Comment by rjw62** [comment]
I think the same issue is also present in the halifax_gb and bank_of_scotland_gb spiders. So it might be worth checking if the solutions proposed for Lloyds also work there.

**Comment by Cj-Malone** [comment]
I'll test that fix with those spiders as tests and let everyone know
