### ISSUE TITLE
Hungry Horse Spider Missing lots of branches

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#4306]
The hungry_horse spider is currently only returning 27 pubs. I think it should be more like 250. It looks like the regex used to filter pages from the side-map is only set to find a subset of the pages.  

The URLs of the pubs take the form `https://www.hungryhorse.co.uk/pubs/<county>/<pub>/`.

The current regex is `r"https://www.hungryhorse.co.uk/pubs/(west-[\w-]+)/([\w-]+)/$"` which thus only finds pubs in counties starting with "west-". 

Presumably the regex should be replaced with `r"https://www.hungryhorse.co.uk/pubs/([\w-]+)/([\w-]+)/$"` to capture all counties.

**Comment by Cj-Malone** [comment]
Yep, thank you. I got 252 with the better regex. I guess I changed to when I was checking the `sitemap_filter`, but never changed it back. woops.
