### ISSUE TITLE
Tapi Carpets results include closed branch holding pages

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#4310]
In the results returned by the tapi_gb spider there are a number of "branches" that I am assuming have previously closed, but the company has kept the web page and sitemap links, presumably for SEO purposes. The web pages for these zombie branches look different from the regular branch pages, but still contain some bare-bones JSON-LD data for the "branch".

Example real branch page: https://www.tapi.co.uk/stores/ashton-under-lyne

Example zombie branch pages: https://www.tapi.co.uk/stores/altrincham & https://www.tapi.co.uk/stores/bury

I'm not sure of the best way to detect and remove these zombie branches. They seem to have an empty openinghours array, and empty address strings apart from "postalCode": "SE6 2QU". However, that postcode is used for a genuine branch https://www.tapi.co.uk/stores/catford so you can't just remove all the branches with that postcode.

**Comment by Cj-Malone** [comment]
As usual I have opinions.

- [ ] We need docs for brands, not just us. We need a document to encourage brands to enable us to scrape them, to follow schema.org, to not block us with Cloudflare or similar. To tell them why they should care.
- [ ] We need a way to better highlight source errors, like your Chain Reaction tool, but more targeted on the source data not OSM. Noting issues with opening hours, coords, missing details, phone number issues and other stuff we clean in pipelines. This needs to be pretty and specific.
- [ ] We need a way to communicate with the brands. Clearly messaging customer service or admin@tld isn't going to work. I would love @schemaorg to require, (or strongly recommend) data providers put in contact details for the "data owner" who can fix the source errors, but even that spec was written today (it may already be possible via `contactPoint` or `accountablePerson`), it'd still take years to get adoption. We need a solution for today.

**Comment by Cj-Malone** [comment]
#8767
