### ISSUE TITLE
Setting country on Spider

### ISSUE THREAD

**Issue by Romeo-PHILLIPS** [alltheplaces/alltheplaces#4340]
Hi, I have a question about force setting country on a spider especially for this Spider: https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/c_and_a.py .

In the Spider we don't set the country but in the output the country is set. Is there a system in place that checks for example the country geometry and checks if the POI is in it?

I am asking this because this POI is marked DE but is actually FR (its located on the border of FR/DE)

```
{
   "type":"Feature",
   "id":"mEdI8GZHyjDatmvDGRz7BZClqaU=",
   "properties":{
      "ref":"FR0303",
      "wheelchair":"yes",
      "@spider":"c_and_a",
      "shop":"clothes",
      "addr:full":"Route nationale 61 1, 57520 Grosbliederstroff",
      "addr:street_address":"Route nationale 61 1",
      "addr:city":"57520 Grosbliederstroff",
      "addr:country":"DE",
      "name":"Grosbliederstroff",
      "phone":"Tel:",
      "website":"https://www.c-and-a.com/stores/fr-fr/grand-est/grosbliederstroff/route-nationale-61-1.html",
      "opening_hours":"Mo 09:00-19:00; Tu 09:00-19:00; We 09:00-19:00; Th 09:00-19:00; Fr 09:00-19:00; Sa 09:00-19:00",
      "image":"https://www.c-and-a.com/shop-img/ca-store/FR0303.JPG",
      "brand":"C&A",
      "brand:wikidata":"Q701338",
      "nsi_id":"canda-3937bd"
   },
   "geometry":{
      "type":"Point",
      "coordinates":[
         7.0421253,
         49.1353519
      ]
   }
},

```

**Comment by Romeo-PHILLIPS** [comment]
```
    city3 = 49.1353519, 7.0421253
    print(get(city3))
```

`{'country_code': 'DE', 'city': 'Kleinblittersdorf', 'country': 'Germany'}`

It shouldn't be returning FR

**Comment by brawer** [comment]
If your spider knows the country from the data (eg. by looking at `ref` or `website`), it’s probably best to set the country code explicitly. The pipeline runs some heuristics as a fallback, but these are not super reliable.
