### ISSUE TITLE
Missing branch from fiveguys.py spider

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#4357]
The fiveguys.py spider contains a condition at https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/fiveguys.py#L36 , which means it only considers branch URLs that contain a hyphen. This is too restrictive, as there's at least one branch that does not: https://restaurants.fiveguys.co.uk/scotland/340 . If you still want to avoid some of the non-branch URLs, a work-around might be there there's either a hyphen or at least two directory levels (i.e. at least 4 forward slashes in the URL).

**Comment by Cj-Malone** [comment]
Looks like that fixed it. Thanks everybody.
