### ISSUE TITLE
Postbank Bulgaria

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#4492]
### Brand name

Пощенска банка

### Wikidata ID

Q7234083

### Store finder url(s)

https://www.postbank.bg/bg-BG/api/locations/locations

**Comment by Cj-Malone** [comment]
FormRequest, should be pretty simple if anyone else wants to write this one.

`curl https://www.postbank.bg/en/api/locations/locations -d "contextItemPath=/sitecore/content/postbank/home" | jq`
