### ISSUE TITLE
Co-Op Credit Unions

### ISSUE THREAD

**Issue by ianmcorvidae** [alltheplaces/alltheplaces#45]
(via a shared branching site, possibly out of scope? http://co-opcreditunions.org/locator/ )

**Comment by iandees** [comment]
Going to clear the assignee on this so others can work on it. If you're still working on it, please re-assign to yourself and push up what you've got so far.

**Comment by MagnetonIO** [comment]
Is there any new issue now?
All of issues are self assigned.

**Comment by MagnetonIO** [comment]
@iandees 
I can't find opened issues.
Can you open new issues for me now?

**Comment by iandees** [comment]
There are several tickets available: https://github.com/alltheplaces/alltheplaces/issues?utf8=✓&q=no%3Aassignee+is%3Aissue+is%3Aopen+-label%3Aquestion

**Comment by MagnetonIO** [comment]
@iandees 
The opened issues have some problems, so can you assign me other available issues?

**Comment by iandees** [comment]
What problems do you see? If you're running into problems please document them on the issue so others don't waste their time on it.

For now, please feel free to write spiders for places that aren't already listed. It's especially useful to include places that are local to you so we can include a wider variety of places.

**Comment by MagnetonIO** [comment]
@iandees 
ok

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.
