### ISSUE TITLE
Billa

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#4508]
### Brand name

Billa

### Wikidata ID

Q537781 for Austria, Bulgaria and Slovakia; Q42969493 for Czechia

### Store finder url(s)

https://www.billa.at/api/stores
https://www.billa.bg/api/stores
https://www.billa.sk/api/stores

https://www.billa.cz/api/stores

**Comment by davidhicks** [comment]
Partially implemented for AT at https://data.alltheplaces.xyz/runs/2023-05-31-05-12-59/stats/billa_at.json
