### ISSUE TITLE
Homebase spider webpage regex is too restrictive

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#4512]
The homebase_gb_ie.py spider contains a regex in sitemap_rules to restrict things to store pages:
`sitemap_rules = [(r"https:\/\/store\.homebase\.co\.uk\/[-\w]+\/[-.\w]+$", "parse_sd")]`

This regex is slightly too strict, as there's a store with a "." in the place level: https://store.homebase.co.uk/st.-albans/the-courtyard-alban-park , which is currently not returned.

To include this store, the regex should presumably be changed to
`sitemap_rules = [(r"https:\/\/store\.homebase\.co\.uk\/[-.\w]+\/[-.\w]+$", "parse_sd")]`

**Comment by Cj-Malone** [comment]
@rjw62 you may be interested in https://www.wikidata.org/wiki/Wikidata:Property_proposal/location_URL_match_pattern

I don't know the exact details of the Wikidata process, but I think I need votes/comments.
