### ISSUE TITLE
Chemist Warehouse (Australian pharmacy/chemist)

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#4530]
### Brand name

Chemist Warehouse

### Wikidata ID

Q48782120

### Store finder url(s)

https://www.chemistwarehouse.com.au/ams/webparts/Google_Map_SL_files/storelocator_data.ashx?searchedPoint=(0,%200)&TrafficSource=1&TrafficSourceState=0

**Comment by davidhicks** [comment]
This URL returns an XML root element <markers> that contains one <marker> element per 490 Chemist Warehouse stores across Australia. A sample <marker> element is:

`  <marker lat="-42.7822" lng="147.562" viewAngle="" id="175" storename="Chemist Warehouse Sorell" storeaddress="2 Gordon St" storesuburb="Sorell" storepostcode="7172" storestate="TAS" storelocationinfo="Next to Westpac Bank and opposite Holts Mitre 10 at the traffic light end of Gordon Street" storephone="03 6265 2153" storefax="03 6269 2165" storeemail="sorell@chemistwarehouse.com.au" storemon="8.00AM - 7.00PM" storetue="8.00AM - 7.00PM" storewed="8.00AM - 7.00PM" storethu="8.00AM - 7.00PM" storefri="8.00AM - 7.00PM" storesat="8.00AM - 6.00PM" storesun="9.00AM - 5.00PM" isAround="false" isClosest="false"/>`

A similar spider to what would be required here is https://github.com/alltheplaces/alltheplaces/blob/HEAD/locations/spiders/biggby.py which also results in a single HTTP request returning XML data of all store locations and details.

**Comment by Cj-Malone** [comment]
@davidhicks do you want to try and write this? Otherwise I will.

**Comment by Cj-Malone** [comment]
Added in #4567
