### ISSUE TITLE
Sparkasse

### ISSUE THREAD

**Issue by FloEdelmann** [alltheplaces/alltheplaces#4571]
### Brand name

Sparkasse

### Wikidata ID

[Q13601825](https://www.wikidata.org/wiki/Q13601825)

### Store finder url(s)

https://www.sparkasse.de/service/filialsuche.html

**Comment by Cj-Malone** [comment]
Is [this](https://data.alltheplaces.xyz/runs/2023-01-07-13-32-28/output/sparkasse.geojson) the one? If so we already collect it.

**Comment by FloEdelmann** [comment]
It seems to be the same, but the data are not equal: e.g. https://www.sparkasse.de/service/filialsuche.html#details/114277 is part of the GeoJSON you linked, https://www.sparkasse.de/service/filialsuche.html#details/128017 is not.

**Comment by Cj-Malone** [comment]
But we have https://www.sparkasse.de/filialen/b/kreissparkasse-muenchen-starnberg-ebersberg-geschaeftsstelle-baldham/10714.html. This spider definitely needs work, I think Sparkasse is a collection of brands, not a unified one. Like coop in GB. https://github.com/osmlab/name-suggestion-index/pull/2475

**Comment by FloEdelmann** [comment]
> But we have [sparkasse.de/filialen/b/kreissparkasse-muenchen-starnberg-ebersberg-geschaeftsstelle-baldham/10714.html](https://www.sparkasse.de/filialen/b/kreissparkasse-muenchen-starnberg-ebersberg-geschaeftsstelle-baldham/10714.html).

But it is not displayed on the [alltheplaces map](https://www.alltheplaces.xyz/map/#17.89/48.099558/11.787522). Was the position wrongly extracted?

> I think Sparkasse is a collection of brands, not a unified one.

Yes, there are different "Sparkassen", but the "Filialsuche" I linked should find them all regardless of sub-brand.

**Comment by iandees** [comment]
> it is not displayed on the [alltheplaces map](https://www.alltheplaces.xyz/map/#17.89/48.099558/11.787522). Was the position wrongly extracted?

I believe it's sitting directly underneath the Edeka point here: https://www.alltheplaces.xyz/map/#18.43/48.0997793/11.7882315, which is why it's purple.

**Comment by Cj-Malone** [comment]
Ironically this spider broke this week. I've not looked at the details yet, and honestly I'm a little overwhelmed by the brand thing. But I'll look at this in the next few days, unless someone else looks at it first.

Spider | 2023-01-14 | 2023-01-07
-- | -- | --
sparkasse | 0 | 8763
