### ISSUE TITLE
Barbeques Galore (Australian outdoor goods retailer)

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#4588]
### Brand name

Barbeques Galore

### Wikidata ID

Q4859570

### Store finder url(s)

https://www.barbequesgalore.com.au/stores/act/all-stores-in-australian-capital-territory.html
https://www.barbequesgalore.com.au/stores/nsw/all-stores-in-new-south-wales.html
https://www.barbequesgalore.com.au/stores/nt/all-stores-in-northern-territory.html
https://www.barbequesgalore.com.au/stores/qld/all-stores-in-queensland.html
https://www.barbequesgalore.com.au/stores/sa/all-stores-in-south-australia.html
https://www.barbequesgalore.com.au/stores/tas/all-stores-in-tasmania.html
https://www.barbequesgalore.com.au/stores/vic/all-stores-in-victoria.html
https://www.barbequesgalore.com.au/stores/wa/all-stores-in-western-australia.html

**Comment by Cj-Malone** [comment]
Looks like a standard CrawlSpider + StructuredDataSpider should handle this one
