### ISSUE TITLE
New spider suggestion: TSB (UK High Street Bank)

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#4614]
### Brand name

TSB

### Wikidata ID

Q7671560

### Store finder url(s)

https://branches.tsb.co.uk/sitemap.xml

Individual branch pages can be distinguished from locality pages by the fact that the former end in ".html".

**Comment by Cj-Malone** [comment]
It looks like standard Microdata too, so it can be a StructuredDataSpider (and SitemapSpider for page discovery). Although the Microdata has 2 types so we'd have to define them with `wanted_types = [["BankOrCreditUnion", "FinancialService"]]`. (This is a bug, it's not how I meant to implement it)

We can check it with:
`$ pipenv run scrapy sd https://branches.tsb.co.uk/aberdeen/aberdeen-st-nicholas.html --wanted-types=BankOrCreditUnion,FinancialService`

```python
{'city': None,
 'email': None,
 'extras': {},
 'image': 'https://branches.tsb.co.uk/aberdeen/aberdeen-st-nicholas.html',
 'lat': '57.147410168890175',
 'lon': '-2.0984620085982897',
 'name': 'Aberdeen, 7-21a St Nicholas St',
 'opening_hours': 'Mo-Tu 09:00-17:00; We 10:00-17:00; Th-Fr 09:00-17:00; Sa '
                  '09:00-15:00',
 'phone': '01224 369984',
 'postcode': 'AB10 1HE',
 'ref': 'https://branches.tsb.co.uk/#13597885',
 'state': None,
 'street_address': '7-21a St Nicholas St Aberdeen',
 'website': 'https://branches.tsb.co.uk/aberdeen/aberdeen-st-nicholas.html'}
```

**Comment by davidhicks** [comment]
Implemented and working per https://data.alltheplaces.xyz/runs/2023-05-31-05-12-59/stats/tsb_gb.json
