### ISSUE TITLE
New spider suggestion: Grape Tree (UK health food chain)

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#4621]
### Brand name

Grape Tree

### Wikidata ID

Q87071497

### Store finder url(s)

https://www.grapetree.co.uk/stores/locator/store/l

Note that https://www.grapetree.co.uk/sitemap.xml contains the stores but the URL paths there (which begin /store-locator/l/ ) are incorrect.

**Comment by Cj-Malone** [comment]
Unfortunately the linked data is loaded by JavaScript so I had to use the api.
