### ISSUE TITLE
Yettel Serbia

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#4654]
### Brand name

Yettel

### Wikidata ID

Q1780171

### Store finder url(s)

https://www.yettel.rs/stores/latlong/

Mo - Ponedeljak
Tu - Utorak
We - Sreda
Th - Četvrtak
Fr - Petak
Sa - Subota
Su - Nedelja

**Comment by Cj-Malone** [comment]
Does 132 stores sound right? If so a single FormRequest should give all the data `curl -X POST https://www.yettel.rs/stores/latlong/ -d "lat=0&lng=0&dist=10000000000" `

**Comment by Dimitar5555** [comment]
It looks like there are 132 stores in the whole country. The IDs reach 350, but I assume that it's due to a lot of additions and removals in their DB.

**Comment by Cj-Malone** [comment]
Sounds good, do you want to write this one too? If not I can do it.

**Comment by Dimitar5555** [comment]
I will try to do Telenor Denmakr first and see what I can do.

**Comment by Cj-Malone** [comment]
OK, let me know if you need any help.
