### ISSUE TITLE
Telenor Denmark

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#4655]
### Brand name

Telenor

### Wikidata ID

Q1796954

### Store finder url(s)

Most useful data is in HTML strings..

https://www.telenor.dk/da/custom/FindNearestShopBlock/GetShops/2bd5f376-3f79-475b-aa1e-b45174b9a2f3/?blockId=1590

**Comment by Cj-Malone** [comment]
A Selector on the html should make it fairly easy to parse. @Dimitar5555 are you going to do this?

**Comment by Dimitar5555** [comment]
I'm not very fluent with Python. Can you show me a spider which has done it for another brand?

**Comment by Cj-Malone** [comment]
`yettel_bg` has a similar combination, part JSON, part html/xpaths/Selector
