### ISSUE TITLE
"TotalEnergies.fr" places that don't exist (Chile)

### ISSUE THREAD

**Issue by confor** [alltheplaces/alltheplaces#4672]
hello, i came across this project while reading [something](https://notes.labordata.bunkum.us/2023/01/09/corp-registry.html) and noticed that there seems to be a massive quantity of "totalenergies.fr" stores all around chile that don't actually exist.

the company totalenergies "is a multi-energy company that produces and markets fuels, natural gas and electricity" ([source](https://totalenergies.com/company/identity)) but most of chile has a monopoly of very few companies that deal with fuel/electricity and i've never heard or seen totalenergies.fr.

while trying to figure out where this data is coming from, i saw the [`total_energies.py` crawler](https://github.com/alltheplaces/alltheplaces/blame/master/locations/spiders/total_energies.py) and ended up going to https://store.totalenergies.fr/ where the main map is shown, only to notice that there aren't any stores in chile (labelled "Chili" because french). i don't know where they're coming from.

while clicking around the map, i can notice that most of the stores have "name" tags that match to small local towns so i can only assume they're selling totalenergy products (like what?) but this is not very convincing. additionally, i've checked many places where i've been and i can confirm that the store "totalenergies.fr" does NOT exist. the only thing they have in common is that they all seem to be brand-less small local stores for auto repair tools or car products. the openstreetmap tag catalogs every single place as fuel, which is incorrect.

random examples:
- [-70.586128,-33.410666](https://www.alltheplaces.xyz/map/#17.15/-33.410666/-70.586128) "Derco S.A. Comercial automotriz": derco is a company that sells new cars (https://www.dercocenter.cl/). it was founded in chile about 70 years ago and its not related to totalenergies.fr.
- [-70.729637,-33.360176](https://www.alltheplaces.xyz/map/#14.76/-33.36018/-70.72964): this is a local mechanic shop. [heres a pic ](https://user-images.githubusercontent.com/38121691/213894986-655fa9f5-ae1c-4f39-9ded-9124747264f6.png) from google streetview.
- [-71.652532,-35.429484](https://www.alltheplaces.xyz/map/#14.25/-35.42948/-71.65253): a small shop that sells car parts. again, [here's a google streetview picture](https://user-images.githubusercontent.com/38121691/213895065-f92619b7-f772-4f07-80ac-30cf878d2e0c.png).

i checked six different cities and i can confirm that there has actually existed a shop at that place at some point but its most certainly not totalenergies.fr and most of them aren't open anymore. all of them are related to mechanics or cars. the name tag in them is mostly correct, but a lot of them have a person's name (owner, maybe?).

i thought i'd raise an issue about this since the map is polluted with places that don't correspond to the brand. i checked the git log to scrape some emails and ask the spiders/total_energies.py contributors directly but that just feels wrong. i don't want to bother people directly.

i don't have a solution, sorry.

**Comment by confor** [comment]
by the way, apologies if my writing is weird or wrong. i haven't used english in a while and i'm a bit rusty on it. also i can't read french so i have no idea what https://www.totalenergies.fr/ is about. i don't know if this repo is the right place to raise an issue about this kind of thing, either. please point me to the right place if this is not it. thanks

**Comment by brawer** [comment]
Looking at https://store.totalenergies.fr/ and glancing over the code in [here](https://github.com/alltheplaces/alltheplaces/blob/master/locations/storefinders/woosmap.py) and [here](https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/total_energies.py), it seems the spider could certainly be improved. For example, we probably shouldn’t tag a place as a gas station when Total’s website doesn’t say so. Also, the spider could emit tags for the kind of gas being sold.

Do you want to try fixing it? Instructions for getting started are [here](https://github.com/alltheplaces/alltheplaces#getting-started).

**Comment by Cj-Malone** [comment]
This may be related to the "brand" https://github.com/alltheplaces/alltheplaces/pull/4254#issuecomment-1326449224

**Comment by Cj-Malone** [comment]
Your English is great. Thanks for pointing this out.

I've just spent a few hours looking at the data, the following probably wont mean much to you, TBH it doesn't mean much to me, I'm just documenting it.

`poiType=t002` seems to be fuel stations. Throwing the others away removes all locations in CL.

`status=2` seems to be operating/normal.

This data seems to be way more than just Total Energies locations, we can brand most of it. However I think I'd be open to dropping all that we can't brand. Maybe even everything that it's Total.

There is indeed tones of metadata for this one.
