### ISSUE TITLE
Odeon Cinemas

### ISSUE THREAD

**Issue by UKChris-osm** [alltheplaces/alltheplaces#4696]
### Brand name

Odeon Cinemas

### Wikidata ID

Q6127470

### Store finder url(s)

https://www.odeon.co.uk/sitemap.xml is the entire site map
https://www.odeon.co.uk/cinemas/*/ lists all the Odeon's.

\* = location

**Comment by Cj-Malone** [comment]
Thanks.

I decided not to parse every location via the sitemap because I couldn't find the coords in the page. Instead I found some JSON in the home page.
