### ISSUE TITLE
opening_hours vs. opening_hours:drive_through

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#4740]
[DATA_FORMAT.md](https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md) should either include [opening_hours:drive_through](https://wiki.openstreetmap.org/wiki/Key:opening_hours:drive_through) as a new property or state whether restaurant dining room or drive-through hours should be extracted and used, or whether the longer hours of the two should be used.

Any suggestions for how to handle opening_hours vs. opening_hours:drive_through?

**Comment by iandees** [comment]
`opening_hours` is the hours for the business. In the case of a restaurant or bank with a drive through, it should be for the dining room or lobby. If you'd like to extract other opening hours, feel free to add them to the `extras` dict.

**Comment by davidhicks** [comment]
Thanks @iandees I'll propose some documentation changes to make the situation clearer to newbies like myself :)

**Comment by CloCkWeRX** [comment]
Closable given related PR?
