### ISSUE TITLE
moneygram: use new Where2GetIt spider

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#4749]
The MoneygramSpider (moneygram.py) is currently a customised crawl spider that could seemingly be simplified to a single request by using the Where2GetIt spider introduced in https://github.com/alltheplaces/alltheplaces/pull/4741

The W2GI application key appears to be 46493320-D5C3-11E1-A25A-4A6F97B4DA77 as obtained from https://hosted.where2getit.com/moneygram/en.htm

@Cj-Malone

**Comment by Cj-Malone** [comment]
See https://github.com/alltheplaces/alltheplaces/issues/4757#issuecomment-1424027513 for my personal preferences, but the last run moneygram gave us 68,236 POIs. The Where2GetIt data will be dramatically more efficient.
