### ISSUE TITLE
quiktrip: fix with use of SitemapSpider to replace old Where2GetIt implementation

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#4752]
QuiktripSpider (quiktrip.py) appears to have removed their Where2GetIt implementation from their website. In place, it appears that a Sitemap Spider with a start point of https://locations.quiktrip.com/sitemap.xml may need to be implemented instead. The user visible store locater is now found at https://locations.quiktrip.com/index.html

**Comment by Cj-Malone** [comment]
I'd call this on a priority, and a clear con for these 3rd party APIs. No errors and we keep publishing the 853 POIs, but they've stopped updating that data, there website now says 969 POIs...

**Comment by davidhicks** [comment]
Numerous third party APIs I've come across will disable/block access to a brand's API key if the brand stops paying for the service. Therefore normally it'd be obvious if a brand stopped using a third party API.

Where it's difficult is if a brand changes their store locator, but keeps paying the bills accidentally for a service they no longer use.
