### ISSUE TITLE
michaels: use new Where2GetIt spider

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#4753]
https://github.com/alltheplaces/alltheplaces/pull/4741 introduces a new Where2GetIt spider that Michaels also appear to now use.

The current MichaelsSpider (michaels.py) uses a SitemapSpider that seemingly can now be replaced with a single request via the Where2GetIt spider using application key F35DCF8C-4F17-11E0-B7D3-E77C241F5146 that is found on sample store page https://locations.michaels.com/AK/Anchorage/5806/

@Cj-Malone

**Comment by Cj-Malone** [comment]
Again, my preferences: https://github.com/alltheplaces/alltheplaces/issues/4757#issuecomment-1424027513
