### ISSUE TITLE
Mitre 10 (Australian hardware store chain)

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#4783]
### Brand name

Mitre 10

### Wikidata ID

Q6882393

### Store finder url(s)

https://www.mitre10.com.au/stores

The store finder home page has an embedded JavaScript object containing store data.

**Comment by Cj-Malone** [comment]
@davidhicks FYI if you put "fixes #issue" in the PR it'll automatically close the issues
