### ISSUE TITLE
Relationship between vetco and petco

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#4809]
I was looking at fixing the `vetco` spider, but after a quick look on the website everything I've seen is titled "At Petco".

To the Americans: is Vetco a real brand?

**Comment by iandees** [comment]
I don't think I've ever seen a "Vetco" before. I've definitely heard of Petco, though.

**Comment by Cj-Malone** [comment]
The [vetcoclinics.com](https://www.vetcoclinics.com) Terms of Service just link to Petco. I vote to delete the Vetco spider.

**Comment by Cj-Malone** [comment]
@thekuiperbelt I see you wrote this one, any opinion?
