### ISSUE TITLE
Caffe Nero GB

### ISSUE THREAD

**Issue by UKChris-osm** [alltheplaces/alltheplaces#4917]
### Brand name

Caffe Nero

### Wikidata ID

Q675808

### Store finder url(s)

https://caffenero.com/uk/stores/

Looking at the source code of the above URL, line 295 appears to show a JavaScript data object called `storesData` which appears to contain store data for many (or all) of the GB stores, including the URL for each one.

Could this variable be extracted and broken up by a spider?

**Comment by Cj-Malone** [comment]
Oh I assigned myself, but I didn't ask if you wanted to do it yourself?

Yeah, this should be fairly straight forward, an xpath to get JavaScript, `chompjs.parse_js_object` will probably parse that, if not we'll have to extract part of the JavaScript with regex. Then loop that and yield the results.

Probably really similar to super_one_foods_us.

**Comment by UKChris-osm** [comment]
You're welcome to do it @Cj-Malone as I'm focusing on another project at the moment, so wouldn't be able to do this quickly.

I might try some others in a couple weeks or so :)
