### ISSUE TITLE
Fix Dickey's Barbecue Pit which has now switched to GraphQL

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#5018]
Dickey's Barbecue Pit (dickeys_barbecue_pit) just broke in the latest weekly run. It appears that pages on the website no longer return structured data and instead, the brand has switched over to using GraphQL.

Below is a GraphQL query that returns all store details (first=2000 variable controls how many are returned). The query needs a large clean-up to only select fields necessary, and to provide alternative field names where necessary.

curl 'https://orders-api.dickeys.com/graphql' -X POST -H 'content-type: application/json' --data-raw '{"query":"\n  query Stores(\n    $first: Int\n    $personId: Int\n    $firstAll: Int\n    $sort: [LocationSort]\n    $firstSubcategorySort: [SubcategorySort]\n    $firstSubcategoryFilter: [SubcategoryFilter]\n    $filter: [LocationFilter]\n    $locationHandoffCategoryFilter: [LocationHandoffCategoryFilter]\n    $locationVendorFilter: [LocationVendorFilter]\n  ) {\n    viewer {\n      id\n      personId\n      firstName\n      email\n      locationConnection(first: $first, sort: $sort, filter: $filter) {\n        edges {\n          node {\n            id\n            label\n            slug\n            storeNumber\n            distance\n            active\n            opened\n            isOpened\n            deliveryRadius\n            timezone {\n              id\n              label\n            }\n            locationVendorConnection (filter: $locationVendorFilter) {\n              edges {\n                node {\n                  vendor {\n                    id\n                    label\n                    vendorimage {\n                      url\n                    }\n                  }\n                  deliveryUrl\n                }\n              }\n            }\n            locationExclusiveDeliveryAddressConnection {\n              edges {\n                node {\n                  id\n                  address {\n                    id\n                    address\n                    zip\n                    city\n                  }\n                }\n              }\n            }\n            locationWeekdayConnection(filter: { showHoliday: { eq: true } }) {\n              edges {\n                node {\n                  id\n                  opened\n                  active\n                  closed\n                  locationHours {\n                    id\n                    opened\n                    active\n                    closed\n                  }\n                  weekday {\n                    weekdayId\n                    id\n                    type\n                    label\n                  }\n                }\n              }\n            }\n            locationHandoffCategoryConnection(first: 1000, filter: $locationHandoffCategoryFilter) {\n              edges {\n                node {\n                  id\n                  handoff {\n                    id\n                    label\n                  }\n                  category {\n                    id\n                  }\n                  radius\n                }\n              }\n            }\n            address {\n              id\n              address\n              city\n              state {\n                id\n                abbreviation\n              }\n              zip\n              latitude\n              longitude\n            }\n            phone {\n              id\n              phone\n            }\n            menu {\n              id\n              subcategoryConnection(\n                first: 1\n                sort: $firstSubcategorySort\n                filter: $firstSubcategoryFilter\n              ) {\n                edges {\n                  node {\n                    id\n                    subcategoryId\n                    slug\n                    orderKey\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      stateConnection(first: $firstAll) {\n        edges {\n          node {\n            id\n            label\n          }\n        }\n      }\n      personConnection(filter: { personId: { eq: $personId } }) {\n        edges {\n          node {\n            id\n            personLocationConnection {\n              edges {\n                node {\n                  id\n                  isFavorite\n                  location {\n                    id\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n","variables":{"first":2000,"firstAll":2147483647,"sort":{"distance":{"latitude":34.1030032,"longitude":-118.4104684,"order":"ASC"}},"firstSubcategorySort":{"orderKey":"ASC"},"firstSubcategoryFilter":{"category":{"categorytype":{"slug":{"eq":"everyday"}}},"dontShowEmpty":{"eq":true}},"filter":{"isOpened":{"eq":true}},"locationHandoffCategoryFilter":[{"active":{"eq":true},"category":{"id":{"eq":"Q2F0ZWdvcnk6MTo5OTk5LTEyLTMxIDIzOjU5OjU5LjAwMDAwMA=="}},"handoff":{"id":{"in":["SGFuZG9mZjoyOjk5OTktMTItMzEgMjM6NTk6NTkuMDAwMDAw","SGFuZG9mZjo0Ojk5OTktMTItMzEgMjM6NTk6NTkuMDAwMDAw"]}}}]}}'

When fixing this spider, it should be renamed to dickeys_barbecue_pit_us as this brand is only present in the USA. There is a single store in Canada now opened, but it appears the intent from the brand is that the Canadian chain would have a different website and different store locator.

**Comment by Cj-Malone** [comment]
Quick go at trimming the query down, `storeTypeId` and  `active` may be interesting.

```graphql
query {
  viewer {
    locationConnection(first: 2000, filter: { isOpened: { eq: true } }) {
      edges {
        node {
          name: label
          slug
          ref: storeNumber
          storeTypeId
          active
          isOpened
          start_date: opened
          end_date: closed
          address {
            street_address: address
            city
            state {
              abbreviation
            }
            zip
            latitude
            longitude
          }
          phone {
            phone
          }
          email
        }
      }
    }
  }
}
```
