### ISSUE TITLE
Fix Costa Coffee (US) which has switched from Amasty to a JSON API

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#5019]
In the latest weekly run, Costa Coffee (costacoffee_us) is now broken with the Amasty "amlocator" AJAX endpoint no longer existing. In it's place appears to be a JSON API that returns store details (locations and addresses):

https://us.costacoffee.com/api/cf/?locale=en-US&include=2&content_type=storeLocatorStore&limit=500&fields.location[near]=33.77804102,-84.38068933

This appears to be a fairly easy fix to rewrite the spider to use the new JSON API (with a higher limit than 500).

**Comment by Cj-Malone** [comment]
And pages [nicely](https://us.costacoffee.com/api/cf/?locale=en-US&include=2&content_type=storeLocatorStore&limit=500&skip=500).

I've seen this `fields`/`sys`/`metadata` thing before, but I don't think I looked into the details. We should keep an out in case it's common and deserves shared code.

**Comment by davidhicks** [comment]
locations/spiders/costacoffee_ie.py:20:                "ref": store_data["sys"]["id"],
locations/spiders/tele2_se.py:34:                    "ref": store.get("sys").get("id"),
locations/spiders/brewdog.py:21:            item["ref"] = bar["sys"]["id"]

**Comment by davidhicks** [comment]
> And pages [nicely](https://us.costacoffee.com/api/cf/?locale=en-US&include=2&content_type=storeLocatorStore&limit=500&skip=500).
> 
> I've seen this `fields`/`sys`/`metadata` thing before, but I don't think I looked into the details. We should keep an out in case it's common and deserves shared code.

@Cj-Malone I finally found out what this pattern is. It's Contentful (https://www.contentful.com/developers/docs/references/content-delivery-api/). I've raised a new issue to investigate the possibility of a storefinder being produced at https://github.com/alltheplaces/alltheplaces/issues/7848
