### ISSUE TITLE
Regal Theaters

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#508]
https://www.regmovies.com/theaters

**Comment by evanmosseri** [comment]
sorry, I posted this for me, can I complete this job?

**Comment by sledjama** [comment]
oh! sorry about that. Please go ahead

**Comment by evanmosseri** [comment]
https://www.regmovies.com/sitemap-theater-detail-pages.xml

**Comment by iandees** [comment]
Please don't close issues without an explanation or a link to a pull request that adds a spider.

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by evanmosseri** [comment]
In the middle of this right now. Will be spending a lot of time hammering out some scripts tonight, reassigning myself for tonight and will unassign myself if I don't complete it by tomorrow morning.
