### ISSUE TITLE
ToysRUs

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#509]
https://www.toysrus.com/storelocator/showGoogleMap.jsp
http://stores.toysrus.com/

**Comment by evanmosseri** [comment]
sorry, I posted this for me, can I complete this job?

**Comment by vlad555** [comment]
sorry, I didn't know
Of course, I released

**Comment by vlad555** [comment]
By the way. I thought spider for ToyRUS already done

**Comment by evanmosseri** [comment]
finished

**Comment by evanmosseri** [comment]
the script keeps getting timed out on travis with no output even though it runs fine locally. Unless there is something obvious that I am missing, I think that toysrus might be blocking hosting IP addresses
