### ISSUE TITLE
therange.co.uk

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#515]
https://www.therange.co.uk/stores/

**Comment by evanmosseri** [comment]
How do I self-assign this?

**Comment by vlad555** [comment]
![image](https://user-images.githubusercontent.com/9920034/34086535-58a1141a-e351-11e7-84a4-f45acd29e44b.png)
press here

**Comment by evanmosseri** [comment]
Not an option for me, can you add me as a contributor?

**Comment by iandees** [comment]
@evanmosseri I invited you a couple hours ago.

**Comment by evanmosseri** [comment]
@iandees I never got an invite, are you sure that you added me as a contributor? I am not on the contributor list: https://github.com/alltheplaces/alltheplaces/graphs/contributors

**Comment by iandees** [comment]
@evanmosseri check your email (including spam). Or go to https://github.com/orgs/alltheplaces and you should be able to accept the invite.

**Comment by evanmosseri** [comment]
Ah, sorry I don't usually use that email, got it.

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.
