### ISSUE TITLE
Add WP Store Locator store finder

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#5188]
There is a store locator plugin for WordPress @ https://github.com/wp-plugins/wp-store-locator which is used by many spiders already part of ATP:

```
grep -Rn "admin-ajax.php?action=store_search" *.py
bre_wingz.py:9:    start_urls = ["https://www.brewingz.com/wp-admin/admin-ajax.php?action=store_search&autoload=1"]
bucees_us.py:13:    start_urls = ["https://buc-ees.com/wp-admin/admin-ajax.php?action=store_search&autoload=1"]
busy_beaver.py:15:        "https://busybeaver.com/wp-admin/admin-ajax.php?action=store_search&lat=40&lng=-79&max_results=5000&search_radius=5000&autoload=1",
carpet_court_nz.py:12:        "https://carpetcourt.nz/wp-admin/admin-ajax.php?action=store_search&lat=0&lng=0&categories=&stories=0&max_results=100000&search_radius=500000"
coastal_farm.py:12:        "https://www.coastalfarm.com/wp-admin/admin-ajax.php?action=store_search&lat=45.523062&lng=-122.67648199999996&max_results=25&search_radius=50",
cookout.py:17:        base_url = "https://cookout.com/wp-admin/admin-ajax.php?action=store_search&lat={lat}&lng={lng}&max_results=300&search_radius=500"
curves_nl.py:13:        "https://curves.nl/wp-admin/admin-ajax.php?action=store_search&max_results=25000&search_radius=10000000&autoload=1"
food_city_us.py:11:    start_urls = ["https://myfoodcity.com/wp-admin/admin-ajax.php?action=store_search&max_results=250&autoload=1"]
footgear_za.py:10:    start_urls = ["https://www.footgear.co.za/wp-admin/admin-ajax.php?action=store_search&autoload=1"]
kum_and_go.py:33:                        f'https://www.kumandgo.com/wordpress/wp-admin/admin-ajax.php?action=store_search&lat={point["latitude"]}&lng={point["longitude"]}&max_results=100&search_radius=100',
lundsandbyerlys.py:13:        "https://lundsandbyerlys.com/wp-admin/admin-ajax.php?action=store_search&autoload=1",
mobilelink.py:12:        "https://mobilelinkusa.com/wp-admin/admin-ajax.php?action=store_search&lat=29.760427&lng=-95.36980299999999&max_results=1000&search_radius=10000&autoload=1",
premierurgentcare.py:18:        "http://www.premierimc.com/wp-admin/admin-ajax.php?action=store_search&lat=40.030628&lng=-75.36398400000002&max_results=50&search_radius=10&autoload=1",
relay_fr.py:16:            url = f"https://www.relay.com/wp-admin/admin-ajax.php?action=store_search&lat={lat}&lng={lon}&max_results=1000&search_radius=140"
smilebrands.py:12:        "https://smilebrands.com/wp-admin/admin-ajax.php?action=store_search&lat=39.11553&lng=-94.62679&max_results=100000&search_radius=100&autoload=1",
soul_pattinson_chemist_au.py:12:    start_urls = ["https://soulpattinson.com.au/wp-admin/admin-ajax.php?action=store_search&autoload=1"]
superamerica.py:14:        "http://superamerica.com/wp-admin/admin-ajax.php?action=store_search&lat=45.0&lng=-90.0&max_results=0&search_radius=500",
superconti_it.py:12:    start_urls = ["https://www.superconti.eu/wp-admin/admin-ajax.php?action=store_search&autoload=1"]
```

These could be simplified/grouped by subclassing from a new WP Store Locator store finder class.

**Comment by Cj-Malone** [comment]
@davidhicks do you intend to work on this? Or shall I do it?

**Comment by davidhicks** [comment]
If you have the time, please go right ahead :) I won't have an opportunity to work on this for another week.

**Comment by davidhicks** [comment]
If you do get around to implementing this one, can some documentation be provided in the store locator to link to https://github.com/wp-plugins/wp-store-locator/blob/master/frontend/wpsl-ajax-functions.php#L15 as the source code for the function that validates supplied parameters and returns the result.

This store locator seemingly won't need parameters either as the source code confirms the following parameters will always return all store results:

```
?action=store_search&lat=0&lng=0&autoload=1
```

Perhaps just copy the approach used at https://github.com/alltheplaces/alltheplaces/blob/master/locations/storefinders/amasty_store_locator.py#L27-L33 where an allowed_domains = ["..."] can be supplied with a single domain, and then the suffix of "/wp-admin/admin-ajax.php?action=store_search&lat=0&lng=0&autoload=1" can just be appended. If for some weird reason the location of admin-ajax.php differs, then start_urls = ["..."] could be supplied instead.

**Comment by Cj-Malone** [comment]
I don't like misusing `allowed_domains`. But I like you, so I did it anyway.

**Comment by davidhicks** [comment]
I'm happy to switch to start_urls only, and base spider users then have to supply the full path rather than just a domain name for the brand.

An automated spider creator would generally be best to ask for the Wikidata ID of a brand, and then get the domain from https://www.wikidata.org/wiki/Property:P856 and try multiple common API endpoint paths to check if a self-hosted store finder such as WP Store Locator was used. And if that doesn't work, crawl the first level pages from the home page (preferring those URLs with certain names in the path such as "find"/"store"/etc and then use XPath queries to find an external store-finder-as-a-service API in use, and the required parameters such as the API key.
