### ISSUE TITLE
State Farm Agents

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#519]
https://www.statefarm.com/agent/US

**Comment by Eagle19243** [comment]
@iandees, this website provides agent informations. So it has no lat, lon info and opening_hours.

**Comment by Eagle19243** [comment]
At this point, we can ignore those fields?

**Comment by iandees** [comment]
Yes, if those fields aren't presented then you can skip them.

**Comment by Eagle19243** [comment]
Ok, I got it.

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.
