### ISSUE TITLE
Family Dollar

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#527]
https://www.familydollar.com/content/familydollar/en/store-results.html

They're a client of Brandify, which means we can re-use the AJAX parsing we do in other Brandify stores.

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by skorasaurus** [comment]
is the parsing for the brandify stores shared somewhere? a repo search of brandify didn't turn up anything

**Comment by iandees** [comment]
Not yet, but it should be.
