### ISSUE TITLE
Rent-A-Center

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#528]
Index of all states near the bottom of this page: https://locations.rentacenter.com/

**Comment by vlad555** [comment]
Search with ZIP, dynamic loading pages, requests with security tokens.

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.
