### ISSUE TITLE
Build server failure: python dependencies need updating

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#5295]
Per https://data.alltheplaces.xyz/runs/2023-05-15-03-47-28/logs/forty_winks_au.txt the build server is missing the `tzdata` module that was recently added as a dependency for ATP. The build server likely just needs a dependencies update.

**Comment by iandees** [comment]
tzdata was never added as a dependency. I'll add it.

**Comment by davidhicks** [comment]
Thank you!

I got mixed up with https://github.com/alltheplaces/alltheplaces/pull/5181 and thought I'd previously added `tzdata` when in fact it was removal of `xlrd`.
