### ISSUE TITLE
Cochlear Implants

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#530]
http://www.cochlear.com/wps/wcm/connect/us/home/take-the-next-step/contact-a-hearing-specialist

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by CloCkWeRX** [comment]
Don't know if this is valuable, finds clinics but not under one Brand
