### ISSUE TITLE
petsathome_gb spider unstable

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#5309]
The most recent run of the petsathome_gb spider from 2023-05-15 has returned 50 fewer stores than the previous run from 2023-04-15. I've checked a few of the missing stores, and they all appear to still exist. For example:
* https://community.petsathome.com/store/yeovil/
* https://community.petsathome.com/store/east-grinstead/
* https://community.petsathome.com/store/barrow/
* https://community.petsathome.com/store/ipswich/

I've tried running the spider locally, with similar (though not identical) results to the 2023-05-15 run. The only clue I've spotted is that the log output shows a number of HTTP 404 responses. I don't know if these are on store URLs or from the search points. Is anyone able to shed any light on this?

**Comment by Cj-Malone** [comment]
This doesn't fix it either. [South East](https://www.petsathome.com/shop/en/pets/store-locations-results/southeast) links to `http://community.petsathome.com/stores/ST_ALBANS/` which redirects a couple times, then 404s. The real url is `https://community.petsathome.com/store/st-albans/`

There site is just broken at the moment... I think we just come back in a few week and see if the site is fixed.

```python
from scrapy.link import Link
from scrapy.linkextractors import LinkExtractor
from scrapy.spiders import CrawlSpider, Rule

from locations.structured_data_spider import StructuredDataSpider


class PetsAtHomeGBSpider(CrawlSpider, StructuredDataSpider):
    name = "petsathome_gb"
    item_attributes = {"brand": "Pets at Home", "brand_wikidata": "Q7179258"}
    allowed_domains = ["petsathome.com"]
    start_urls = ["https://www.petsathome.com/shop/en/pets/store-locations"]
    rules = [
        Rule(LinkExtractor(allow=["https://www.petsathome.com/shop/en/pets/store-locations-results/"])),
        Rule(
            LinkExtractor(allow=["http://community.petsathome.com/stores/"]),
            callback="parse_sd",
            process_links="clean_links",
        ),
    ]
    wanted_types = ["PetStore"]
    custom_settings = {"ROBOTSTXT_OBEY": False}

    # Skip a bunch of redirects
    @staticmethod
    def clean_links(links: [Link]):
        for link in links:
            link.url = (
                link.url.lower().replace("http://", "https://").replace(":443", "").replace("/stores/", "/store/")
            )
            yield link
```

**Comment by CloCkWeRX** [comment]
Is this one still busted? Or closable since skipped?

**Comment by rjw62** [comment]
I don't know the details of what's been changed, but the output now looks ok when compared with OSM (https://osm.mathmos.net/chains/Q7179258/) and the number of stores returned is stable at 461. (FYI the spider was renamed to pets_at_home_gb a few weeks ago.)
