### ISSUE TITLE
T-Mobile US Stores

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#531]
This returns max 50 stores:

https://www.t-mobile.com/srvspub/storelocsearch?authorizedRetailers=true&coporateStores=true&count=1000&dist=5000&latcentre=44.9761378&lngcentre=-93.271724&prepaidStores=false&query=80+S+8th+St+Ste+205,+Minneapolis,+MN,+United+States&sortBy=Store+Type&start=0

**Comment by sweetdream0729** [comment]
working on this
