### ISSUE TITLE
UPS Store

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#536]
Not much to go on here:

https://www.theupsstore.com/tools/find-a-store

**Comment by eusid** [comment]
Will give this one a look. I'll post my findings.

**Comment by eusid** [comment]
![image](https://user-images.githubusercontent.com/552127/34183059-d2ca4b3a-e4e6-11e7-8f86-3ada5c6e00a2.png)

API works and returns 30 results at a time. Does not expect cookies. Looking for other choices besides zip code, or a way to widen the radius.  Thinking about the overall problem you guys are having here with the zip codes also.

**Comment by eusid** [comment]
@iandees Permission to burn through zip codes? I could also experiment with the middleware idea from #538

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.
