### ISSUE TITLE
White Castle

### ISSUE THREAD

**Issue by brentajones** [alltheplaces/alltheplaces#54]
https://www.whitecastle.com/locations

**Comment by iandees** [comment]
Removing the assignee on this so others can give it a shot. If you're still working on this please push up your work and open a pull request so we can help work through any problems.

**Comment by whoissteven** [comment]
I've worked on this a bit, but I have issues pulling anything from the page.
view-source:https://www.whitecastle.com/locations/ny/huntington-station/540-walt-whitman-rd/340

The <body>doesn't contain html or an iframe that I can work with... thoughts?

**Comment by iandees** [comment]
If you look at the network traffic there are a couple XHR requests being made to an API endpoint when you search the map. Try looking at that endpoint.
