### ISSUE TITLE
Uzbekistan POI Data

### ISSUE THREAD

**Issue by justinelliotmeyers** [alltheplaces/alltheplaces#5465]
### Brand name

Uzbekistan GEONAMES

### Store finder url(s)

https://geonames.kadastr.uz

license: https://creativecommons.org/licenses/by/4.0/

@iandees If there is anyway possible you could grab these, I would really appreciate it. And buy you a beer this summer when back in MSP. Let me know amigo!
Justin

**Comment by justinelliotmeyers** [comment]
@iandees any idea if this is possible? gracias amigo

**Comment by iandees** [comment]
What are they?

**Comment by justinelliotmeyers** [comment]
![IDS](https://github.com/alltheplaces/alltheplaces/assets/5324316/d78d50b0-923c-4d03-b99f-5d99f2f704a9)

Unique ids open up weblinks with maps - which is where your magic would have to come into play to somehow grab the hidden x,y

https://geonames.kadastr.uz/show/921910
https://geonames.kadastr.uz/show/921909

No idea if this is possible or not, but this repo would be the best place to ask I think. And this would be huge for Uzbekistan **WITH A FRIENDLY LICENSE!!

**Comment by iandees** [comment]
I don't see a reference to CC-BY license on the page. Where did you spot that?

**Comment by justinelliotmeyers** [comment]
Main parent webpage (scroll all the way down), where I found their geonames child site!

https://kadastr.uz/

![image](https://github.com/alltheplaces/alltheplaces/assets/5324316/042da746-f88a-4f5b-b6c2-57b07326fe48)

Copyright is my thing - I have to adhere to it daily

**Comment by iandees** [comment]
Nice, thanks for the link.

**Comment by Cj-Malone** [comment]
Unless I'm missing something, I've not actually seen one with coords. The map defaults to 41.31122859768113, 69.26838037276731 but never renders anything.

**Comment by davidhicks** [comment]
> Unless I'm missing something, I've not actually seen one with coords. The map defaults to 41.31122859768113, 69.26838037276731 but never renders anything.

I concur. I can't see evidence of locations having coordinates available to extract.

**Comment by justinelliotmeyers** [comment]
will reach out to their agency and see if they can fix this. until they do, seems like the webpage won't work for this. Thank you all for looking into this.
