### ISSUE TITLE
searchable_points generation

### ISSUE THREAD

**Issue by jimbofreedman** [alltheplaces/alltheplaces#5495]
Hi,

Is the code that was used to generate these available somewhere? I'd like to generate some more and could save a bit of time.

Thanks!

**Comment by jimbofreedman** [comment]
I found the wikidata query

**Comment by iandees** [comment]
Unfortunately we don't have information about how the searchable points were generated. I can probably regenerate something like them, but I don't think we ever got @wessport's readout on how they were made.

**Comment by wessport** [comment]
@iandees apologies missed the earlier tag. 

A short write up on how the points were created would be good. I think I have some notes written down somewhere. I can also generate a new set if that would be helpful. Traveling this week, but will be back in early next week and can write up how the points were generated.

**Comment by jimbofreedman** [comment]
Amazing, thank you!

**Comment by davidhicks** [comment]
I've been working on something similar for the `western_union` spider that needs searchable points across the entire surface of the Earth for 350km radius searches. I've proposed a documented whole-of-Earth searchable points generation method for radius search APIs at https://github.com/alltheplaces/alltheplaces/pull/5509 (using `western_union` as an example consumer).

This proposed icosahedral discrete global grid approach to generating searchable points for radius searches is a bit trickier to apply on a country-by-country level as the software ([DGGRID](https://github.com/sahrk/DGGRID)) only appears to have crude means to optimise the returned searchable points for a small area of the Earth. For example, it is possible to crop a whole-of-Earth list of carefully spaced centroids to just those centroids overlapping a supplied shapefile (shapefile outline of a country). It is also possible to shift all centroids +/- latitude and +/- longitude to find a somewhat optimal overlap of cells over a country, minimising the total number of centroids needed to completely cover a country. This could perhaps be overcome with some scripts that run DGGRID multiple times to shift +/- latitude and +/- longitude and within X attempts, picks the one that results in complete coverage of a country shapefile with the fewest number of centroids required.

**Comment by jimbofreedman** [comment]
#5509 answers my question, thanks

**Comment by davidhicks** [comment]
@jimbofreedman also see https://github.com/alltheplaces/alltheplaces/blob/master/locations/searchable_points/au_centroids_iseadgg_175km_radius.meta for an example of how to generate searchable points for a country code, and https://github.com/alltheplaces/alltheplaces/blob/master/locations/searchable_points/gg_gb_im_je_centroids_iseadgg_48km_radius.meta for multiple country codes.

I'm happy to generate more searchable points as needed just let me know.
