### ISSUE TITLE
Eldrive charging stations

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#5497]
### Brand name

Eldrive

### Wikidata ID

Q120376381

### Store finder url(s)

https://www.google.com/maps/d/u/0/embed?mid=1qSn43vWZ-wVP4x84BGWNba_KaV_qLEQP&ehbc=2E312F&ll=52.06312150131042%2C24.922955749999986&z=4

**Comment by Cj-Malone** [comment]
I'm not going to scrape a Google domain. While I have no doubt it's user generated data, and so should be owned by the user, I expect this to come with drama. Technical or political.

**Comment by Dimitar5555** [comment]
It does come from their website, see https://eldrive.eu/. If that's still a problem, feel free to close the issue.

**Comment by Cj-Malone** [comment]
I don't know if it's a issue for ATP, but personally I'd rather stay away.

**Comment by iandees** [comment]
Yea, I think I'm with you on this, @Cj-Malone.
