### ISSUE TITLE
Suspicious point coordinates from moneygram spider.

### ISSUE THREAD

**Issue by panasonic-mafia** [alltheplaces/alltheplaces#5510]
Found this in alltheplaces.xyz 2023-06-17, `moneygram` spider.

<img width="1281" alt="image" src="https://github.com/alltheplaces/alltheplaces/assets/35237910/fbdccf94-5e1f-46c4-96a5-e24d6982b55c">

**Comment by Cj-Malone** [comment]
Looks like they have there lons copied from lats.
50.867241, 50.867241
50.855583, 50.855583
50.8465, 50.8465
