### ISSUE TITLE
Shell spider returns 0 elements

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#5568]
For the past month the Shell spider has been returning 0 elements.

Spider: https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/shell.py
Finder: https://shellgsllocator.geoapp.me/#/@43.82071,22.04528,4z

**Comment by davidhicks** [comment]
Thanks @Dimitar5555 

I've essentially fixed this in draft PR #5562 for the bp spider which also uses the geo.me store finder, and was broken in a similar way. I plan to change PR #5562 to have a dedicated geo.me store finder which both shell and bp will use.
