### ISSUE TITLE
Missing module typing_extensions, imported by Twisted/Scrapy

### ISSUE THREAD

**Issue by brawer** [alltheplaces/alltheplaces#5584]
Tests on my PR #5583 are currently [failing](https://github.com/alltheplaces/alltheplaces/actions/runs/5666780253/job/15354334218?pr=5583) because of missing module `typing_extensions`, imported by [internet/address.py](https://github.com/twisted/twisted/blob/a9ee8e59a5cd1950bf1a18c4b6ca813e5f56ad08/src/twisted/internet/address.py#L16) in the Twisted library, which is the core foundation of Scrapy. I guess this didn’t trigger before because my PR adds a new library, so I updated`Pipfile.lock`.

What to do? I believe the failure isn’t directly related to my PR, it’ll probably come again as soon as we try updating `Pipfile.lock`.

**Comment by iandees** [comment]
Please make sure you're using Python >= 3.10
