### ISSUE TITLE
How are GeojsonPointItem.opening_hours supposed to be formatted?

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#559]
I seem to have seen several different formats by grepping through `locations/spiders`

**Comment by evanmosseri** [comment]
also, what kind of data is appropriate for `GeojsonPointItem .extras`?

**Comment by Eagle19243** [comment]
@evanmosseri, The opening_hours property should follow the OpenStreetMap opening_hours format. There are examples [in their wiki page](https://wiki.openstreetmap.org/wiki/Key:opening_hours#Examples).

**Comment by evanmosseri** [comment]
Cool, thanks.
