### ISSUE TITLE
Include crawl date in data

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#5658]
I'm looking at an old output directory, trying to workout which release it is.

I think we could add the crawl time and/or build id to the dataset attributes easily.

I think @rjw62 asked for this before. Which I promptly forgot. Sorry.

I'll look at this later or Monday.

**Comment by iandees** [comment]
That's a great idea!

**Comment by Cj-Malone** [comment]
It seems excessively hard to access stats (for `start_time`) or settings (to pass `RUN_TIMESTAMP` from `run_all_spiders.py`) from the exporter.

The easy option is to write the time at the start of the export, but that will actually be slightly after the spider actually starts, and a while after the build id. I'll open a PR tomorrow.
