### ISSUE TITLE
Dia (ES) ~1.7k shop=supermarket

### ISSUE THREAD

**Issue by jimbofreedman** [alltheplaces/alltheplaces#5780]
### Brand name

Dia

### Wikidata ID

Q925132

### Store finder url(s)

https://www.dia.es/tiendas/buscador-tiendas-folletos

**Comment by davidhicks** [comment]
GZIP'd JSON file containing location IDs and coordinates: `https://www.dia.es/clubdia/ES/tiendas.v2031.json.gz`

Then for each location ID, an API request can be made to (for example) `https://www.dia.es/tiendas/buscadorTiendas.html?action=buscarInformacionTienda&id=7817` to return location details.

There doesn't appear to be a webpage specific to each location, hence no mention in the sitemap of location pages.

**Comment by davidhicks** [comment]
GZIP'd JSON file is indeed versioned and now: `https://www.dia.es/clubdia/ES/tiendas.v2034.json.gz`
