### ISSUE TITLE
NatWest (GB) ~600 amenity=bank (also amenity=atm)

### ISSUE THREAD

**Issue by jimbofreedman** [alltheplaces/alltheplaces#5782]
### Brand name

NatWest

### Wikidata ID

Q2740021

### Store finder url(s)

https://www.natwest.com/search-results/locator.html

**Comment by davidhicks** [comment]
This appears to be some crappy custom API in front of Yext (for which we have a store finder). It may be Yext is self-hosted, or they don't expose the API key needed to use `YextSpider`.

The custom API uses the template `https://www.natwest.com/content/natwest_com/en_uk/personal/search-results/locator/jcr:content/master-par/locator/results.blapi.search.json?search_term=BB9%208EH&search_limit=50&search_radius=2500` and increasing the search limit above 50 fails, as does the `offset` parameter that the Yext API usually uses, and other pagination parameters such as `page=`, `search_offset=`, etc.

**Comment by CloCkWeRX** [comment]
https://www.natwest.com/search-results/locator/branch.html?sortcode=600131
https://www.natwest.com/content/natwest_com/en_uk/personal/search-results/locator/branch/jcr:content/master-par/branchdetailshelf/details.blapi.details.json?sortcode=600131


No structured data
