### ISSUE TITLE
Gap

### ISSUE THREAD

**Issue by vikranthkr** [alltheplaces/alltheplaces#579]
http://www.gap.com/customerService/storeLocator.do?mlink=5001,9222156,quickStoreLocator&clink=9222156

http://bananarepublic.gap.com/customerService/storeLocator.do?mlink=5001,9222156,quickStoreLocator&clink=9222156

http://oldnavy.gap.com/customerService/storeLocator.do?kwid=1&sem=false

http://athleta.gap.com/customerService/storeLocator.do?mlink=44913,9016015,TopNav_Store5_4&clink=9016015

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by vikranthkr** [comment]
http://stores.athleta.net
http://www.bananarepublic.com/products/store-locations.jsp
http://www.oldnavy.com/products/store-locations.jsp
http://www.gap.com/products/store-locations.jsp
