### ISSUE TITLE
Barnes and Noble

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#580]
https://stores.barnesandnoble.com/stores?lng=-97.7429885864258&lat=30.2675895690918&searchText=Austin%2c+TX&storeFilter=all&v=1&view=map

I didn't assign myself on purpose this time.

**Comment by MagnetonIO** [comment]
Can I assign my self?

**Comment by evanmosseri** [comment]
If it doesn't have to be approved by @iandees I don't see why not

**Comment by iandees** [comment]
Yes, you can assign yourself.

**Comment by MagnetonIO** [comment]
@iandees 
I updated Qdoba and Tacobel spider already. Can you check them please?
