### ISSUE TITLE
Shell spider doesn't return any results for Bulgaria

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#5818]
There are around 100 Shell gas stations in Bulgaria but none of them are shown in the latest spider result. They are listed on their Bulgarian website (https://www.shell.bg/motorists/shell-station-locator.html).

**Comment by davidhicks** [comment]
The `GeoMeSpider` store finder makes a lot of queries to a common GeoMe API to find locations across the world. This is duplicated for both `shell` and `bp` that are brands using the `GeoMeSpider`.

The `shell` spider is returning a 403 response mid crawl, terminating the crawl before any locations in Europe are found. Reference: https://data.alltheplaces.xyz/runs/2023-09-02-13-32-00/stats/shell.json

The `bp` spider is also returning a 403 response mid crawl. Reference: https://data.alltheplaces.xyz/runs/2023-09-02-13-32-00/stats/bp.json

Perhaps the answer is to try `download_delay=2` or some other number in `storefinders/geo_me.py` in the hope that the 403 response isn't received. And when a 403 response is returned, perhaps it is possible to pause a few minutes (via a handler for the `errback=` parameter) then retry the request.

**Comment by Cj-Malone** [comment]
`AUTOTHROTTLE_ENABLED` should slow down the requests. I don't know if it extends to a few minuets like you question.

https://docs.scrapy.org/en/latest/topics/autothrottle.html#std-setting-AUTOTHROTTLE_ENABLED

**Comment by davidhicks** [comment]
I've got a run going (slowly) with a 0.5 autothrottle and will report back results when available (including total crawl time).

**Comment by davidhicks** [comment]
Finished in 8945 seconds with no errors, and still the same number of locations returned (should be +10000 locations including Europe but these are missing).

I'm debugging now to see what logic is wrong in the spider to cause so much of the world to be missed.
