### ISSUE TITLE
Cricket Wireless

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#584]
https://www.cricketwireless.com/stores.html#/map?woo_campaign=SEM&woo_source=Google_PPC&woo_medium=keyword&woo_content=BND%20Store%20-%20EXM&woo_term=cricket%20wireless%20locator&kid=kwd-145185151253&cid=292853573

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by evanmosseri** [comment]
Will be spending a lot of time hammering out some scripts tonight, reassigning myself for tonight and will unassign myself if I don't complete it by tomorrow morning.
