### ISSUE TITLE
Samsonite spider finds dealers, not official stores

### ISSUE THREAD

**Issue by eisams** [alltheplaces/alltheplaces#5840]
This spider is wrong, e.g., the stores in Norway are not official Samsonite stores but dealers carrying the Samsonite brand

E.g., this is Chillout Travel Store, not a Samsonite store
https://www.alltheplaces.xyz/map/#15.79/59.920398/10.757257

The website does list official stores and dealers separately, so it should be possible to import the right type?
https://www.samsonite.no/samsonite-store/?search=dealer&city=&country=no&lat=59.920469259204786&lng=10.755597088646583&radius=20

_Originally posted by @eisams in https://github.com/alltheplaces/alltheplaces/issues/4385#issuecomment-1586255246_

**Comment by Cj-Malone** [comment]
Would 143 locations sound about right?
