### ISSUE TITLE
Metro PCS

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#585]
https://www.metropcs.com/find-store.html

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by evanmosseri** [comment]
Will be spending a lot of time hammering out some scripts tonight, reassigning myself for tonight and will unassign myself if I don't complete it by tomorrow morning.

**Comment by davidhicks** [comment]
Website is dead, brand can't be found via web search.
