### ISSUE TITLE
DSK Bank

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#5864]
### Brand name

DSK Bank / Банка ДСК

### Wikidata ID

Q5206146

### Store finder url(s)

https://dskbank.bg/контакти/клонова-мрежа/GetOffices/

The type of office is stored in the `BranchType` variable. Some of the offices have lunch breaks which are denoted by `*Почивка`.

**Comment by Exterminator11** [comment]
hey @Dimitar5555, is this issue up for grabs?

**Comment by Dimitar5555** [comment]
Hi @Exterminator11, yes the issue is up for grabs.

**Comment by Exterminator11** [comment]
I am a novice contributor, so if you could explain what the issue expects to be done it would be very helpful.

**Comment by Dimitar5555** [comment]
The goal is to create a spider that gets the coordinates, opening hours, addresses and other information that is in the json file and convert it to All The Places data format. I think that the spider for DSK would be similar to A1 (https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/a1.py). There is more information in [README.md](https://github.com/alltheplaces/alltheplaces/blob/master/README.md) and [DATA_FORMAT.md](https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md).

**Comment by Exterminator11** [comment]
Thank you so much, I'll get to work right away!

**Comment by davidhicks** [comment]
This would be a fairly simple spider, mostly just:

`
start_urls = ["https://dskbank.bg/%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D0%B8/%D0%BA%D0%BB%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0-%D0%BC%D1%80%D0%B5%D0%B6%D0%B0/GetOffices/"]

def parse(self, response):
  for location in response.json():
    item = DictParser.parse(location)
    yield item
`

Then some extra tweaks to extract additional fields from `location` to `item`, and to clean up any messy fields.

**Comment by Exterminator11** [comment]
hey @davidhicks and @Dimitar5555, I was able to come up with a solution would you like me to open up a PR?. This is what the output looks like when I run the file.
<img width="1438" alt="Screenshot 2023-10-01 at 8 40 25 AM" src="https://github.com/alltheplaces/alltheplaces/assets/88940647/5091bba6-559b-4c55-91d4-ecd5d257ac82">

**Comment by davidhicks** [comment]
@Exterminator11 Your output is looking good. Just a few minor suggestions before you send a pull request:

1. Set `name = "dsk_bank_bg"` in class properties, and name the class `DSKBankBGSpider`. `item_attributes` should have `Банка ДСК` as the brand name, and the Wikidata item of `Q5206146`. Additional attributes will be pulled in from `name-suggestion-index` reference https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=dsk
2. Use `apply_category(Categories.BANK, item)` or `apply_category(Categories.ATM, item)` to denote whether the location is a bank branch, ATM, etc.

**Comment by Dimitar5555** [comment]
Resolved by #6006., thanks @Exterminator11!

**Comment by Exterminator11** [comment]
> Resolved by #6006., thanks @Exterminator11!

Happy to have helped!!, couldn't have done it without the support of the great people of this organization😃.
