### ISSUE TITLE
T-Market supermarkets

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#5866]
### Brand name

T-Market

### Wikidata ID

Q64033983

### Store finder url(s)

https://tmarket.bg/sitemap/page/1.xml

Each location has a separate URL that looks like this: `https://tmarket.bg/page/magazin-{shop_name}`. They may have forgotten to put a few dozen closing tags which makes finding the opening hours quite difficult. Having only coordinates would be fine at this stage.

**Comment by CloCkWeRX** [comment]
----
### Brand name

T-Market

Bulgarian supermarket chain

### Wikidata ID

Q64033983
https://www.wikidata.org/wiki/Q64033983
https://www.wikidata.org/wiki/Special:EntityData/Q64033983.json

### Store finder url(s)

Official Url(s): http://www.tmarket.bg/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q64033983 http://www.tmarket.bg/`
```
```

**Comment by CloCkWeRX** [comment]
https://tmarket.bg/page/magazin-gorna-orqhovitsa
No structured data

```
<div class="_text-description">
            <div class="qqvbed-p83tee">
<h3 class="qqvbed-p83tee-lTBxed">Магазин - Горна Оряховица</h3>
<p class="qqvbed-p83tee-lTBxed">Адрес:</p>
<p class="qqvbed-p83tee-lTBxed">Горна Оряховица, ул. Васил Левски 10</p>
</div>
<div class="qqvbed-p83tee">
<div class="qqvbed-p83tee-lTBxed">Телефон на потребителя:</div>
<div class="qqvbed-p83tee-lTBxed">
<div class="phone"><strong>0700 701 71</strong></div>
<div class="phone">&nbsp;</div>
<div class="phone">
<div>Работно време:</div>
<div></div>
<div class="phone">
<div class="_4bl9">
<div id="u_fetchstream_1_1" class="_6a uiPopover openToggler selected">
<div id="u_fetchstream_1_2" class="clearfix _ikh _5jau _p" role="button" aria-haspopup="true" aria-expanded="false" aria-controls="u_fetchstream_1_0">
<div class="_4bl7"><span><strong>Понеделник - Неделя</strong></span></div>
<div class="_4bl7">08:00 ч. - 22:00 ч.</div>
</div>
</div>
</div>
</div>
<div class="phone"></div>
<div class="phone">
<div>Email:</div>
<div class="phone"><span><strong>maxima@maximabulgaria.bg</strong></span></div>
</div>
</div>
</div>
</div>
        </div>
```

**Comment by Dimitar5555** [comment]
If you use innerHTML, you get a bit of structure.

```
Магазин - Горна Оряховица

Адрес:

Горна Оряховица, ул. Васил Левски 10

Телефон на потребителя:
0700 701 71
 
Работно време:
Понеделник - Неделя
08:00 ч. - 22:00 ч.
Email:
maxima@maximabulgaria.bg
```

**Comment by CloCkWeRX** [comment]
I mean more specifically no linked data, rdfa, jsonld, etc - https://validator.schema.org/ surfaces nothing
