### ISSUE TITLE
Provide accuracy info

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#5880]
It would be useful to have notes field that would record

- largest known mistake between real world data and claimed location
- whether there are cases of website listing closed objects as existing
- missing cases of open ones

and record some examples of bad data.

Maybe even provide errata for known mistakes in location data. (I am doing it for bicycle parking data that I am using, see https://codeberg.org/matkoniecz/compare_osm_data_with_geojson/src/branch/master/fix.rb )

This would allow more efficient and accurate use of data: some data is garbage and can be used as vague hints (`amenity=money_transfer`  from `@spider=western_union` POIs look quite bad from quick check), data may have some secondary tags like `name` and `operator` broken, data may roughly locate shop but misplace it to the middle of the road or next building, data may be ideally accurate) and so on.

It would also allow to record that spider got broken and data is stale.

It is necessary to check it anyway before using data, so recording it centrally looks like a good idea to me.

Even info that noone checked quality of some data is useful.

**Comment by Cj-Malone** [comment]
We can't document every source error in code. There is way to many. https://osm.mathmos.net/chains/source-errors.html

It's my personal opinion that anyone using the output should conflate the OSM, with OSM taking priority/overriding ATP.

Documenting that some spiders have known issues makes sense to me. eg adding `confidence:geometry=x` in `dataset_attributes` for one where we know it sucks. If we have data on a POI level it could be added to the POI.

**Comment by matkoniecz** [comment]
> We can't document every source error in code. There is way to many. https://osm.mathmos.net/chains/source-errors.html

I would not say in code, I would rather see it as some separate dataset. If this data would be used it would be necessary to do this anyway, for example collect cases of zombie shops that exist only in source data not in reality.

It seems to me that having central location for that rather than everyone rolling own solution would make sense.

**Comment by brawer** [comment]
Curious, how would we know ground truth? The upstream chain might be wrong, or OSM might be wrong, or both. How does Chain Reaction do this?

**Comment by matkoniecz** [comment]
> how would we know ground truth?

On-the-ground verification by trustworthy OSM mappers? Depending on planned scale of ATP it may be not viable.

Also, Bing streetview/Mapillary verification may be possible.

Note that I am not thinking about verifying all cases. 

But making possible to add note like "there was trustworthy report that entries in this dataset are sometimes misplaced, with errors reaching 1200m, see -link to specific location-" to warn potential users of data.

**Comment by Cj-Malone** [comment]
> How does Chain Reaction do this?

@rjw62 will know the specifics, but as far as I'm aware: Some like "Postcode Errors", "Missing Location Coordinates" will be generated automatically. "Significant Location Offsets" is distance between the source and OSM. OSM match being exact `website` or `brand:wikidata` with in x meters. I assume "Fascia Errors" and "Zombie Entries" are completely manual.

I have access to another of Robert Whittakers tools where some trusted users can flag things as gone permanently/temporally.

**Comment by rjw62** [comment]
re Chain Reaction: That's basically right. The things flagged at https://osm.mathmos.net/chains/source-errors.html are either automatically detected from the source data, or the result of manually flagging by me. The postcode errors are manual corrections that I've applied to the source data (usually prompted the source containing an invalid or non-existent  postcode). Matches to OSM are based on the OSM object having the correct brand:wikidata tag and being close enough to the source position. I don't currently look at the website tags for this, but I think a correct postcode may allow a greater distance apart.

**Comment by matkoniecz** [comment]
https://github.com/alltheplaces/alltheplaces/issues?q=is%3Aopen+is%3Aissue+label%3A%22Data+limitation%3A+wildly+inaccurate+coordinates%22 label seems related but unused

**Comment by matkoniecz** [comment]
I will open more specific PR at some point, and keep submitting PRs fixing what can be fixed on ATP side
