### ISSUE TITLE
Stop proposing to add company logo as an image tag

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#5882]
See

https://www.alltheplaces.xyz/map/#16.82/50.072221/20.041573

![screen01](https://github.com/alltheplaces/alltheplaces/assets/899988/46772969-5a13-4a19-9b09-3eb5bde7a36f)

that adds no real value.

**Comment by Cj-Malone** [comment]
We try to collect images, unfortunately lots of sites lie and call the logo an image.

Ideally we'd be able to detect these automatically an remove the logos. Or move them to a different tag. For now, the we have to remove the image on some spiders.

https://validator.schema.org/#url=https%3A%2F%2Flocal.fedex.com%2Fen-us%2Fmn%2Ftruman%2Fmktbf

Similarly we sometimes get brand level social media tags, and occasionally brand level website. I'd like to move these into fields like `brand:facebook`. We can do this easily and automatically if we pull in Wikidata.

**Comment by matkoniecz** [comment]
I would argue that `image` tag also is not worth much anyway. Or is it intended not to be imported as OSM tag but as help for verification etc?

**Comment by Cj-Malone** [comment]
Images are very useful for end users viewing POIs. The OSM community find value in [adding images to POIs](https://wiki.openstreetmap.org/wiki/Key:image).

> proposing to add

It might be worth pointing out, ATP exists in it's own right. I want it to be used by the OSM community, but OSM not the only user.

**Comment by matkoniecz** [comment]
> I want it to be used by the OSM community, but OSM not the only user.

Oh, sorry. I am trying to understand better how this project works but I was unaware of that part. Is there some explanation/vision for this project that I can read to be less confused?

**Comment by jleedev** [comment]
In this particular example, there are many thousand unique `name` values, but only 21 unique `image` values, and they indicate "Office", "Ship Center", "Authorized ShipCenter", and the like.

Sure, the spider could probably be improved to locate that value more precisely than by hardcoding an image URL lookup table, but there's definitely a useful signal there. I agree that this project does not only exist to provide importable data to OSM; as another example `cvs_us` encodes `departments` and `store_type` to somewhat capture the nature of the location (is it inside a supermarket, can they do vaccines, etc.) which is somewhat messy in the source data and somewhat messy to map to OSM but nonetheless valuable, without having to additionally contort the output to fit OSM norms.

**Comment by jleedev** [comment]
To state the obvious, "why should this feature have an image?" Because the website contains unambiguous, machine readable RDF stating as such.

The "name" property of many locations is just as often something weird and incompatible with OSM, but it is much more maintainable to use the sitemap + structured data combo with as little custom modification as possible — essentially, giving the start URL, brand Wikidata, and that's it.

**Comment by Cj-Malone** [comment]
> For something actionable: maybe files with `logo` in name can be skipped in general?

Sounds reasonable, if implemented as a pipeline we could disable on specific spider if it was causing trouble.

> Hmmm, maybe common repeated `image` values can be detected. Real images will repeat only rarely.

Because of how scrapy works, we can't edit previous items, but if we say any images with more than x occurrences get dropped from the future POIs. Only the first x POIs would get the bad image.

I don't have a major argument against this. Especially if we did some logging so they could then be fixed in spider code.

> In this particular example, there are many thousand unique `name` values, but only 21 unique `image` values, and they indicate "Office", "Ship Center", "Authorized ShipCenter", and the like.

This sounds like the best answer for FedEx. If you are still busy I can take a look at the specifics later this week.

> The "name" property of many locations is just as often something weird and incompatible with OSM,

This is on my TODO list. Actually I wrote a little bit of code. But I want to test it on a previous weekly before a PR.

> but it is much more maintainable to use the sitemap + structured data combo with as little custom modification as possible — essentially, giving the start URL, brand Wikidata, and that's it.

Eg https://github.com/alltheplaces/alltheplaces/pull/5078/files

**Comment by matkoniecz** [comment]
> Because of how scrapy works, we can't edit previous items, but if we say any images with more than x occurrences get dropped from the future POIs. Only the first x POIs would get the bad image.

I thought rather about some report based on scrapped data, for review and potential inclusion on a ban list. Or is it to labour-intensive give ATP scale?

**Comment by jleedev** [comment]
It would probably be best to do this on an individual basis, e.g.

```
northwest_bank.py
    # Image is just the svg logo, ignore it
    del item["image"]
```

As noted above, scrapy runs through each scraped item independently. But it's straightforward to download the latest tarball and identify those files where all the values are identical, and then start submitting pull requests.

**Comment by jleedev** [comment]
For what it's worth, I am mildly negative on this codebase correlating with NSI and adding additional tags such as `amenity=restaurant` and so on, as it clutters the actual scraped output. The brand_wikidata should be sufficient.

**Comment by matkoniecz** [comment]
> The brand_wikidata should be sufficient.

What about cases when single brand operates distinct POIs?

**Comment by jleedev** [comment]
Looks like there is some matching logic that attempts to find the correct `nsi_id` based on the presence of any top-level category tags: https://github.com/alltheplaces/alltheplaces/blob/a0bc9ae0f99026e6235a4e71a1b70d83231c3f5c/locations/categories.py#L6-L12

Pretty reasonable. I am just questioning the utility of adding, e.g. `cuisine=sandwich` + `takeaway=yes` to every individual Subway location, beyond merely stating that the preset was successfully matched.

**Comment by Cj-Malone** [comment]
`cuisine` is basically mandatory for a category, at least in my mind. I know it's not in OSM land.

I could agree with `takeaway`, but I don't want to get in the business of which tags we take from NSI, and which we ignore. It's not worth it. And I think the consumers would do it anyway, so it adds value to ATP.

**Comment by Cj-Malone** [comment]
> In this particular example, there are many thousand unique `name` values, but only 21 unique `image` values, and they indicate "Office", "Ship Center", "Authorized ShipCenter", and the like.
> 
> Sure, the spider could probably be improved to locate that value more precisely than by hardcoding an image URL lookup table, but there's definitely a useful signal there.

Unfortunately `https://local.fedex.com/permanent-b0b701/assets/images/logo.2a392863.png` fucks it up and is used across categories.

I wrote the following mess before noticing:
```python
        image = item.pop("image")
        item["extras"]["type"] = image  # DEBUG: remove after someone has validated the below
        if image == "https://dynl.mktgcdn.com/p/8WjhQotIsbSZbCVeZGIRwOdN8wywnr-li_0rrKqvjGg/150x150.jpg":
            item["located_in"] = item.pop("name").replace("FedEx at ", "")
            apply_category({"post_office": "post_partner"}, item)
        elif image == "https://local.fedex.com/permanent-b0b701/assets/images/logo.2a392863.png":
            # TODO:
            apply_category({"post_office": "post_partner"}, item)
        elif image in [
            "https://dynl.mktgcdn.com/p/xr4KIXJyrI7mLDfTQ_N7sj307bDhWS0-Iru_r0Y5uOw/150x150.png",
            "https://dynl.mktgcdn.com/p/PFax364A7l9w6MV-uPQSNg4ydyUPd3uLJQO0TDCUTdo/150x150.png",
        ]:
            item["located_in"] = item["name"].replace("FedEx Authorized ShipCenter ", "")
            item["name"] = "FedEx Authorized ShipCenter"
            apply_category({"post_office": "post_partner"}, item)
        elif image == "https://dynl.mktgcdn.com/p/p4QLbd5TrIHVqq8XA3z9-mUTA2CgEwmHjpL3ucaTMnI/150x150.png":
            item["name"] = "FedEx Office Ship Center"
            apply_category({"post_office": "post_partner"}, item)
        elif image == "https://dynl.mktgcdn.com/p/abqUEmAWWhDygw_o8g_5DXA-jZhPYGmvxw7xIhBYkwU/1.0000/150x150.png":
            item["name"] = "FedEx Ship Center"
            apply_category(Categories.POST_OFFICE, item)
        elif image == "https://dynl.mktgcdn.com/p/_RHBdXdIAO4wQ2H0isBpcTuoEf8w6mE7o2AXEQ2nAfE/150x150.png":
            apply_category(Categories.POST_OFFICE, item)
        elif image == "https://dynl.mktgcdn.com/p/maqqGsdssxpL0YBOZRp28_qRkQy_m9ew4gFj7MTct0o/150x150.jpg":
            apply_category(Categories.POST_DEPOT, item)
        elif image == "https://dynl.mktgcdn.com/p/VqBHEoSSU6V8w4XRNlATQp_rpi8m4E5wAFunpRhELY8/150x150.jpg":
            item["name"] = "FedEx Office Print & Ship Center"
            apply_category(Categories.SHOP_COPYSHOP, item)
        else:
            self.crawler.stats.inc_value("atp/fedex/unmapped_category/{}".format(item["image"]))
```
