### ISSUE TITLE
@spider=zabka_pl opening hours are missing Sunday data, proposed `opening_hours` are broken

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#5888]
https://www.alltheplaces.xyz/map/#16.47/50.073227/20.037421

![screen](https://github.com/alltheplaces/alltheplaces/assets/899988/a19656c7-65ad-4db2-8907-b5e0f2186f26)

https://www.openstreetmap.org/node/4271289403

Opening hours in OSM (`Mo-Sa 06:00-22:00; Su 11:00-20:00`) are correct.

At https://www.zabka.pl/znajdz-sklep it refuses to show Sunday opening hours.

Maybe it is caused by their internal structure? This shops are franchises and maybe they are obligated to be open `Mo-Sa 06:00-22:00` and Sundays can be decided by operator?

Overall it seems that Monday to Saturday data is likely correct.

**Comment by Cj-Malone** [comment]
> Maybe it is caused by their internal structure? This shops are franchises and maybe they are obligated to be open `Mo-Sa 06:00-22:00` and Sundays can be decided by operator?

https://github.com/alltheplaces/alltheplaces/blob/a0bc9ae0f99026e6235a4e71a1b70d83231c3f5c/locations/spiders/zabka_pl.py#L30-L35

https://github.com/alltheplaces/alltheplaces/pull/5586

Sounds like you and @alufers agree, and it sounds like at least some of them have Sunday hours available. It would be nice to collect them, especially when all the Sundays in `nonTradingDays` agree.

**Comment by matkoniecz** [comment]
Not entirely sure what should be done?

Ideally parsing `nonTradingDays` would be nice, but not sure what should be done with shops missing it. Are they closed on Sundays? Missing data and their opening hours should be skipped?

For now I would propose to not emit any opening hours rather than known incomplete ones.

**Comment by Cj-Malone** [comment]
> For now I would propose to not emit any opening hours rather than known incomplete ones.

Interesting, we don't actually output `Su off`. But I acknowledge, in reality, OSM doesn't differentiate. We also don't output any PH data, anyone conflating with OSM should take that into account.

For this specific spider, currently 262 are missing (length 0) `nonTradingDays`, 9,365 have it. Ideally someone with knowledge of the chain could work out if the 262 are closed on Sunday, or missing data.

More than 9,000 currently have the same `nonTradingDays` opening hours, we can collect them. But what happens near Christmas? I imagine that number will be a lot lower, I wouldn't want you to update OSM then.
