### ISSUE TITLE
Good Lood (small scale chain, no Wikidata entry)

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#5897]
### Brand name

Good Lood

### Wikidata ID

does not have one

### Store finder url(s)

https://goodlood.com/en

I looked at https://github.com/alltheplaces/alltheplaces/blob/master/docs/PULL_REQUEST.md  and CONTRIBUTING.MD does not exists, and this one is kind of probe: are you accepting also small chains?

Or would I need to anyway run a separate project to support small chains or individual non-chain shop (in such cases monitoring and parsing opening hours data is still helpful)

**Comment by Cj-Malone** [comment]
There are spiders for small chains. I think it's a bit of a waste of time, but I still write some.

[Data](https://mobile.goodlood.com/loodspots) looks quite accessible so it shouldn't be too much trouble.

Do you want to have a go for this one?

**Comment by matkoniecz** [comment]
> Do you want to have a go for this one?

I can do this, but no promises about doing it soon (my next planned step is to try to use some `opening_hours` ATP data)
