### ISSUE TITLE
Orlen amenity=parcel_locker (9699 POIs)

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#5898]
### Brand name

Orlen

### Wikidata ID

Q110457879

### Store finder url(s)

https://www.orlenpaczka.pl/pokaz-punkty/

Note that Orlen fuel station spider exists already

**Comment by davidhicks** [comment]
I think the brand is meant to be Q110457879 (Orlen Paczka) instead of Q971649 (Orlen). Looks simple to implement as all results returned with a single request to `https://ruch-osm.sysadvisors.pl/api.php`

**Comment by matkoniecz** [comment]
switched to Q110457879 - I was unaware that someone bothered to consider it as a separate brand
