### ISSUE TITLE
Delikatesy Centrum (1471 POIs)

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#5910]
### Brand name

Delikatesy Centrum

### Wikidata ID

Q11693824

### Store finder url(s)

https://www.delikatesy.pl/sklepy - note that one in South America, it is clearly misplaced

**Comment by davidhicks** [comment]
All locations returned via `https://www.delikatesy.pl/_next/data/8y1sYoIBRkA8Q7yTv3U32/sklepy.json`

There is a possibility that 8y1.. string changes regularly.
