### ISSUE TITLE
Inpost parcel lockers (>22 000 POIs)

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#5912]
### Brand name

Inpost

### Wikidata ID

Q3182097

### Store finder url(s)

https://inpost.pl/en/find-location

**Comment by davidhicks** [comment]
JSON object parser needed for `https://inpost.pl/sites/default/files/points.json` which returns all locations.

The field names are minimised and obscured but it looks fairly simple to figure it out.

**Comment by davidhicks** [comment]
t=1 for parcel lockers (Categories.PARCEL_LOCKER) and t=2 for parcel pickup locations (Categories.PRODUCT_PICKUP)
