### ISSUE TITLE
I&G Brokers

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#5916]
### Brand name

I&G Brokers

### Wikidata ID

Q110399829

### Store finder url(s)

https://iandgbrokers.com/offices/pins?srch_offices=&city=&features[]=all&_=1695470505675

**Comment by Arshad-Ali-1a** [comment]
Hey @Dimitar5555, I would like to work on this..

**Comment by Dimitar5555** [comment]
Hey @Arshad-Ali-1a, feel free to do so.
