### ISSUE TITLE
Microsoft Store

### ISSUE THREAD

**Issue by josh0203e** [alltheplaces/alltheplaces#593]
https://www.microsoft.com/en-us/store/locations/all-locations

**Comment by evanmosseri** [comment]
Are there a minimum number of locations necessary for us to be able to scrape a site?

**Comment by josh0203e** [comment]
Sure. Did you check the url? We can get the Microsoft stores

**Comment by evanmosseri** [comment]
sorry if I wasn't clear, my question was whether or not we were supposed to crawl sites with relatively few locations

**Comment by iandees** [comment]
No minimum.
