### ISSUE TITLE
A1 Croatia

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#5962]
### Brand name

Q688755

### Wikidata ID

A1

### Store finder url(s)

https://www.a1.hr/prodajna-mjesta?p_p_id=pos_WAR_pos&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=searchPos&p_p_cacheability=cacheLevelPage

There is data that needs to be sent via a POST request to the same url (`query=&tipprikaza=lista&types=center&types=partner`), otherwise no results are returned. I'm not sure how their partners operate and whether there are actual A1 stores there or the partners offer limited A1 services.

**Comment by davidhicks** [comment]
`curl 'https://www.a1.hr/prodajna-mjesta?p_p_id=pos_WAR_pos&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=searchPos&p_p_cacheability=cacheLevelPage' -X POST -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data-raw 'query=&tipprikaza=lista&types=center&types=partner'`

From the results, only `type="center"` should be extracted.
