### ISSUE TITLE
A1 North Macedonia

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#5963]
### Brand name

A1

### Wikidata ID

Q24589907

### Store finder url(s)

https://www.a1.mk/poddrska/prodazni-mesta

There is a `select` element with `id=select-city`. From there we take all values and send them one by one to `https://www.a1.mk/o/StoreFinder-portlet/rest/api/shops/city/{city_id}`. They have a very nice machine readable format for opening hours and they even have `workingDuringHolidays`.

**Comment by davidhicks** [comment]
I think you can obtain a list of all shops (including opening hours) via:

`https://www.a1.mk/o/StoreFinder-portlet/rest/api/shops/`

80 results returned. Is that all?

**Comment by Dimitar5555** [comment]
I think so. A1 is quite rare to find even in Bulgaria. There are very few shops outside of the top 4 cities by population.
