### ISSUE TITLE
addr:state for Orlen in Poland are (1) in wrong language (2) not needed

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#5967]
`addr:state=Lesser Poland Voivodeship` in Poland is (1) not needed, we are not using it as part of address in general (2) if at all present, it should be in Polish

![screen03](https://github.com/alltheplaces/alltheplaces/assets/899988/8743e553-a3f7-49cb-b750-1eafed9d239d)

**Comment by iandees** [comment]
We're capturing the data as we get it from the website, so there's not much for us to do here.

We have talked about normalizing addresses, but we don't have plans to do it right now. Also, I don't know that it would solve the language problem. Maybe if we found a way to normalize to an abbreviation?
