### ISSUE TITLE
@spider=shell - internal names in `name` tag

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#5969]
like  #5968

`name=7315 KRAKOW SLIWKOWA.` is not correct, it is at most some `ref`

https://www.alltheplaces.xyz/map/#18.48/50.0726652/20.0190363

**Comment by Cj-Malone** [comment]
You are making the assumption that ATP `name` is OSMs `name`. It's closer to a label right now. I'd like to get ATP closer to OSM, and have discussed multiple times eg #4772 #5899 making a new issue for every spider isn't going to help the situation.

**Comment by matkoniecz** [comment]
> You are making the assumption that ATP `name` is OSMs `name`. 

Yes.

So it would be better to close that issue, right?

**Comment by iandees** [comment]
Yep, let's continue the discussion about this on #4772.
