### ISSUE TITLE
Starwood Hotels

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#6]
HTML hotel directory: http://www.starwoodhotels.com/corporate/directory/hotels/all/list.html?language=en_US

**Comment by nicolas17** [comment]
That page has links to each country, then links to each state/province/thing, then the list of hotels there.

It may be easier to extract the whole list from the map page: https://www.starwoodhotels.com/preferredguest/directory/hotels/all/map.html

`ul#resultsPrimary` has a `li` for each hotel. I'm not sure if it has *all* the info you want though. Also note that map.html redirects to a mobile page if it doesn't think your user-agent is a desktop.

**Comment by vlad555** [comment]
When I requested data by scraper, it redirected by site to mobile version at another domain
https://assistive.usablenet.com/tt/www.starwoodhotels.com/preferredguest/directory/hotels/all/map.html?sortType=region&un_jtt_redirect
There are all data on one page
Can I use these data? or I should scrype it from genuine site (will forbid redirection)

**Comment by nicolas17** [comment]
As I said in my comment, you need to change the user agent. After some more testing: if I send a desktop web browser user agent (such as mine `Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0`) or a user agent containing the word 'bot' (`AllThePlacesBot/1.0` works!), then you don't get the redirect.

I'll let you figure out how to change the user agent in scrapy 😀

**Comment by vlad555** [comment]
I understood it at once.
But I found simplest way to get information. 
Just want to ask is it possible to get information by that way.
If not, I'll do as it necessary
Ok
