### ISSUE TITLE
Sunglass Hut (various countries)

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#6003]
### Brand name

Sunglass Hut

### Wikidata ID

Q136311

### Store finder url(s)

https://mena.sunglasshut.com/api/content/render/false/limit/9999/type/json/query/+contentType:SghStoreLocator%20+languageId:11%20+deleted:false%20+working:true/orderby/modDate%20desc

Covers countries:
* Algeria
* Bahrain
* Cyprus
* Egypt
* Jordan
* KSA
* Kuwait
* Lebanon
* Oman
* Qatar
* UAE

Netherlands: https://nl.sunglasshut.com/api/content/render/false/limit/9999/type/json/query/+contentType:SghStoreLocator%20+languageId:3%20+deleted:false%20+working:true/orderby/modDate%20desc

Portugal: https://pt.sunglasshut.com/api/content/render/false/limit/9999/type/json/query/+contentType:SghStoreLocator%20+languageId:4%20+deleted:false%20+working:true/orderby/modDate%20desc

Turkey: https://tr.sunglasshut.com/api/content/render/false/limit/9999/type/json/query/+contentType:SghStoreLocator%20+languageId:4%20+deleted:false%20+working:true/orderby/modDate%20desc

Hong Kong: https://hk.sunglasshut.com/api/content/render/false/limit/9999/type/json/query/+contentType:SghStoreLocator%20+languageId:8%20+deleted:false%20+working:true/orderby/modDate%20desc

**Comment by davidhicks** [comment]
Covers countries:
* Algeria
* Bahrain
* Cyprus
* Egypt
* Jordan
* KSA
* Kuwait
* Lebanon
* Oman
* Qatar
* UAE

**Comment by davidhicks** [comment]
Other countries using the same API:

Netherlands: https://nl.sunglasshut.com/api/content/render/false/limit/9999/type/json/query/+contentType:SghStoreLocator%20+languageId:3%20+deleted:false%20+working:true/orderby/modDate%20desc

**Comment by Arshad-Ali-1a** [comment]
Hey @davidhicks , I would love to implement this..

**Comment by davidhicks** [comment]
Do you want to have a go at writing this spider? I can add it to my TODO list otherwise.

**Comment by Arshad-Ali-1a** [comment]
> Do you want to have a go at writing this spider? I can add it to my TODO list otherwise.

Ya, I will have a go at it.

**Comment by Arshad-Ali-1a** [comment]
@davidhicks 
[sunglass_hut.py](locations/spiders/sunglass_hut.py) already exists for AU, CA, GU, NZ, PR, US, VI.
So, Shall I name the one I am implementing as sunglass_hut_it.py?

**Comment by davidhicks** [comment]
I think the existing `sunglass_hut` could be renamed to `sunglass_hut_1` and this new spider named `sunglass_hut_2`? I can't see any logical grouping of countries for each spider to be able to suffix with `_europe` or `_apac` or similar.

**Comment by davidhicks** [comment]
Note that the countries of [sunglass_hut.py](https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/sunglass_hut.py) have their own separate API to the countries referred to in this issue #6003. The other API looks a bit like:
```
https://www.sunglasshut.com/AjaxSGHFindPhysicalStoreLocations?latitude=-37.8152065&longitude=144.963937&radius=100&langId=-26&storeId=11351
```

And you need to change the coordinates and `storeId` to match a location within each country, and then also specify the `radius` differently per country (some countries allow a larger radius than other countries).

I didn't create an issue to switch [sunglass_hut.py](https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/sunglass_hut.py) to use the new API. A problem for another day :)

**Comment by Arshad-Ali-1a** [comment]
Hey @davidhicks, should the `item["opening_hours"]` be a **string** like `"Mo-Su 10:00-22:00"`  (by applying the [as_opening_hours](https://github.com/alltheplaces/alltheplaces/blob/master/locations/hours.py#L533C20-L533C20) function), or an **OpeningHours  object** like `<locations.hours.OpeningHours object at 0x7ff8347224a0>`?
Thanks.

**Comment by davidhicks** [comment]
@Arshad-Ali-1a alwaus set/return an `OpeningHours` object. I can't think of any situation where it would be necessary to call `as_opening_hours`.

**Comment by Arshad-Ali-1a** [comment]
> @Arshad-Ali-1a always set/return an `OpeningHours` object. I can't think of any situation where it would be necessary to call `as_opening_hours`.

I will make the necessary changes to the PR

**Comment by iandees** [comment]
> @Arshad-Ali-1a always set/return an `OpeningHours` object. I can't think of any situation where it would be necessary to call `as_opening_hours`.

For further context, the system will automatically call `as_opening_hours()` for you if it detects an `OpeningHours` object as a value in the properties of the item.
