### ISSUE TITLE
Kik: Missing lots of locations

### ISSUE THREAD

**Issue by hfs** [alltheplaces/alltheplaces#6007]
The Kik spider in kik.py is missing a lot of locations.

Here I’ve compared them to GMaps. All the red ones are potentially missing.

![Map comparing Kik locations from ATP vs GMaps](https://github.com/alltheplaces/alltheplaces/assets/538109/012a7d30-da1a-4436-9fbe-496097cedf31)

I think the problem could be that their API `https://storefinder-microservice.kik.de/storefinder/results.json?lat={lat}&long={lon}&country={country}&distance=130` doesn’t actually return all results in a 130 km radius, but limits them to the 20 nearest results.

When it gets called with the 120 km search grid, lots of gaps remain where their shops are denser.

**Comment by davidhicks** [comment]
Thanks for reporting.

`https://storefinder-microservice.kik.de/storefinder/results.json?lat=50&long=9&country=DE&distance=10000&limit=10000` returns 2470 locations in a single request. Easy fix :)
