### ISSUE TITLE
National Trust

### ISSUE THREAD

**Issue by jimbofreedman** [alltheplaces/alltheplaces#6028]
### Brand name

National Trust

### Wikidata ID

Q333515

### Store finder url(s)

https://www.nationaltrust.org.uk/api/search/places?query=sw6%203er&placeSort=distance&lat=51.4672197&lon=-0.1925168&milesRadius=10000&pageStartIndex=0&pageSize=10000&lang=en&publicationChannel=NATIONAL_TRUST_ORG_UK&maxPlaceResults=1000&maxLocationPageResults=0
(returns 598 results)
or
https://www.nationaltrust.org.uk/sitemap.xml

**Comment by Exterminator11** [comment]
hey @davidhicks and @jimbofreedman , can I work on this issue?
