### ISSUE TITLE
`easypay_bg.py` - foreign offices are marked as located in Bulgaria

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#6032]
EasyPay seems to have some offices outside of Bulgaria (1 in Austria, 5 in Greece and 14 in Cyprus), but all of them have `addr:country=BG`.

**Comment by Arshad-Ali-1a** [comment]
@Dimitar5555 As there are only some EasyPay offices outside Bulgaria, should we just hardcode the countries, or apply reverse geocoding of coordinates?

**Comment by Dimitar5555** [comment]
How would you hardcode the countries? There is no information in which country each office is. 

The best solution (that I can think of right now) would be to mark offices with postcode (4th column) with `addr:country=BG` and reverse geocode all other coordinates.

**Comment by Arshad-Ali-1a** [comment]
oh, ya that is good. Reverse geocode would have to run only 20 times.
I will implement this..

**Comment by brawer** [comment]
The pipeline already runs an offline reverse geocoder using [this code here](https://github.com/alltheplaces/alltheplaces/blob/master/locations/pipelines/country_code_clean_up.py), so it might be enough to set some properties on the spider.

**Comment by Arshad-Ali-1a** [comment]
> EasyPay seems to have some offices outside of Bulgaria (1 in Austria, 5 in Greece and 14 in Cyprus), but all of them have `addr:country=BG`.

CORRECTION:
BG-3267
RO-24
CY-14
GR-10
MK-3
AT-1
