### ISSUE TITLE
Stamen tiles won't be available after October 31

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#6034]
![image](https://github.com/alltheplaces/alltheplaces/assets/19364673/0cb2d25f-8c25-47ca-a779-402ca2fd306e)

These tiles are used in `https://alltheplaces.xyz/map.html`.

More information is available on https://maps.stamen.com/stadia-partnership/.

**Comment by davidhicks** [comment]
Perhaps switch to self-hosted pmtiles e.g. https://protomaps.com/docs/downloads/basemaps ?

`/ci/run_all_spiders.sh` already generates pmtiles for locations so some precedent has been set already.

**Comment by iandees** [comment]
I switched over to OSM tiles for now.

I'm working with @bdon to get a protomaps vector tile solution working, so I'll leave this open.

**Comment by iandees** [comment]
I updated to use Protomaps' API and Maplibre. Looks pretty good!
