### ISSUE TITLE
Texcycle shoes and clothes containers

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#6039]
### Brand name

Texcycle

### Wikidata ID

Q85614408

### Store finder url(s)

https://texcycle.bg/bin-locations-list/

The descriptions in the table are more detailed, the ones in the map popups seem to be automatically generated.

**Comment by davidhicks** [comment]
Can you provide a better translation of what is contained in the popups/table beneath the map?

For example, "ОБОРИЩЕ &#8211; ул. Каймакчалан, вляво от входа на МОЛ Сердика" via Google Translate is "MANURE &#8211; Kaymakchalan St., to the left of the Serdika MALL entrance"

Quite a few locations are prefixed "ОБОРИЩЕ" (and I doubt Google is correct in translating this to animal poop... but who am I to know) which I suspect indicates a province/state name?

The only information that seems to be available for each location is coordinates and this string that appears to be freeform text directions for how to get to the location by road.

**Comment by Dimitar5555** [comment]
> Can you provide a better translation of what is contained in the popups/table beneath the map?

The popups on the map contain text like "ул. „Генерал Иван Пашинов“ 14, 6014 Железник, Стара Загора, България", which can be translated to "14 General Ivan Pashinov Str., Zheleznik quarter, Stara Zagora, Bulgaria, post code 6014".

The text in the table shows a shorter address (street + street number, the city name is above the table) along with data about where exactly the container is located ("on the parking", "right of building entrance", "next to underpass near building 20").

> For example, "ОБОРИЩЕ – ул. Каймакчалан, вляво от входа на МОЛ Сердика" via Google Translate is "MANURE – Kaymakchalan St., to the left of the Serdika MALL entrance"

> Quite a few locations are prefixed "ОБОРИЩЕ" (and I doubt Google is correct in translating this to animal poop... but who am I to know) which I suspect indicates a province/state name?

Thank you for the laugh with that translation :D. "Оборище" means barnyard (i.e. the place where a village's barns are located). The name is related to the April Uprising of 1876 (see https://en.wikipedia.org/wiki/Oborishte_locality for more info). In this case, it's the city district name (as well as all other words in caps). I don't think that it's important for ATP.

> The only information that seems to be available for each location is coordinates and this string that appears to be freeform text directions for how to get to the location by road.

We are talking about containers which are located outdoors. I'm not sure if there is any other information about them that could be useful.

**Comment by davidhicks** [comment]
Thank you that is very helpful!

Are these points clothing/shoe donation bins where you can drop off only? e.g. https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling

Or can you drop off and pick up clothing/shoes from these containers? e.g. https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgive_box

**Comment by Dimitar5555** [comment]
It's drop off only. I've added it in NSI with `amenity=recycling + recycling:clothes=yes + recycling:shoes=yes`.
