### ISSUE TITLE
DSV Locker parcel lockers (ZA)

### ISSUE THREAD

**Issue by arrival-spring** [alltheplaces/alltheplaces#6045]
### Brand name

DSV Locker

### Wikidata ID

Q1155771

### Store finder url(s)

https://dsvdirect.co.za/dsv-locker/#Locator (457 lockers)

**Comment by davidhicks** [comment]
A single API call to the following URL returns all location data as a JSON object:

`https://dsv-clientzone-map.afrigis.co.za/proxy/api/wfs/?layer=locker`

**Comment by davidhicks** [comment]
Currently 263 features are available to extract.

**Comment by Arshad-Ali-1a** [comment]
So, data of only 263 lockers has to be extracted?
I would love to implement this..
