### ISSUE TITLE
Odido (PL)

### ISSUE THREAD

**Issue by starsep** [alltheplaces/alltheplaces#6050]
### Brand name

Odido

### Wikidata ID

Q106947294

### Store finder url(s)

https://www.sklepy-odido.pl/znajdz-sklep

**Comment by davidhicks** [comment]
Single API call to the following URL returns all location data as a JSON object:

`https://www.sklepy-odido.pl/api/shops?itemsPerPage=10000`

**Comment by davidhicks** [comment]
Note there are no unique references I can see for each store, but the API returns an index for each store that could possibly be used (unsure of whether these indexes are stable for each store).

**Comment by davidhicks** [comment]
Currently 1664 features are available to extract.
