### ISSUE TITLE
Pick n Pay (Southern African supermarket chain)

### ISSUE THREAD

**Issue by arrival-spring** [alltheplaces/alltheplaces#6052]
### Brand name

Pick n Pay

### Wikidata ID

Q7190735

### Store finder url(s)

https://www.pnp.co.za/store-locator

Supermarkets, convenience stores and clothing stores

SUPER: shop=supermarket
HYPER: shop=supermarket
LOCAL: shop=convenience
FAMILY: shop=supermarket
EXPRESS: shop=convenience, Q122764443
MINI: shop=convenience
MARKET: don't know
WHOLESALE: shop=wholesale
BOXER SUPERSTORE: shop=supermarket, Q116586275
BOXER BUILD: shop=doityourself, Q122766671
BOXER LIQUOR: shop=alcohol, Q122766666
DC (Distribution Centre)
BOXER: shop=supermarket, Q116586275
BPFORECOURT: shop=convenience
LIQUOR: shop=alcohol, Q122764458
PHARMACY: listed in dropdown, but no such stores
CLOTHING: shop=clothes, Q122964352

**Comment by davidhicks** [comment]
A single API call to `https://api.pnp.co.za/stores/v2` returns all location data as a JSON blob. Currently 2479 features are available to extract.

**Comment by CloCkWeRX** [comment]
https://github.com/alltheplaces/alltheplaces/discussions/6918 you may also be interested in, I'm not a local so don't quite get the relationship to boxer, etc

**Comment by Firefishy** [comment]
This can likely be closed now that code merged.
