### ISSUE TITLE
Ruby Tuesday

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#6145]
### Brand name

Ruby Tuesday

### Wikidata ID

Q7376400

### Store finder url(s)

https://www.rubytuesday.com/locations/

**Comment by davidhicks** [comment]
Sitemap: https://www.rubytuesday.com/sitemap.xml

Then for each `/locations/` URL (per location) some HTML parsing is required to extract location information.

**Comment by sterojos** [comment]
All data is in a JS blob on the store finder page.

**Comment by CloCkWeRX** [comment]
Closable?
