### ISSUE TITLE
Rotten Robbie

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#6181]
### Brand name

Rotten Robbie

### Wikidata ID

Q87378070

### Store finder url(s)

https://www.rottenrobbie.com/locations-2/

**Comment by davidhicks** [comment]
`https://rocketstores.com/wp-json/stations/v1/locations?MinLong=-128.42634771874998&MaxLong=-107.55232428125&MinLat=31.420274450318118&MaxLat=35.90778546631802` returns location information for 313 stations.

**Comment by davidhicks** [comment]
All 37 locations appear to be returned via `https://www.rottenrobbie.com/wp-json/wpgmza/v1/features/base64eJyrVkrLzClJLVKyUqqOUcpNLIjPTIlRsopRMoxRqlWqBQCnUQoG`
