### ISSUE TITLE
Rocket

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#6182]
### Brand name

Rocket

### Wikidata ID

Q121513516

### Store finder url(s)

https://rocketstores.com/rocket-stations/

**Comment by davidhicks** [comment]
`https://rocketstores.com/wp-json/stations/v1/locations?MinLong=-128.42634771874998&MaxLong=-107.55232428125&MinLat=31.420274450318118&MaxLat=35.90778546631802` returns location information for 313 stations.
