### ISSUE TITLE
Frys

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#619]
https://www.frys.com/ac/storeinfo/austin-location-frys-electronics-hours-maps-directions

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by evanmosseri** [comment]
Will be spending a lot of time hammering out some scripts tonight, reassigning myself for tonight and will unassign myself if I don't complete it by tomorrow morning.
