### ISSUE TITLE
Ace Hardware

### ISSUE THREAD

**Issue by ianmcorvidae** [alltheplaces/alltheplaces#62]
http://www.acehardware.com/mystore/storeLocator.jsp

**Comment by whoissteven** [comment]
Interesting.
http://www.acehardware.com/acestoresitemap.xml
Can pull URLS from there.
When on store page however, using xpath or css the values are never what they should be. Checking source they change. Will come back to this.

**Comment by iandees** [comment]
Removing the assignee on this because there's been no update for 5 days.
