### ISSUE TITLE
Bass Pro Shops

### ISSUE THREAD

**Issue by DerekMcDaniel** [alltheplaces/alltheplaces#631]
https://stores.basspro.com/

**Comment by DerekMcDaniel** [comment]
working on this

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by DerekMcDaniel** [comment]
Hey @iandees just noticed this. I completed the bass pro spider and it was merged 15 days ago

**Comment by iandees** [comment]
Great, thanks for the reminder @DerekMcDaniel.

**Comment by DerekMcDaniel** [comment]
No problem. @iandees  should I have been adding, in example, Fixes: '#(number)'? to my pull requests?

**Comment by iandees** [comment]
Yep, but I never really asked anyone to do it so I was adding it myself. Clearly I missed a few.

**Comment by DerekMcDaniel** [comment]
Ok thanks, I'll do that next time :)
