### ISSUE TITLE
yettel_bg is broken

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#6323]
The spider does not return anything. It seems like they've moved the page for getting their store data. I wasn't able to find the new address or how the data reaches their store locator page.

Store locator: https://www.yettel.bg/faq/digital-customer-service/store-locator

Spider: https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/yettel_bg.py

**Comment by Dimitar5555** [comment]
There is an Excel file (https://www.yettel.bg/dA/1d9e589cca/) that has everything we need. Is there a way to parse it?

**Comment by brawer** [comment]
[openpyxl](https://openpyxl.readthedocs.io/en/stable/) is pretty good at parsing Excel files
