### ISSUE TITLE
Starbucks 

### ISSUE THREAD

**Issue by skorasaurus** [alltheplaces/alltheplaces#64]
On mobile, so didn't find an endpoint yet

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by Cj-Malone** [comment]
This can be closed. There is a Starbucks and Starbucks EU scraper.

**Comment by skorasaurus** [comment]
there is! thanks for pointing it out - https://github.com/alltheplaces/alltheplaces/blob/6737cea2da20a2e05a0f3d4619df352d6c7f933b/locations/spiders/starbucks.py
