### ISSUE TITLE
AWS Access Denied Error for Geojson Files?

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#642]
https://s3.amazonaws.com/placescraper-results/results/farmers_insurance/2017-12-21-02-04-53/output.geojson

**Comment by iandees** [comment]
This was a problem I introduced in #638 and fixed in #643. It should be better now.

**Comment by iandees** [comment]
It was causing no geojson to be created, so it's not going to fix URLs that are broken right now. You'll have to rebuild stuff to get a working URL.
