### ISSUE TITLE
Wiener Wald

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#651]
Restaurant/fast food in Europe.

http://www.wienerwald.eu/restaurants/deutschland

**Comment by davidhicks** [comment]
No store locator or other location information found at wienerwald.de

[Wikipedia states](https://en.wikipedia.org/wiki/Wienerwald_(restaurant)):
_As of 2022 there are five Wienerwald restaurants in Germany and three in Egypt_
