### ISSUE TITLE
bupa_gb spider is including closed branches

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#6562]
The bupa_gb.py spider is returning a number of closed practices, as these still have web pages and are still listed in the sitemap. Current examples include:

https://www.bupa.co.uk/dental/dental-care/practices/harleston
https://www.bupa.co.uk/dental/dental-care/practices/leckhampton

I think these can be reliably detected by checking if the name ends (case-insensitively) with "closed". So I'd suggest we drop any whose name matches /closed$/i. There are about 12 of these in total out of 388 branches.

(Sorry, I can no longer run the code on my computer to implement and test this myself, since I'm unable to install a recent enough version of Python.)

**Comment by Cj-Malone** [comment]
I've flagged them as closed in #6564 in the method that was discussed for Wilko in #6042 (`end_date=yes`). TT has a strong preference for flagging these, not removing them so they can remove the closed POIs from other datasets.
