### ISSUE TITLE
H&M

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#659]
Clothing store.

They're in multiple countries, but here's the US store locator: https://www.hm.com/us/store-locator

**Comment by evanmosseri** [comment]
Figured out how to get stores from all countries.

**Comment by SelfnessAid** [comment]
@evanmosseri @iandees 
I am getting error in this Spider after pull last master branch.
```
import requests
import itertools
```

_ModuleNotFoundError: No module named 'requests'_

I need to install this package on my local side?

**Comment by evanmosseri** [comment]
I didn't end up using requests, you can just delete that import
