### ISSUE TITLE
Pague Menos (Brazilian pharmacy/chemist)

### ISSUE THREAD

**Issue by matheusgomesms** [alltheplaces/alltheplaces#6602]
Not sure how this works, but let me start with a big pharmacy company in Brazil, with over 1000+ stores. Complete data, with addresses (addr:street, addr:housenumber, addr:postcode, addr:city and addr:state) and phone number. Each location has a single URL too.

### Brand name

Pague Menos

### Wikidata ID

Q7124466

### Store finder url(s)

https://www.paguemenos.com.br/nossas-lojas

**Comment by Cj-Malone** [comment]
Unfortunately they don't have coords, addresses, phone numbers and urls are available though. [Example data](https://pmenos.paguemenos.com.br/wp-json/wp/v2/lojas?per_page=1&page=1&order=asc)

**Comment by matheusgomesms** [comment]
Such a pity! Not sure, but it seems, looking now at their source code, that they do geocoding on the fly with GMaps... Well, #6603 will be great anyway, thanks a lot!

**Comment by davidhicks** [comment]
> Such a pity! Not sure, but it seems, looking now at their source code, that they do geocoding on the fly with GMaps... Well, #6603 will be great anyway, thanks a lot!

Unfortunately it is a fairly common problem that brands use Google Maps with place IDs (Google proprietary IDs similar to OpenStreetMap node/way/relation IDs) or postal addresses.

Perhaps [OpenAddresses](https://openaddresses.io/) could be integrated with ATP for geocoding in the future?
