### ISSUE TITLE
MediaMarkt

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#661]
http://www.mediamarkt.com/

They're in multiple countries. It'd be great to get them all.

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by davidhicks** [comment]
Completed per 568c061a85232c9e4d39c9209aca2b616d85dc3f
