### ISSUE TITLE
Le Crobag

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#664]
Fast food bakery.

http://www.lecrobag.de/en/shops.html

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by davidhicks** [comment]
Completed per 25bc847e1fe3061d0f02a33d134b634d34e18d2e
