### ISSUE TITLE
Kamps Bakery

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#665]
Bakery in Germany

https://kamps.de/en/company/bakery-backstube-search

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by davidhicks** [comment]
Completed per 98b1a8da0200174b17884c9d2adf29917c58bb9b
