### ISSUE TITLE
A Pea in the Pod

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#668]
https://stores.apeainthepod.com/?page=1&storesPerPage=12

**Comment by davidhicks** [comment]
Liquidated in 2019 per https://www.bizjournals.com/bizwomen/news/latest-news/2019/10/destination-maternity-files-for-bankruptcy.html

Whilst the brand was acquired and website available at https://www.apeainthepod.com there is no evidence of physical stores existing in 2023 on the website.
