### ISSUE TITLE
Second Cup

### ISSUE THREAD

**Issue by brianbancroft** [alltheplaces/alltheplaces#67]
http://www.secondcup.com/find-a-cafe

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by davidhicks** [comment]
CrawlSpider of `https://secondcup.com/trouver-un-cafe/` and then HTML parsing of individual store pages such as `https://secondcup.com/location/braeside-shopping-centre/`, which contain additional detail not on the store list page such as opening hours.

I couldn't find any coordinates available to extract for each location. The sitemap `https://secondcup.com/sitemap_index.xml` was also not loading for me (timeout).

**Comment by CloCkWeRX** [comment]
StructuredDataSpider
