### ISSUE TITLE
Ibis Hotels

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#671]
http://www.ibis.com/gb/world/hotels-ibis-monde.shtml

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by davidhicks** [comment]
Ibis is included in parent brand's `accor` spider.
