### ISSUE TITLE
Caffe Nero GB spider using outdated JSON file

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#6729]
The caffe_nero_gb.py spider gets its data from JSON file that the Store Finder page at https://caffenero.com/uk/stores/ uses to display its map. However, it looks like that URL of that JSON file has changed, and ATP is still referencing the old (and no longer updated one).

The ATP code currently has
`allowed_domains = ["caffenero-webassets-production.s3.eu-west-2.amazonaws.com"]`
`start_urls = ["https://caffenero-webassets-production.s3.eu-west-2.amazonaws.com/stores/stores_gb.json"]`
But the URL referenced by https://caffenero.com/uk/stores/ is now
https://caffenerowebsite.blob.core.windows.net/production/data/stores/stores-gb.json

I think the format of the JSON file has remained the same, so it should just be a matter of swapping the URLs over.

To help issues like this be picked up sooner in the future, I wonder if there's a way of checking that the JSON URL used is still included in the https://caffenero.com/uk/stores/ page, and producing a warning to anyone running ATP if not?

**Comment by Cj-Malone** [comment]
> To help issues like this be picked up sooner in the future, I wonder if there's a way of checking that the JSON URL used is still included in the https://caffenero.com/uk/stores/ page, and producing a warning to anyone running ATP if not?

In my PR I collected the json url from the live page, if the page is updated the spider should break or collect the new data.
