### ISSUE TITLE
Ross Dress for Less

### ISSUE THREAD

**Issue by ianmcorvidae** [alltheplaces/alltheplaces#68]
https://www.rossstores.com/store-locator?source=main-nav

**Comment by iandees** [comment]
No progress for 5 days, re-opening this for others.

**Comment by AnthoneyKalasho** [comment]
According to the Ross website there are 1412 stores. The following request returns up to 1000 locations, so by requesting data for two points on opposite sides of the country and removing duplicates I should be able to get most locations.

[Link](https://hosted.where2getit.com/rossdressforless/2014/ajax?&xml_request=%3Crequest%3E%3Cappkey%3E1F663E4E-1B64-11E5-B356-3DAF58203F82%3C%2Fappkey%3E%3Cformdata+id%3D%22locatorsearch%22%3E%3Cdataview%3Estore_default%3C%2Fdataview%3E%3Climit%3E99999%3C%2Flimit%3E%3Cgeolocs%3E%3Cgeoloc%3E%3Clongitude%3E-98.5795%3C%2Flongitude%3E%3Clatitude%3E39.8283%3C%2Flatitude%3E%3C%2Fgeoloc%3E%3C%2Fgeolocs%3E%3Csearchradius%3E4000%7C250%3C%2Fsearchradius%3E%3Cwhere%3E%3Cclientkey%3E%3Ceq%3E%3C%2Feq%3E%3C%2Fclientkey%3E%3Copendate%3E%3Ceq%3E%3C%2Feq%3E%3C%2Fopendate%3E%3Cshopping_spree%3E%3Ceq%3E%3C%2Feq%3E%3C%2Fshopping_spree%3E%3C%2Fwhere%3E%3C%2Fformdata%3E%3C%2Frequest%3E)
