### ISSUE TITLE
Jamba Juice

### ISSUE THREAD

**Issue by ianmcorvidae** [alltheplaces/alltheplaces#69]
http://www.jambajuice.com/find-a-store

**Comment by kristinepetrosyan** [comment]
@iandees How would it be best to approach this issue?

**Comment by kristinepetrosyan** [comment]
I found http://locations.jambajuice.com/site-map but it needs a token to get the data.

**Comment by iandees** [comment]
It looks like that token sticks around between page loads. You can probably use it for this spider.

**Comment by kristinepetrosyan** [comment]
curl 'https://momentfeed-prod.apigee.net/api/llp.json?auth_token=PQUBOCBNLKOUIYUP&country=US&sitemap=true'
ok cool. Thanks a lot @iandees
