### ISSUE TITLE
Snap Fitness

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#690]
https://www.snapfitness.com/gyms

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by davidhicks** [comment]
Australia:
JSON response with all locations: `https://www.snapfitness.com/au/api/location-finder-edge`

Belgium:
JSON response with all locations: `https://www.snapfitness.com/be/api/location-finder-edge`

Canada:
JSON response with all locations: `https://www.snapfitness.com/ca/api/location-finder-edge`

Spain:
JSON response with all locations: `https://www.snapfitness.com/es/api/location-finder-edge`

Hong Kong:
JSON response with all locations: `https://www.snapfitness.com/hk/api/location-finder-edge` or `https://www.snapfitness.com/hk_en/api/location-finder-edge`

Indonesia:
JSON response with all locations: `https://www.snapfitness.com/id/api/location-finder-edge` or `https://www.snapfitness.com/id_en/api/location-finder-edge`

Ireland:
JSON response with all locations: `https://www.snapfitness.com/ie/api/location-finder-edge`

Japan:
CrawlSpider needed for start URL: `https://www.snapfitness.jp/locations/`

Mexico:
JSON response with all locations: `https://www.snapfitness.com/mx/api/location-finder-edge`

Netherlands:
JSON response with all locations: `https://www.snapfitness.com/nl/api/location-finder-edge`

New Zealand:
JSON response with all locations: `https://www.snapfitness.com/nz/api/location-finder-edge`

Philippines:
JSON response with all locations: `https://www.snapfitness.com/ph/api/location-finder-edge`

Saudi Arabia:
JSON response with all locations: `https://www.snapfitness.com/sa_en/api/location-finder-edge`

Singapore:
JSON response with all locations: `https://www.snapfitness.com/sg/api/location-finder-edge`

Taiwan:
JSON response with all locations: `https://www.snapfitness.com/tw/api/location-finder-edge`
