### ISSUE TITLE
Anthropologie spider produces transposed coordinates

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#6909]
https://www.alltheplaces.xyz/map/#7.69/-75.171/39.95

![image](https://github.com/alltheplaces/alltheplaces/assets/365751/549c74f8-f0ee-437d-aad5-b6c56cb747fb)

The cause is the upstream data:

https://www.anthropologie.com/stores/rittenhouse-square-philadelphia
![image](https://github.com/alltheplaces/alltheplaces/assets/365751/688ab3b4-18ed-435b-a6e1-733784d4c9a7)

It might be worth doing any of the following:

- Suspend the lat/long from the parser for now
- Contact the company (I'll probably do that shortly) about the bug
- Any kind of high level validations that can check the expected bounds for a scraper, vs the results?

**Comment by Cj-Malone** [comment]
We can switch them in the spider, it's possiby as easy as:
```python
    def pre_process_data(self, ld_data, **kwargs):
        ld_data["geo"]["latitude"], ld_data["geo"]["longitude"] = ld_data["geo"]["longitude"], ld_data["geo"]["latitude"]
```
I can't test right now as my VPN is broken, I'll take a look soon unless someone else does first.

> Contact the company (I'll probably do that shortly) about the bug

I don't have any positive experiences doing that, trying to find the right person is impossible. Good luck though, and if you manage, tell me your secrets! :)

> Any kind of high level validations that can check the expected bounds for a scraper, vs the results?

hmm, not currently.

**Comment by Cj-Malone** [comment]
I've flipped the coords. If you manage to make contact and they fix it, we'll need to remove the hack. Until then, we should have good coords now :) thank you.
