### ISSUE TITLE
Bike Totaal (shop/bicycle)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#6922]
### Brand name

Bike Totaal

Dutch bicycle retail chain

### Wikidata ID

Q123536506
https://www.wikidata.org/wiki/Q123536506
https://www.wikidata.org/wiki/Special:EntityData/Q123536506.json

### Store finder url(s)

https://www.biketotaal.nl/fietsenwinkels (js blob - script id="NEXT_DATA" type="application/json")

Official Url(s): https://www.biketotaal.nl/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q123536506 https://www.biketotaal.nl/`
```
```

**Comment by davidhicks** [comment]
147 (seemingly all) results returned with a POST to:

```https://txqn75ks6l-2.algolianet.com/1/indexes/*/queries?x-algolia-agent=Algolia for JavaScript (4.20.0); Browser (lite); instantsearch.js (4.60.0); react (18.3.0-canary-09285d5a7-20230925); react-instantsearch (7.3.0); react-instantsearch-core (7.3.0); next.js (13.5.4); JS Helper (3.15.0)&x-algolia-api-key=7b238970f2f25648d04318c495206253&x-algolia-application-id=TXQN75KS6L```

With search parameters:
```{"requests":[{"indexName":"live_nl_stores","params":"analytics=true&aroundLatLng=52.7712587%2C6.235939999999999&aroundRadius=1000000&facets=%5B%5D&getRankingInfo=true&hitsPerPage=1000&tagFilters="}]}```
