### ISSUE TITLE
Pure Barre

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#693]
http://purebarre.com/locations/

**Comment by kristinepetrosyan** [comment]
@iandees I dont see hours for this one.

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by davidhicks** [comment]
Single API call to `https://members.purebarre.com/api/brands/purebarre/locations?open_status=external` appears to return all location data in JSON format.
