### ISSUE TITLE
Add attribution to CI map

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#6932]
> [122 items](https://alltheplaces-data.openaddresses.io/ci/7699308566/activ_fitness_ch/output.geojson) ([Map](https://alltheplaces-data.openaddresses.io/map.html?show=https://alltheplaces-data.openaddresses.io/ci/7699308566/activ_fitness_ch/output.geojson))

That map is awesome, but needs [attribution](https://wiki.openstreetmap.org/wiki/Community_attribution_advice).

_Originally posted by @habi in https://github.com/alltheplaces/alltheplaces/issues/6927#issuecomment-1915385170_

**Comment by CloCkWeRX** [comment]
https://www.alltheplaces.xyz/map/#1/0/0
+
https://alltheplaces-data.openaddresses.io/map.html seem correct now - closable?

**Comment by iandees** [comment]
Yep, looks good.
