### ISSUE TITLE
Distinguish parsed opening hours and partially parsed opening hours

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#6943]
Opening hours range from tame to horrifyingly complex. The same goes for their representation.

Parsing may work fine, fail silently or fail with known problems.

First two cases are not really distinguishable by processing (that is why silent failures are irritating).

Currently when ATP processing fails to process one of days, it just does not show opening hours for it - turning known parsing failure into failing silently.

This is problematic for some uses of ATP data - for example where it would be imported into OSM.

Maybe marking failed parsing can be done somehow? Without that users need to assume that any value can be only partially parsed. With marking users could have greater (but not full!) confidence in ATP processing.

Some ideas from #6933:

`Mo-Tu 08:00-16:00; We open; Th-Fr 08:00-16:00; ...` where Wednesday is known to be open but exact parsing failed.

`Mo-Tu 08:00-16:00; We "parsing failed" Th-Fr 08:00-16:00; ...`

Add `fixme=yes fixme:opening_hours=parsing_failed` or `suspect_data=yes` or `low_quality:opening_hours=parsing_partially_failed` or `quality:opening_hours=parsing_partially_failed`

Or maybe put into `partially_parsed_opening_hours` not into `opening_hours` ?

**Comment by davidhicks** [comment]
I think we'd need new methods such as `OpeningHours.set_days_open(days: list[str], reason: ReasonForNoHoursRange)` and `OpeningHours.set_days_closed(days: list[str])` to allow spiders to specify explicitly whether a location is open (but exact hours not known) or closed on a particular day? The `ReasonForNoHoursRange` Enum could have values such as `NOT_SPECIFIED_BY_SOURCE`, `SOURCE_DATA_ERROR`, ...?

And where did we land on locations which brands may have designated as `Opening soon on 1/1/2025!` or `Temporarily closed for refurbishment until 1/1/2025`? The opening hours string format seemingly allows for specifying `2024 Jan-Dec closed; 2025 Jan-Dec open;`

If when `OpeningHours.as_opening_hours()` is called there are days of the week with no hours specified, should they be output as e.g. `We open` or just keep status quo that no mention of Wednesday would be made in the output string?

**Comment by matkoniecz** [comment]
> And where did we land on locations which brands may have designated as Opening soon on 1/1/2025! or Temporarily closed for refurbishment until 1/1/2025? The opening hours string format seemingly allows for specifying 2024 Jan-Dec closed; 2025+ Jan-Dec open;

No idea, but from perspective of someone interested in importing this to OpenStreetMap it would be nice to not get it unexpectedly and have clear distinction of currently existing shop and not actually currently existing shops.

Maybe it could be in form of distinct main key using namespacing? `future:shop=whatever` instead of `shop=whatever` ?

This way in such cases `opening_hours` can have some exotic content with lower risk of problems appearing.

**Comment by iandees** [comment]
Can you share a couple examples that you've noticed where opening hours aren't what you expect due to ATP parsing failures?

If we're going to the trouble of adding something like `quality:` prefix tagging to each spider, why not just fix the opening hours parsing instead? They seem like similar amounts of work.

**Comment by Cj-Malone** [comment]
#5888 wasn't saying `Su off` or `Su closed`...

**Comment by iandees** [comment]
ATP shouldn't "partially" parse hours, but it's possible that ATP produces incomplete or inaccurate data because of a bug or a data source omission. If we become aware of a bug in the ATP spider, we should fix it. If we become aware of a data source omission, we shouldn't output incomplete/inaccurate data (preferably as narrowly as possible - i.e. only skip outputting on a single feature when we know it's wrong). Note that it's hard to know when these things happen, so there's no programmatic way we can go validate all this stuff.

I disagree that your example is an ATP parsing error. It's potentially a data source error, and ATP does its best to get it right given the information it has.

**Comment by iandees** [comment]
OSM behaves the same way, by the way. Mappers are humans and can misinterpret or miss a day of opening hours when mapping in person. In that case, someone comes along and fixes it.

**Comment by matkoniecz** [comment]
> but it's possible that ATP produces incomplete or inaccurate data because of a bug or a data source omission.

Maybe I misunderstood situation, but I thought that there are cases where data source is too complex/confusing and in such case part of opening hours info is silently omitted

> I disagree that your example is an ATP parsing error. It's potentially a data source error, and ATP does its best to get it right given the information it has.

https://github.com/alltheplaces/alltheplaces/issues/5888 included case where ATP was not parsing Sunday data at all and was claiming that store is closed on Sunday (by not emitting any data for Sunday)

Data source included this data and it was not parsed by ATP and https://github.com/alltheplaces/alltheplaces/pull/5890/files fixed it by parsing it

(data was in weird format which is a separate issue)

**Comment by iandees** [comment]
> Maybe I misunderstood situation, but I thought that there are cases where data source is too complex/confusing and in such case part of opening hours info is silently omitted

I'm not aware of any of spider that does this on purpose.

> https://github.com/alltheplaces/alltheplaces/issues/5888 included case where ATP was not parsing Sunday data at all and was claiming that store is closed on Sunday (by not emitting any data for Sunday)
> 
> Data source included this data and it was not parsed by ATP and https://github.com/alltheplaces/alltheplaces/pull/5890/files fixed it by starting to parse it

I think what I said holds true in this case: We shouldn't output known-incorrect or known-incomplete data (the same concept with different words). If we do and we notice it, we should fix that by not outputting the data or by fixing the parsing. 

In this case we spotted an error and fixed it.

**Comment by matkoniecz** [comment]
> I'm not aware of any of spider that does this on purpose.

In such case that was based on misunderstanding and confusion and this is not needed (as cases where processing is doing it by accident would not be helped or detected by such change, this would only help with spiders deliberately doing this or which were known to do this)

**Comment by iandees** [comment]
I concede that I might have merged spiders that took shortcuts on particularly hard opening hours, but if I did that was a mistake and we should fix situations like that.

The suggestion for describing our certainty on particular tags like `opening_hours` is good, but I'd rather tackle it by removing questionable data than adding complexity for data consumers.

**Comment by matkoniecz** [comment]
and for future maybe such half done (or just not doable ones) can put their data into `partially_parsed_opening_hours` or similar to not trap people?
