### ISSUE TITLE
Micromania (FR) (shop/video_games) (314 stores)

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#6993]
### Brand name

Micromania

### Wikidata ID

Q3312221

### Store finder url(s)

https://www.micromania.fr/on/demandware.store/Sites-Micromania-Site/default/Stores-FindStoresLocator?radius=3000&postalCode=*

**Comment by CloCkWeRX** [comment]
----
### Brand name

Micromania-Zing

video games and cultural products

### Wikidata ID

Q3312221
https://www.wikidata.org/wiki/Q3312221
https://www.wikidata.org/wiki/Special:EntityData/Q3312221.json

### Store finder url(s)

https://www.micromania.fr/magasins?mode=viewAll

Official Url(s): https://www.micromania.fr/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [x] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q3312221 https://www.micromania.fr/`
```
```
