### ISSUE TITLE
New Hampshire Liquor & Wine Outlets (US) (shop/alcohol) (65 stores)

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#7021]
### Brand name

New Hampshire Liquor & Wine Outlets

### Wikidata ID

Q98400557

### Store finder url(s)

https://www.liquorandwineoutlets.com/api/checkout/carts_storelist

**Comment by CloCkWeRX** [comment]
Oops!
```
<Message>An error has occurred.</Message>
<ExceptionMessage>The 'ObjectContent`1' type failed to serialize the response body for content type 'application/xml; charset=utf-8'.</ExceptionMessage>
<ExceptionType>System.InvalidOperationException</ExceptionType>
```

**Comment by CloCkWeRX** [comment]
https://www.liquorandwineoutlets.com/store-locator requests the above as type: application/json, so perhaps that's the missing part

**Comment by davidhicks** [comment]
Yep you're right.

This works:
```curl -H "Accept: application/json" https://www.liquorandwineoutlets.com/api/checkout/carts_storelist```

Just need to override `start_requests` to `yield JsonRequest(url=start_urls[0])`
