### ISSUE TITLE
Pick n Pay brands (ZA) (shop/supermarket, others) (2485 stores)

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#7026]
### Brand name

Pick n Pay (various brands), Boxer (various brands), others

### Wikidata ID

Q7190735, Q116586275, various others needed

### Store finder url(s)

https://api.pnp.co.za/stores/v2

See list of subordinate brands and official store location counts at https://www.picknpayinvestor.co.za/financials/annual-reports/2018/our-footprint-and-formats.php

Note that the API results return `storeType=bpforecourt` which is probably in addition to these counts and from the name appears to be BP branded fuel stations.

**Comment by CloCkWeRX** [comment]
https://github.com/alltheplaces/alltheplaces/issues/6052 duplicate?

**Comment by davidhicks** [comment]
Duplicate of #6052
