### ISSUE TITLE
Can I use Python's requests library for a synchronous http request?

### ISSUE THREAD

**Issue by evanmosseri** [alltheplaces/alltheplaces#708]
I need to fetch a list of states and a list of hash values in the `__init__` method in order to scrape a site efficiently and therefore need to make a synchronous request before the asynchronous crawler starts. Since there are two resources that I am fetching, I can't just add it to start_urls

**Comment by iandees** [comment]
You should be able to do this with existing Scrapy functionality and without using `requests`. Can you point to the spider and problem you're running into?

**Comment by evanmosseri** [comment]
Nevermind, I figured a way around it for this site.
