### ISSUE TITLE
Chipotle

### ISSUE THREAD

**Issue by ianmcorvidae** [alltheplaces/alltheplaces#71]
http://chipotle.com/locations/

**Comment by sweetdream0729** [comment]
working on this

**Comment by iandees** [comment]
No progress for 6 days, re-opening this for others.

**Comment by vlad555** [comment]
As I can't find flat listing of shops I can purpose to make several requests(7) with 800mi range
Is it acceptable?
![image](https://user-images.githubusercontent.com/9920034/34030374-79b77626-e121-11e7-9f77-77cd72da5a3f.png)

**Comment by iandees** [comment]
Yes, that's ok.

**Comment by vlad555** [comment]
I'm sorry, i found the scriper already done by somebody.
Nice to know he used same logic I going to use :-)

**Comment by iandees** [comment]
Dupe of #205
