### ISSUE TITLE
Cycle Spot (JP) (shop/bicycle) (WPStoreLocator) (More than 100 bicycle specialty stores in the Kanto area)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7124]
### Brand name

Cycle Spot

Japanese cycling company

### Wikidata ID

Q93620124
https://www.wikidata.org/wiki/Q93620124
https://www.wikidata.org/wiki/Special:EntityData/Q93620124.json

### Store finder url(s)

https://www.cyclespot.net/shops-list

Official Url(s): https://www.cyclespot.net/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q93620124 https://www.cyclespot.net/`
```

from locations.storefinders.wp_store_locator import WPStoreLocatorSpider


class CycleSpotJPSpider(WPStoreLocatorSpider):
        name = "_jp"
        item_attributes = {
                "brand_wikidata": "Q93620124",
                "brand": "サイクルスポット",
        }
        allowed_domains = [
                "www.cyclespot.net",
        ]
```

**Comment by CloCkWeRX** [comment]
Requires a different approach:
https://github.com/alltheplaces/alltheplaces/pull/7132

**Comment by davidhicks** [comment]
Can alternatively be implemented with a CrawlSpider starting at https://www.cyclespot.net/shops-list plus HTML extraction of each location page (example: https://www.cyclespot.net/shops/cyclespotooi/)
