### ISSUE TITLE
Jacques’ Wein-Depot (DE) (shop/wine) (100+ locations)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7184]
### Brand name

Jacques’ Wein-Depot

German wine store chain

### Wikidata ID

Q1678150
https://www.wikidata.org/wiki/Q1678150
https://www.wikidata.org/wiki/Special:EntityData/Q1678150.json

### Store finder url(s)

https://www.jacques.de/weindepots
https://www.jacques.de/sitemap.xml
https://www.jacques.de/weindepot/D025/Bielefeld-Babenhausen

Official Url(s): https://www.jacques.de/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q1678150 https://www.jacques.de/`
```
```

----

**Comment by davidhicks** [comment]
1. Search https://www.jacques.de/weindepots for something similar to `<script src="[main.18490de1fe72ffeb.js](view-source:https://www.jacques.de/main.18490de1fe72ffeb.js)" type="module"></script>`
2. Load main.???.js
3. Extract the API key from within: `,xApiKeyCommerce:"3ktDIbM06aHMAbGRA1y3NSBpVSuoCUtq",`
4. Get an authorization bearer token: `curl -X POST -H "x-api-key: {key_extracted_in_step_3}" https://commerce.api.jacques.de/authentication/v1/anonymous`
5. Request list of locations: `curl 'https://commerce.api.jacques.de/depot/v1/locations' -H 'Accept: application/json' -H 'Accept-Language: de-DE' -H 'x-api-key: {key_extracted_in_step_3}' -H 'Authorization: Bearer {token_returned_in_step_4}'`
6. For each location, request details: `curl 'https://commerce.api.jacques.de/depot/v1/depot/D005' -H 'Accept: application/json' -H 'Accept-Language: de-DE' -H 'x-api-key: {key_extracted_in_step_3}' -H 'Authorization: Bearer {token_returned_in_step_4}'`
7. Use `DictParser.parse` and tidy up results. Opening hours are included.

**Comment by CloCkWeRX** [comment]
Added location url to wikidata
