### ISSUE TITLE
Loblaws & Superstore & Thirfty Foods & Fairway's Market & Safeway & Save on Foods & Farmboy

### ISSUE THREAD

**Issue by brianbancroft** [alltheplaces/alltheplaces#72]
- [x] [Loblaws](https://www.loblaws.ca/store-locator)
- [ ] [Superstore](https://www.realcanadiansuperstore.ca/store-locator)
- [ ] [Thrifty Foods](https://www.thriftyfoods.com/find-a-store)
- [ ] [Fairways](http://www.fairwaymarkets.com/index.php/store-locations)
- [ ] [Safeway](https://www.safeway.ca/find-a-store)
- [ ] [Save on Foods](https://shop.saveonfoods.com/chain/8E4E398?hash=locator&_ga=1.168908327.789228674.1484454975)
- [ ] [Farm Boy](https://www.farmboy.ca/about-us/stores/)

**Comment by iandees** [comment]
Going to clear the assignee on this so others can work on it. If you're still working on it, please re-assign to yourself and push up what you've got so far.

**Comment by iandees** [comment]
These should all be broken out into their own tickets. A lot of them have already been done.

**Comment by sweetdream0729** [comment]
working on this.

**Comment by sweetdream0729** [comment]
@iandees , I think this issue should be opened for other stores.
Thanks.

**Comment by sweetdream0729** [comment]
@iandees , Safeway of this issue has a different domain with #311 .
https://www.safeway.ca/find-a-store
So I am going to create one for above URL.
Thanks.
