### ISSUE TITLE
Godiva Chocolatier (Multiple counties) (shop/chocolate)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7278]
### Brand name

Godiva Chocolatier

Turkish owned Belgian chocolaterie

### Wikidata ID

Q931084
https://www.wikidata.org/wiki/Q931084
https://www.wikidata.org/wiki/Special:EntityData/Q931084.json

### Store finder url(s)

https://shop.godiva.co.jp/stores
https://godiva.com.au/pages/stores
Many others probably

Official Url(s): https://www.godiva.co.jp/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q931084 https://www.godiva.co.jp/`
```
```
Official Url(s): http://www.godiva.com
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q931084 http://www.godiva.com`
```
```

**Comment by davidhicks** [comment]
https://stockist.co/api/v1/u17509/locations/all for Australia

**Comment by davidhicks** [comment]
`curl 'https://shop.godiva.co.jp/api/delivery/stores/search/' -X POST -H 'Accept: application/json' -H 'Content-Type: application/json;charset=utf-8' --data-raw '{"lat":"","lng":"","area_id":"","q":"","is_opening":"","bs_services":"","bs_brands":"","referer":"","_browser_url":"https%3A%2F%2Fshop.godiva.co.jp%2Fstores","current_url":"https%3A%2F%2Fhttps%3A%2F%2Fshop.godiva.co.jp%2Fstores","limit":"10000"}'` for Japan (357 locations)
