### ISSUE TITLE
Jeff de Bruges (BL, international) (shop/chocolate) (100+ locations)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7279]
### Brand name

Jeff de Bruges

Belgian chocolate retailer

### Wikidata ID

Q3176626
https://www.wikidata.org/wiki/Q3176626
https://www.wikidata.org/wiki/Special:EntityData/Q3176626.json

### Store finder url(s)

https://www.jeff-de-bruges.com/trouver-une-boutique
Official Url(s): https://www.jeff-de-bruges.com/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [x] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q3176626 https://www.jeff-de-bruges.com/`
- [x] I have added the storefinder to wikidata
```
```

**Comment by davidhicks** [comment]
All worldwide locations seemingly returned with a single request:
`curl 'https://www.jeff-de-bruges.com/ajax.V1.php/fr_FR/Rbs/Storelocator/Store/' -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'X-HTTP-Method-Override: GET' --data-raw '{"websiteId":100198,"sectionId":100198,"pageId":101426,"data":{"currentStoreId":0,"distanceUnit":"kilometers","distance":"50000kilometers","coordinates":{"latitude":0,"longitude":0},"commercialSign":0},"dataSets":"coordinates,address,card,allow,hours","URLFormats":"canonical,contextual","visualFormats":"original,95x95,190x190,290x188,384x249,580x376,768x498,1160x752,1536x996","pagination":"0,5000","referer":"https://www.jeff-de-bruges.com/trouver-une-boutique"}'`
