### ISSUE TITLE
Auto detection of hours - can multiple languages be attempted by default?

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7360]
Variation of #7242.

OpeningHours has an assumption that DAYS_EN is the set you want to use.

However, with the generated WPStoreLocatorSpider and probably others, I'm noticing that I have to do an extra touch to say "Oh, and this one is in german/french/etc" all of the time:
```
from locations.hours import DAYS_DE
from locations.storefinders.wp_store_locator import WPStoreLocatorSpider


class BarbarossaBaeckereiDESpider(WPStoreLocatorSpider):
    name = "barbarossa_baeckerei_de"
    item_attributes = {
        "brand_wikidata": "Q807766",
        "brand": "Barbarossa Bäckerei",
    }
    allowed_domains = [
        "www.barbarossa-baeckerei.de",
    ]
    days = DAYS_DE
```

Generally I'm just inferring this from:

- The domain name (90% of the time)
- Chrome translation suggestions

Even if we didn't iterate over all, we could attempt the top 10:
https://www.statista.com/statistics/262946/most-common-languages-on-the-internet/
OR
Guess from the domain on the first requests the array of most probable.

The performance impact of this should be fairly low

**Comment by iandees** [comment]
Generally I prefer to make the spider more explicit than to try multiple things implicitly across all spiders. It might mean more typing or one-offs, but that also means the difference is obvious.

**Comment by CloCkWeRX** [comment]
Okay - fair point, but we have a lot of assumptions with the defaulting of says, DAYS_EN in the current codebase.

Yes, English is the most common language on the web (~50%), but it means that at least half the time that assumption is likely to be wrong the first time you try to write a spider.

Would you be comfortable with swapping this to defaulting to None; and having the core spiders raise an exception along the lines of "Default language(s) not defined - choose one of [DAYS_EN, DAYS_FR]" ?

It'd be a pain to refactor the existing spiders; but it would mean for the auto detection use cases; the looser "guess at language" could be run; while for the production execution / by the time its ready for a PR, the spider author has to have locked it in.
