### ISSUE TITLE
Carrefour (Argentina)

### ISSUE THREAD

**Issue by nicolas17** [alltheplaces/alltheplaces#74]
Supermarket chain, present in several countries.

Their website in Argentina doesn't seem to have a full list of branches, only a search engine:
http://www.carrefour.com.ar/storelocator/index

However, I found a hidden `<select>` that lets you choose a province rather than typing a city, so you could just iterate all 24 provinces.

Interestingly, they have opening hours for every individual branch!

**Comment by iandees** [comment]
@nicolas17 points out in https://github.com/alltheplaces/alltheplaces/pull/353#issuecomment-352185409 that there are more than a hundred stores for this brand. None of the spiders that have been added find them all, so I'm going to reopen this.

**Comment by vlad555** [comment]
done
