### ISSUE TITLE
Yokohama Off-Highway Tires (shop/tires) (Agile Store Finder)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7488]
### Brand name

Yokohama Off-Highway Tires

Off-Highway tire manufacturing company

### Wikidata ID

Q420541
https://www.wikidata.org/wiki/Q420541
https://www.wikidata.org/wiki/Special:EntityData/Q420541.json

### Store finder url(s)

Official Url(s): https://yokohama-oht.com/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q420541 https://yokohama-oht.com/`
```
from locations.storefinders.agile_store_locator import AgileStoreLocatorSpider


class NewBrandZZSpider(AgileStoreLocatorSpider):
        name = "new_brand_zz"
        allowed_domains = [
                "yokohama-oht.com",
        ]

```

**Comment by davidhicks** [comment]
Does not appear to have retail outlets, just a manufacturing company whose products are sold at other branded outlets. Feel free to reopen if I've mistakenly closed.
