### ISSUE TITLE
Cruizers (US) (shop/convenience) (AgileStoreLocator)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7496]
### Brand name

Cruizers

US-american convenience store chain

### Wikidata ID

Q66134801
https://www.wikidata.org/wiki/Q66134801
https://www.wikidata.org/wiki/Special:EntityData/Q66134801.json

### Store finder url(s)

Official Url(s): https://cruizers.net
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q66134801 https://cruizers.net`
```
from locations.storefinders.agile_store_locator import AgileStoreLocatorSpider


class CruizersUSSpider(AgileStoreLocatorSpider):
        name = "cruizers_us"
        item_attributes = {
                "brand_wikidata": "Q66134801",
                "brand": "Cruizers",
        }
        allowed_domains = [
                "www.refuelmarket.com",
        ]
```

**Comment by CloCkWeRX** [comment]
https://cruizers.net/locations/

However, refuel market? Is the main site and has no locator

**Comment by CloCkWeRX** [comment]
https://www.refuelmarket.com/our-stores/

**Comment by davidhicks** [comment]
Yep you are right, Cruizers no longer exists per https://cruizers.net/refuel-acquisition/

I've created #7982 to track Refuel and Double Quick that have taken over Cruizers
