### ISSUE TITLE
Penzeys (US) (shop/spices)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7582]
Fetched 1 brands/shop/spices from NSI
Missing by wikidata: 1
### Brand name

Penzeys Spices

American spice retailer

### Wikidata ID

Q7165435
https://www.wikidata.org/wiki/Q7165435
https://www.wikidata.org/wiki/Special:EntityData/Q7165435.json

### Store finder url(s)
https://www.penzeys.com/locations/
Official Url(s): https://www.penzeys.com/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [x] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q7165435 https://www.penzeys.com/`
```
```

----

**Comment by davidhicks** [comment]
JSON blob with 50 locations (check if this is all--most likely scenario, or just truncated to 50 results):

```
curl -v -H "Accept: application/json" -H "Host: www.penzeys.com" -H "Referer: https://www.penzeys.com/locations/" https://www.penzeys.com/api/GetLocations
```

**Comment by CloCkWeRX** [comment]
51 locations via custom API
            "Address1": "1048 Rockville Pike",
            "Address1": "10805 N. Tatum Boulevard",
            "Address1": "11211 SE 82nd Ave #D",
            "Address1": "11880 74th Pl Ste A",
            "Address1": "12001 W Capitol Dr",
            "Address1": "1274 University Ave",
            "Address1": "12835 Preston Rd",
            "Address1": "1293 Massachusetts Ave",
            "Address1": "1323 Creston Park Drive",
            "Address1": "1615 Sherman Ave",
            "Address1": "1729 Penn Ave",
            "Address1": "17712 W 13 Mile Rd",
            "Address1": "1809 S Orange Ave",
            "Address1": "19300 W Janacek Ct",
            "Address1": "197 Westport Ave",
            "Address1": "21217 Hawthorne Blvd",
            "Address1": "22 E Chicago Ave",
            "Address1": "233 Market St",
            "Address1": "24 Lasalle Rd",
            "Address1": "246 THF Blvd",
            "Address1": "2500 West Main Street",
            "Address1": "27099 Chagrin Blvd",
            "Address1": "2939 18th Street South",
            "Address1": "3028 Hennepin Avenue S",
            "Address1": "3220 Golf Rd",
            "Address1": "3252 University Ave",
            "Address1": "3400 W Cary St",
            "Address1": "3831 SW 117th Ste F",
            "Address1": "4128 North Oracle Road",
            "Address1": "418 Perkins Extd",
            "Address1": "4244 East Towne Blvd",
            "Address1": "4455 Kenny Rd",
            "Address1": "5016 S 74th St",
            "Address1": "513 W Broad St",
            "Address1": "516 W 19th St",
            "Address1": "5345 E 82nd St",
            "Address1": "595 Linmar Lane Unit B60",
            "Address1": "616 S 72nd St",
            "Address1": "6269 Roswell Road NE",
            "Address1": "638 N Water St",
            "Address1": "674 Grand Ave",
            "Address1": "710 North Casaloma Drive",
            "Address1": "7338 Manchester Rd",
            "Address1": "736 Farmers Lane",
            "Address1": "7511 Grandview Avenue",
            "Address1": "7626 160th St W",
            "Address1": "771 Santa Cruz Ave",
            "Address1": "783 Elmwood Avenue",
            "Address1": "7937 Santa Fe Dr",
            "Address1": "W62N604 Washington Ave",
            "Address1": "​Stuyvesant Pla
