### ISSUE TITLE
ADLO (SK) (shop/doors)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7583]
Fetched 4 brands/shop/doors from NSI
Missing by wikidata: 1
### Brand name

ADLO

Slovak security doors retailer

### Wikidata ID

Q116862985
https://www.wikidata.org/wiki/Q116862985
https://www.wikidata.org/wiki/Special:EntityData/Q116862985.json

### Store finder url(s)
https://www.adlo-securitydoors.com/en/shops

Official Url(s): https://www.adlo.sk/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [x] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q116862985 https://www.adlo.sk/`
```
```

----

**Comment by CloCkWeRX** [comment]
Would take our coverage of this NSI category to 100%

**Comment by davidhicks** [comment]
This brand is also present in more than just SK. Also CZ, AT, DE, DK and CH.

I've added location finder URLs for each other country to https://www.wikidata.org/wiki/Q116862985
