### ISSUE TITLE
New storefinder: WP Go Maps

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7591]
5-6x examples.
https://github.com/search?q=repo%3Aalltheplaces%2Falltheplaces%20wpgmza&type=code

Indicator: `/wp-json/wpgmza/v1/`
*Maybe* as simple as:
```
from scrapy import Spider

from locations.categories import Categories
from locations.dict_parser import DictParser


class RottenRobbieUSSpider(Spider):
    name = "rotten_robbie_us"
    item_attributes = {"brand": "Rotten Robbie", "brand_wikidata": "Q87378070", "extras": Categories.FUEL_STATION.value}
    start_urls = [
        "https://www.rottenrobbie.com/wp-json/wpgmza/v1/features/base64eJyrVkrLzClJLVKyUqqOUcpNLIjPTIlRsopRMoxRqlWqBQCnUQoG"
    ]

    def parse(self, response, **kwargs):
        yield from map(DictParser.parse, response.json()["markers"])

```

**Comment by CloCkWeRX** [comment]
https://github.com/alltheplaces/alltheplaces/pull/7592 was detected as Wordpress, but was actually this.

**Comment by davidhicks** [comment]
Good find!

Source code for the `features` API at https://github.com/CodeCabin/wp-google-maps/blob/429c7da3c71215da5676836d92cc7f0b9c0fed41/includes/class.rest-api.php#L550

This should be fairly easy to turn into a new `WPGoMapsSpider`

**Comment by davidhicks** [comment]
Also previously detected with some notes on how to implement this spider at:

https://github.com/alltheplaces/alltheplaces/issues/3436#issuecomment-1690240112

**Comment by CloCkWeRX** [comment]
Well! I just made a start on this and ran out of freebie codespace hours, so... oh well.
