### ISSUE TITLE
New storefinder: Rio SEO

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7621]
> Seems to be a common self-hosted store finder (new, not sure what product/name) shared with https://github.com/alltheplaces/alltheplaces/issues/810, https://github.com/alltheplaces/alltheplaces/issues/966, https://github.com/alltheplaces/alltheplaces/issues/1005, https://github.com/alltheplaces/alltheplaces/issues/1047, hallmark and justice. Search URL is https://maps.locations.airgas.com/api/getAsyncLocations?template=search&level=search&search=Kansas%20City,%20KS,%20US&radius=100000&limit=100000

#809

Other:
https://stores.pandora.net/en-au/

Existing code:
https://github.com/search?q=repo%3Aalltheplaces%2Falltheplaces%20getAsyncLocations&type=code

Raised as a meta issue, adding a storefinder that can detect /api/getAsyncLocations would be a useful tool

**Comment by davidhicks** [comment]
I finally found the store finder as Rio SEO with a home page of https://www.rioseo.com/local-marketing-solutions/store-locator-software/ and demo page of https://local.rioseo.com/

This will be a good store finder to implement straight away as there are many brands which appear to use this store finder. Use of `jquery.rlsmaps_v2.min.js` is another clue available that this store finder is in use.

More spiders which can be converted or added to a new Rio SEO storefinder:
* https://maps.stores.staples.ca/api/getAsyncLocations?template=search&level=search
* https://maps.homedepot.ca/api/getAsyncLocations?template=search&level=search
* https://maps.hallmark.com/api/getAsyncLocations?template=search&level=search
* https://maps.spirithalloween.com/api/getAsyncLocations?template=search&level=search
* https://maps.locations.airgas.com/api/getAsyncLocations?template=search&level=search
* https://maps.pandora.net/api/getAsyncLocations?template=domain&level=domain
* https://maps.cosmoprofbeauty.com/api/getAsyncLocations?template=search&level=search
* https://maps.bankofamerica.com/api/getAsyncLocations?template=search&level=search
* https://maps.stores.footlocker.com/api/getAsyncLocations?template=search&level=search
* https://maps.stores.lindedirect.com/api/getAsyncLocations?template=search&level=search
* https://maps.locations.commercebank.com/api/getAsyncLocations?template=search&level=search
* https://maps.scrubsandbeyond.com/api/getAsyncLocations?template=search&level=search
* https://maps.locations.bankwithunited.com/api/getAsyncLocations?template=search&level=search
* https://maps.locations.eatnpark.com/api/getAsyncLocations?template=search&level=search
* https://maps.partycity.com/api/getAsyncLocations?template=domain&level=domain
* https://maps.savers.com/api/getAsyncLocations?template=search&level=search
* https://maps.locations.vitaminshoppe.com/api/getAsyncLocations?template=domain&level=domain
* https://maps.genghisgrill.com/api/getAsyncLocations?template=domain&level=domain
* https://maps.locations.wingiton.com/api/getAsyncLocations?template=domain&level=domain

**Comment by Cj-Malone** [comment]
I'm going to email RioSEO later today/tomorrow.
