### ISSUE TITLE
Crate And Barrel

### ISSUE THREAD

**Issue by josh0203be** [alltheplaces/alltheplaces#765]
https://www.crateandbarrel.com/stores/list-state/retail-stores

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by shuwen-zhang** [comment]
Hello, I've started working on this but I believe the website might be blocking crawlers. 

The location details are on a different page for each state, and I can crawl around 4 pages before getting redirected to a page with a captcha and getting a 503. 

I've tried changing the `User-Agent` in headers and setting a `download_delay = 10`. Are there other general strategies that could be good to try?

**Comment by iandees** [comment]
It looks like setting user-agent works for me. Your IP might be blocked for some amount of time now. I would just move on to another ticket.

**Comment by kumanoit** [comment]
I am interested in this

**Comment by kumanoit** [comment]
Raised PR: https://github.com/alltheplaces/alltheplaces/pull/4096/files
