### ISSUE TITLE
Pizza Hut (GB) (360 restaurants) - change to custom API

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#7699]
### Brand name

Pizza Hut

### Wikidata ID

Q191615

### Store finder url(s)

https://api.pizzahut.io/v1/huts/?sector=uk-1

**Comment by davidhicks** [comment]
Same API endpoint as #7698 just with a different search filter.

**Comment by davidhicks** [comment]
This spider already exists as `pizza_hut_gb` and I accidentally created this issue without realising the duplication.

What I suggest happen instead is that when the Pizza Hut (FR) spider is created in #7698, the existing `pizza_hut_gb` spider be changed to use the same API, reducing the need for 360+ requests for individual restaurant pages to extract structured data from each.

**Comment by rjw62** [comment]
FYI the pizza_hut_gb spider is currently broken (403 errors, so maybe we're being blocked from accessing the sitemap), so this might be a good time to look again at this. 

Note that there's also https://api.pizzahut.io/v1/huts/?sector=uk-2 to collect from. They don't seem to list websites though, but maybe it's possible to construct the URLs from the type, name, id, and sector data.

* The delivery branches have URLs like https://www.pizzahut.co.uk/huts/uk-1/8147-ashton-under-lyne/
* The restaurants have URLs like https://www.pizzahut.co.uk/restaurants/find/details/ashtonunderlyne
