### ISSUE TITLE
Great Wolf Lodge

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#772]
https://www.greatwolf.com/

**Comment by davidhicks** [comment]
CrawlSpider of `https://www.greatwolf.com/locations` with StructuredDataSpider used for individual location pages such as `https://www.greatwolf.com/mashantucket`. Coordinates or much other detail on each location does not appear to be available anywhere to parse.

**Comment by iandees** [comment]
It seems that there's coordinates on the customer service page for each location. For example: https://www.greatwolf.com/grand-mound/customer-service

**Comment by davidhicks** [comment]
Great, thanks!

In that case we should do: SitemapSpider of `https://www.greatwolf.com/php-root.sitemap.xml` with filter of `/customer-service$` and for each location page, use StructuredDataSpider to extract location data. Within the location data is a `hasMap` attribute which is a Google Maps URL that can be parsed to obtain coordinates e.g. `46.7905042,-123.0121885` for `https://www.greatwolf.com/grand-mound/customer-service`
