### ISSUE TITLE
Bob Evan's

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#777]
https://www.bobevans.com/webservices/restaurantSearch/search/45.0/-90.0/500/1000/500

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by davidhicks** [comment]
Working without error per most recent run: https://alltheplaces-data.openaddresses.io/runs/2024-02-03-13-31-57/stats/bobevans_us.json
