### ISSUE TITLE
Les Comptoirs de la Bio (FR) (Sitemap, Structured Data)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7786]
### Brand name

Les Comptoirs de la Bio

French retail chain

### Wikidata ID

Q120801428
https://www.wikidata.org/wiki/Q120801428
https://www.wikidata.org/wiki/Special:EntityData/Q120801428.json

### Store finder url(s)
https://magasins.lescomptoirsdelabio.fr/
Official Url(s): https://lescomptoirsdelabio.fr/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q120801428 https://lescomptoirsdelabio.fr/`
```
from scrapy.spiders import SitemapSpider

from locations.structured_data_spider import StructuredDataSpider


class LesComptoirsDeLaBioFRSSpider(SitemapSpider, StructuredDataSpider):
    name = "lescomptoirsdelabio_fr"
    item_attributes = {"brand": "Les Comptoirs de la Bio", "brand_wikidata": "Q4646294"}
    sitemap_urls = ["https://magasins.lescomptoirsdelabio.fr/client/sitemap-locations-fr.xml.gz"]
    sitemap_rules = [(r"\/fr\/[\w-]+-\d+$", "parse_sd")]
    wanted_types = ["LocalBusiness"]
```

**Comment by CloCkWeRX** [comment]
https://magasins.lescomptoirsdelabio.fr/sitemap.xml
https://magasins.lescomptoirsdelabio.fr/client/sitemap-locations-fr.xml.gz
https://magasins.lescomptoirsdelabio.fr/client/sitemap-divisions-fr.xml.gz
https://magasins.lescomptoirsdelabio.fr/client/sitemap-static.xml.gz

**Comment by CloCkWeRX** [comment]
https://validator.schema.org/#url=https%3A%2F%2Fmagasins.lescomptoirsdelabio.fr%2Ffr%2Fles-comptoirs-de-la-bio-mallemort-105423
Structured Data

**Comment by CloCkWeRX** [comment]
Structured data inserted outside of DOM

**Comment by Cj-Malone** [comment]
If you use uBlock Origin, it's real quick to disable javascrip and check if something is part of the request, or added via js.

`curl "https://0knemtbxx3-3.algolianet.com/1/indexes/CDLB_fr" -H "x-algolia-application-id: 0KNEMTBXX3" -H "x-algolia-api-key: 7a46160ed01bb0af2c2af8d14b97f3c5" | jq`
I've seen this response before, specifically `nbPages`.
