### ISSUE TITLE
Golf Galaxy (US)

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#7808]
### Brand name

Golf Galaxy

### Wikidata ID

Q69364358

### Store finder url(s)

```
from locations.storefinders.where2getit import Where2GetItSpider


class GolfGalaxyUSSpider(Where2GetItSpider):
    name = "golf_galaxy_us"
    item_attributes = {
        "brand_wikidata": "Q69364358",
        "brand": "Golf Galaxy",
    }
    api_endpoint = "https://storelocator.golfgalaxy.com/rest/getlist"
    api_key = "CE23B360-C828-11E4-B146-ED9AA38844B8"
```

**Comment by CloCkWeRX** [comment]
Golf Galaxy

American golf equipment store chain

### Wikidata ID

Q69364358
https://www.wikidata.org/wiki/Q69364358
https://www.wikidata.org/wiki/Special:EntityData/Q69364358.json

### Store finder url(s)

Official Url(s): https://www.golfgalaxy.com/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q69364358 https://www.golfgalaxy.com/`
```
```

**Comment by CloCkWeRX** [comment]
Are you finding these through the new detectors? Might be worth me rerunning everything!

**Comment by davidhicks** [comment]
> Are you finding these through the new detectors? Might be worth me rerunning everything!

I also do a search of various search engines for "locations.where2getit.com" and other such storefinder pages that are hosted externally and included into a brand's website via iframe. In the past I also try to find if storefinder websites have blogs or "client success stories" or case studies where they list some of their customers.
