### ISSUE TITLE
Storefinder: Sylinder

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7844]
#7841 #2923

https://api.ngdata.no/sylinder/stores/v1/basic-info?chainId=1300
https://api.ngdata.no/sylinder/stores/v1/basic-info?chainId=1100
https://api.ngdata.no/sylinder/stores/v1/extended-info/7080000028320

Can we iterate over all of the chain ids?

**Comment by davidhicks** [comment]
https://www.reddit.com/r/norge/comments/125o41q/comment/je527se/ provides a few more chains using this storefinder:

- KIWI: https://platform-rest-prod.ngdata.no/api/extended-user/1100/default
- SPAR: https://platform-rest-prod.ngdata.no/api/extended-user/1210/default
- Joker: https://platform-rest-prod.ngdata.no/api/extended-user/1220/default
- MENY: https://platform-rest-prod.ngdata.no/api/extended-user/1300/default
