### ISSUE TITLE
EKO petrol stations

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#7902]
### Brand name

Multiple

### Wikidata ID

Multiple

### Store finder url(s)

The data is stored in elements with `data-control="box"`.

Example for future reference:
```html
<article id="x-control-27a2641a-2d38-47b3-b1c6-4d9a147b7d1c" class="x-control x-box x-partner-box" data-control="box" data-latitude="42.56098946397903" data-longitude="23.668149760105784">
<div style="display: none;" class="box-info" data-latitude="42.56098946397903" data-longitude="23.668149760105784">
    <div>
        <div class="name-container">
                <span class="name">EKO 1101 Ихтиман</span>
        </div>

        <ul class="info-container">
                <li class="address-one">АМ Тракия, 21-ви километър (посока Бургас), Ихтиман</li>
                <li class="phone">+359 894 442 154 </li>
            <li class="map-url"><a href="[https://www.google.gr/maps/dir//42.56098946397903,23.668149760105784](view-source:https://www.google.gr/maps/dir//42.56098946397903,23.668149760105784)" target="_blank">Виж на Google Maps</a></li>
        </ul>
        <div class="extra-features-container">
            <ul>
                    <li class="wc" title="WC"></li>
                    <li class="minimarket" title="Mini Market"></li>
                    <li class="coffee-zone" title="Coffee Zone"></li>
                    <li class="atm" title="ATM"></li>
                    <li class="parking" title="Parking"></li>
                    <li class="disabled-wc" title="WC for disabled people "></li>
            </ul>
        </div>
```

| Country | URL                                                         | brand | wikidata   |
|--------|-------------------------------------------------------------|-------|------------|
| ME     | https://www.jugopetrol.co.me/stanice/prona-i-stanicu/       | EKO   | Q111604689 |
| GR     | https://www.eko.gr/pratiria/katastimata/                    | EKO   | Q31283948  |
| MK     | https://www.okta-elpe.com/service-stations/find-a-station/  | OKTA  | Q3350105   |
| RS     | https://www.ekoserbia.com/benzinske-stanice/find-a-station/ | EKO   | Q111604683 |
| CY     | https://www.eko.com.cy/pratiria/katastimata/                | EKO   | Q111604705 |
| BG     | https://www.eko.bg/stations/karta-na-obektite/              | EKO   | Q111603199 |

**Comment by CloCkWeRX** [comment]
Distint from 
Brand name
Eko

Polish supermarket chain

Wikidata ID
Q9251859
https://www.wikidata.org/wiki/Q9251859
https://www.wikidata.org/wiki/Special:EntityData/Q9251859.json

Store finder url(s)
Official Url(s): http://www.eko.pl/

?

**Comment by CloCkWeRX** [comment]
https://www.jugopetrol.co.me/stanice/prona-i-stanicu/

> generator" content="Created by Lighthouse, powered by VENDD e-commerce platform - www.lighthouse.gr

https://www.ekoserbia.com/benzinske-stanice/find-a-station/
> name="generator" content="Created by Lighthouse, powered by VENDD e-commerce platform - www.lighthouse.gr"

**Comment by Dimitar5555** [comment]
Thank you for handling them @CloCkWeRX!

**Comment by CloCkWeRX** [comment]
@iandees the associated PRs for this one should all be okay to land now (first PR was merged adding the Storefinder)
