### ISSUE TITLE
Maggiano's

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#792]
https://locations.maggianos.com/

Browse listings near the bottom.

**Comment by davidhicks** [comment]
Single API call to `https://locations.maggianos.com/api//restaurant-data/` appears to return JSON format location data for all 51 locations.

**Comment by CloCkWeRX** [comment]
Fixed in https://github.com/alltheplaces/alltheplaces/pull/5593/files - closable @iandees
