### ISSUE TITLE
Bravo Cucina

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#793]
https://bravoitalian.com/locations.html

**Comment by rad-a** [comment]
I'd like to give this a try :)

**Comment by CloCkWeRX** [comment]
Now https://www.bravoitalian.com/locations/

https://www.bravoitalian.com/wp-json/ee/locations/v1/geo-locate/?address=fish

**Comment by Cj-Malone** [comment]
There is also a geojson (`//script[contains(text(), "FeatureCollection")]`) on https://www.bravoitalian.com/locations/. May be better than a search api.

**Comment by CloCkWeRX** [comment]
Bravo Cucina Italiana (Q64055574)
