### ISSUE TITLE
Pak'nSave (NZ) (Custom API)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7947]
### Brand name

Pak'nSave

New Zealand supermarket chain

### Wikidata ID

Q7125339
https://www.wikidata.org/wiki/Q7125339
https://www.wikidata.org/wiki/Special:EntityData/Q7125339.json

### Store finder url(s)

Official Url(s): https://www.paknsave.co.nz/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [x] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q7125339 https://www.paknsave.co.nz/`
```
```

**Comment by CloCkWeRX** [comment]
https://www.paknsave.co.nz/store-finder

**Comment by CloCkWeRX** [comment]
https://www.paknsave.co.nz/BrandsApi/BrandsStore/GetBrandStores

**Comment by davidhicks** [comment]
Fixed in #8379
