### ISSUE TITLE
Primaprix (HTML Parsing)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7954]
### Brand name

Primaprix

### Wikidata ID

Q112691161
https://www.wikidata.org/wiki/Q112691161
https://www.wikidata.org/wiki/Special:EntityData/Q112691161.json

### Store finder url(s)
https://primaprix.eu/es/localiza-tu-tienda/
Official Url(s): https://primaprix.es/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q112691161 https://primaprix.es/`
```
```

**Comment by davidhicks** [comment]
JavaScript blob parsing seems the better option returning lat/lon too:
```
<script>
    window.country = "Espa\u00f1a";
    if (window.shops === undefined) {
        window.shops = [
    {
        "id": 17757,
        "name": "PrimaPrix Barcelona Ribes",
        "lat": 41.39479300000001,
        "lng": 2.1814486,
        "zipcode": "08013",
        "address": "Carrer de Ribes, 27",
        "mapsUrl": null,
        "url": "https:\/\/primaprix.eu\/tienda\/primaprix-barcelona-ribes\/",
        "search_url": "https:\/\/primaprix.eu\/es\/localiza-tu-tienda\/?busqueda=Carrer+de+Ribes%2C+27+08013",
        "is_open": null,
        "schedule": null,
        "country": "es"
    },
```
