### ISSUE TITLE
Waitrose Spider Broken

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#7994]
For the last couple of weeks the Waitrose spider https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/waitrose.py has returned zero results, presumably because of a website re-organisation by the Waitrose.

I think the page we now want to looking at is https://www.waitrose.com/find-a-store/directory where the list of stores is contained in a URI-encoded JSON string. The slugs in the JSON need to be appended to https://www.waitrose.com/find-a-store/ to give the individual store URLs, e.g. https://www.waitrose.com/find-a-store/battersea-nine-elms , which can then be parsed for location, address, opening hours, etc.

**Comment by Cj-Malone** [comment]
I don't see a way to differentiate between the [convenience](https://www.waitrose.com/find-a-store/membury-east-services) stores and [supermarkets](https://www.waitrose.com/find-a-store/windsor) :/

**Comment by Cj-Malone** [comment]
https://gist.github.com/Cj-Malone/4d7703ece53a426e910921ef8b417abe

**Comment by rjw62** [comment]
> I don't see a way to differentiate between the [convenience](https://www.waitrose.com/find-a-store/membury-east-services) stores and [supermarkets](https://www.waitrose.com/find-a-store/windsor) :/

I haven't looked closely, but how about the presence or absence of the "c_accessibility", "c_facilities" , "c_facilities"  and/or "c_departments" entries in the JSON on the store page? These presumably control the corresponding headings in the "Available at this store" section. I'm guessing the supermarkets may have them, and the convenience type stores don't. (You already get some presumably with the "Little Waitrose" brand.)

**Comment by Cj-Malone** [comment]
https://gist.github.com/Cj-Malone/c7a24c7909dddef90d45bc8f6b6a3151

Let me know if you find anything.
