### ISSUE TITLE
Rosauers Supermarkets (HTML Parsing)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#7999]
### Brand name

Rosauers Supermarkets

American supermarket chain

### Wikidata ID

Q7367458
https://www.wikidata.org/wiki/Q7367458
https://www.wikidata.org/wiki/Special:EntityData/Q7367458.json

### Store finder url(s)
https://www.rosauers.com/store-locations/
Official Url(s): https://www.rosauers.com/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q7367458 https://www.rosauers.com/`
```
```

**Comment by davidhicks** [comment]
Needs a new storefinder per #7591
