### ISSUE TITLE
Boston Market

### ISSUE THREAD

**Issue by ianmcorvidae** [alltheplaces/alltheplaces#81]
https://www.bostonmarket.com/locations/

**Comment by sweetdream0729** [comment]
working on this.

**Comment by iandees** [comment]
No progress for 2 days, re-opening this for others.

**Comment by vikranthkr** [comment]
These 16 stores are either not yet operational or have been shutdown. They are listed under locations on their sitemap but are not part of their store locator.
https://www.bostonmarket.com/location/saugus-ma-29/
https://www.bostonmarket.com/location/lincoln-ne-673/
https://www.bostonmarket.com/location/providence-ri-1103/
https://www.bostonmarket.com/location/severna-park-md-246/
https://www.bostonmarket.com/location/pleasant-hills-pa-266/
https://www.bostonmarket.com/location/san-jose-ca-1128/
https://www.bostonmarket.com/location/palm-bay-fl-275/
https://www.bostonmarket.com/location/ft-lauderdale-fl-268/
https://www.bostonmarket.com/location/deerfield-beach-fl-2450/
https://www.bostonmarket.com/location/longwood-fl-347/
https://www.bostonmarket.com/location/ludlow-ma-3204/
https://www.bostonmarket.com/location/pittsburgh-pa-3206/
https://www.bostonmarket.com/location/whitehall-pa-406/
https://www.bostonmarket.com/location/blasdell-ny-1809/
https://www.bostonmarket.com/location/chapel-hill-nc-414/
https://www.bostonmarket.com/location/southlake-tx-2287/

I suspect they'll be included in their location search [API](https://www.bostonmarket.com/wp-admin/admin-ajax.php?action=bingmaps_locations_search_ajax&search=california) when they are in operation.

I can add a separate way to parse and add these if needed.
