### ISSUE TITLE
Praxair

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#810]
http://www.praxair.com/international-locations

**Comment by davidhicks** [comment]
Brand renamed to `Linde Gas & Equipment`.

Seems to be a common self-hosted store finder (new, not sure what product/name) shared with #809, #966, #1005, #1047, `hallmark` and `justice`. Search URL is `https://maps.stores.lindedirect.com/api/getAsyncLocations?template=search&level=search&search=Kansas%20City,%20KS,%20US&radius=100000&limit=100000`
