### ISSUE TITLE
Super C

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#8104]
### Brand name

Super C

Canadian supermarket chain

### Wikidata ID

Q3504127
https://www.wikidata.org/wiki/Q3504127
https://www.wikidata.org/wiki/Special:EntityData/Q3504127.json

### Store finder url(s)

Official Url(s): https://www.superc.ca/index.fr.html
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [x] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q3504127 https://www.superc.ca/index.fr.html`
```
```
Official Url(s): https://www.superc.ca/index.en.html
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [x] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q3504127 https://www.superc.ca/index.en.html`
```
```
https://www.superc.ca/en/find-a-grocery

**Comment by davidhicks** [comment]
Sitemap: https://www.superc.ca/sitemap-general-en.xml
Example store URL: https://www.superc.ca/en/find-a-grocery/742
HTML parsing needed. Lat/lon available in Google Maps URL.
