### ISSUE TITLE
Super del Norte

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#8105]
### Brand name

Super del Norte

Mexican supermarket chain

### Wikidata ID

Q88388513
https://www.wikidata.org/wiki/Q88388513
https://www.wikidata.org/wiki/Special:EntityData/Q88388513.json

### Store finder url(s)

Official Url(s): http://www.superdelnorte.com.mx/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [x] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q88388513 http://www.superdelnorte.com.mx/`
```
```
https://www.superdelnorte.com.mx/sucursales

**Comment by davidhicks** [comment]
All 38 locations returned in JSON format via: https://superdelnorte.com.mx/api/tiendas

Note lat and lon are found in a Google Maps URL for each location within the JSON response.
