### ISSUE TITLE
AAA Offices

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#811]
http://www.aaa.com/office/

**Comment by sledjama** [comment]
AAA has locations by zip and radius.
I have a list of all 40,000 zip codes, is it wise to have over 40,000 start_urls
or do you have any recommendations?

**Comment by sledjama** [comment]
So i figured it also allows search by city name e.g
http://tdr.aaa.com/tdrl/search.jsp?searchtype=O&radius=500&format=json&ident=AAACOM&destination=Richmond,%20VA

http://www.aaa.com/office/assets/places.json also provides the city names, which is 33,145 start_urls we are looking at.
i will go for this. thanks

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.
