### ISSUE TITLE
SuperBrugsen (COOP)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#8115]
### Brand name

SuperBrugsen

Danish supermarket chain

Part of #840 

### Wikidata ID

Q12337746
https://www.wikidata.org/wiki/Q12337746
https://www.wikidata.org/wiki/Special:EntityData/Q12337746.json

### Store finder url(s)
https://butik.coop.dk/find-butik/
Official Url(s): http://www.superbrugsen.dk/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q12337746 http://www.superbrugsen.dk/`
```
```
Official Url(s): https://superbrugsen.coop.dk
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q12337746 https://superbrugsen.coop.dk`
```
```

**Comment by davidhicks** [comment]
`https://butik.coop.dk/umbraco/api/Chains/GetAllStores` to get all stores and basic data.

`https://butik.coop.dk/umbraco/api/Chains/GetStorePartials?kardex={store_id}` to get opening hours in HTML format (needing HTML parsing) for each `{store_id}`.
