### ISSUE TITLE
[GB] Poundstretcher (323 shops, jsblob)

### ISSUE THREAD

**Issue by RedAuburn** [alltheplaces/alltheplaces#8134]
### Brand name

Poundstretcher

### Wikidata ID

Q7235675

### Store finder url(s)

https://www.poundstretcher.co.uk/find-a-store

json:
https://www.poundstretcher.co.uk/ustorelocator/location/searchJson/

**Comment by Cj-Malone** [comment]
Oh I assigned myself, but did you want to try?

**Comment by RedAuburn** [comment]
> Oh I assigned myself, but did you want to try?

sadly i'm pretty busy at the moment, so if you fancy doing it that'd be great :)
i'll get around to it eventually if not
