### ISSUE TITLE
Huddle House

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#816]
https://locations.huddlehouse.com/index.html

**Comment by davidhicks** [comment]
SitemapSpider of `https://www.huddlehouse.com/sitemap.xml` (filtering on `/locations/[a-z]{2}/[\w\-]+/{slug}/`) + StructuredDataSpider (LD+JSON)

**Comment by davidhicks** [comment]
> SitemapSpider of `https://www.huddlehouse.com/sitemap.xml` (filtering on `/locations/[a-z]{2}/[\w\-]+/{slug}/`) + StructuredDataSpider (LD+JSON)

This wasn't possible as location pages have minimised/obfuscated JavaScript blobs which dynamically populate the page with location data (including LD+JSON data, but it's broken so useless to us). The JavaScript blobs cannot be parsed without a JavaScript interpreter.

I found another way with a custom API that returns up to 25 results per radius search.
