### ISSUE TITLE
The Store (MY)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#8171]
### Brand name

The Store

Malaysian supermarket

### Wikidata ID

Q96679754
https://www.wikidata.org/wiki/Q96679754
https://www.wikidata.org/wiki/Special:EntityData/Q96679754.json

### Store finder url(s)
https://www.tstore.com.my/storelocator.php
Official Url(s): https://www.tstore.com.my
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q96679754 https://www.tstore.com.my`
```
```

**Comment by davidhicks** [comment]
Has four sub-brands:
* The Store, https://www.wikidata.org/wiki/Q96679754
* Pacific, https://www.wikidata.org/wiki/Q125449800
* Millimewa, https://www.wikidata.org/wiki/Q125449813
* Super Jimat, https://www.wikidata.org/wiki/Q125449830

I'll implement all four with The Store being the base class, and other sub-brands inheriting where possible.
