### ISSUE TITLE
Wendy's incorrect hours

### ISSUE THREAD

**Issue by yo-scottie-oh** [alltheplaces/alltheplaces#8373]
ATP populates incorrect hours for Wendy's. It's populating 10:30 when [the Wendy's website](https://locations.wendys.com/united-states/oh/loveland/10601-loveland-madeira-rd) says 12:00am. Reference [OSM Changeset 151311478](https://www.openstreetmap.org/changeset/151311478#map=6/41.675/-77.593). I assume it has to do with parsing multiple blocks of hours on the same page. In this case, the web page lists restaurant hours and drive through hours, with an extra blurb about breakfast ending at 10:30 am, which I assume is where the 10:30 is coming from in the OSM import.

**Comment by iandees** [comment]
It looks like "breakfast hours" are getting mixed in with regular store opening hours. I'll look at a fix.
