### ISSUE TITLE
La Salsa

### ISSUE THREAD

**Issue by ianmcorvidae** [alltheplaces/alltheplaces#84]
http://lasalsa.com/locations/

**Comment by nicolas17** [comment]
Search engine. Uses Google's geocoder to convert the search string to a lat/lon, then fetches:
```http://lasalsa.com/wp-content/themes/lasalsa-main/locations-search.php?lat=<lat>&lng=<lng>&radius=50```
Apparently has no limit to the radius, so http://lasalsa.com/wp-content/themes/lasalsa-main/locations-search.php?lat=0&lng=0&radius=99999999 will give you all stores!
