### ISSUE TITLE
Incorrect addr:full parsing in mcdonalds_localizer.py

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#846]
I haven't investigated much, but for many addresses, characters are being left off the beginning of the address, like:

    as Cumbres Ave., Carr 199 Int.176, Rio Piedras 00926,
    venida João Pinheiro s/n - Lote 4,   - Centro, Poços de Caldas - 37701-386, BR

I guess @SelfnessAid is working on that spider.

**Comment by CloCkWeRX** [comment]
Closable? mcdonalds_localizer doesn't appear to exist in the codebase anymore.
