### ISSUE TITLE
Mister Minit (shop/locksmith) (AU) (395 locations)

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#8489]
### Brand name

Mister Minit

### Wikidata ID

Q1939269

### Store finder url(s)

https://storage.googleapis.com/maps-solutions-7ge5m84jyd/locator-plus/08n0/locator-plus-config.js

**Comment by CloCkWeRX** [comment]
Also international?


Fetched 6 brands/shop/locksmith from NSI
Missing by wikidata: 4
### Brand name

Mister Minit

company

### Wikidata ID

Q1939269
https://www.wikidata.org/wiki/Q1939269
https://www.wikidata.org/wiki/Special:EntityData/Q1939269.json

### Store finder url(s)

Official Url(s): https://www.misterminit.eu/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q1939269 https://www.misterminit.eu/`
```
```
Official Url(s): https://www.minit.co.jp/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q1939269 https://www.minit.co.jp/`
```
```

**Comment by davidhicks** [comment]
Good find on them being international, we'll have to add those international locations to the TODO list.
