### ISSUE TITLE
BedsRus (shop/bed) (NZ)

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#8530]
### Brand name

BedsRus

### Wikidata ID

Q111018938

### Store finder url(s)

Storemapper ID: 16389

**Comment by CloCkWeRX** [comment]
### Brand name

BedsRus

New Zealand chain of bed stores

### Wikidata ID

Q111018938
https://www.wikidata.org/wiki/Q111018938
https://www.wikidata.org/wiki/Special:EntityData/Q111018938.json

### Store finder url(s)

Official Url(s): https://www.bedsrus.co.nz/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q111018938 https://www.bedsrus.co.nz/`
```
```
