### ISSUE TITLE
Minimarket (shop/convenience) (BG) 60 locations

### ISSUE THREAD

**Issue by Dimitar5555** [alltheplaces/alltheplaces#8580]
### Brand name

Minimart

### Wikidata ID

Q119168386

### Store finder url(s)

https://mini-mart.bg/nameri-magazin/

Requires HTML parsing. The locations are encoded in Google Maps URLs (`https://maps.app.goo.gl/{randomString}`).

**Comment by CloCkWeRX** [comment]
### Brand name

Minimart

Convenience store chain in Bulgaria

### Wikidata ID

Q119168386
https://www.wikidata.org/wiki/Q119168386
https://www.wikidata.org/wiki/Special:EntityData/Q119168386.json

### Store finder url(s)

Official Url(s): https://mini-mart.bg/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
`pipenv run scrapy sf --brand-wikidata=Q119168386 https://mini-mart.bg/`
```
```

**Comment by davidhicks** [comment]
They're just Google Maps shortener URLs, so we'd follow them and capture the redirect to the full Google Maps URL that can then be parsed for lat/lon.
