### ISSUE TITLE
KFC ghost entries

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#8626]
> it looks like KFC isn't removing branches that have permanently closed from its listings, it just has them with opening hours indicating they're never open

https://osmus.slack.com/archives/CDJ4LKA2Y/p1718394560134019 (#poi channel)

Maybe they should be removed from ATP output? Or get some lifecycle prefix?

**Comment by jleedev** [comment]
For the locations with explicitly closed hours, e.g.

`<tr itemprop="openingHours" content="Mo Closed">` (etc.)

I would much prefer to see the output contain `"opening_hours":"Mo-Su off"`.

**Comment by Cj-Malone** [comment]
We have `end_date` for closed locations, either `yes` or `YYYY-MM-DD`.

Are we all happy that `xx Closed` on KFC, are actually closed? I did a spot check and it seems right.

**Comment by matkoniecz** [comment]
@Cj-Malone Should it be closed after https://github.com/alltheplaces/alltheplaces/pull/8627 merge?
