### ISSUE TITLE
bad link provided by edeka spider

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#8642]
https://www.openstreetmap.org/way/235612992 has working https://www.edeka.de/eh/minden-hannover/edeka-junghans-poppauer-str.-2/index.jsp

ATP suggests https://www.edeka.de/eh/minden-hannover/edeka-junghans-poppauer-str.-2/index.jspp

(not investigated how it happens and is it a wider issue)

**Comment by Cj-Malone** [comment]
Comes direct from the [source](https://www.edeka.de/api/marketsearch/markets?size=1&page=2725)

**Comment by matkoniecz** [comment]
should it be patched out at ATP level? Or is it preferable for every ATP consumer to spot and eliminate it on their own?

**Comment by iandees** [comment]
We can add an if-check in the spider to fix it on our end.

**Comment by matkoniecz** [comment]
Code: https://github.com/alltheplaces/alltheplaces/blob/fbcec251dfd54ba56712beff81247a51711cd17d/locations/spiders/edeka_de.py

likely proper fix method: https://github.com/alltheplaces/alltheplaces/commit/c9479270dc424d80e3be800aa575dd287f91ad2b
