### ISSUE TITLE
Organic food stores in Germany

### ISSUE THREAD

**Issue by tordans** [alltheplaces/alltheplaces#866]
This websites show an index of organic food stores
- berlin only https://www.meinbioberlin.de/
- based on data from https://www.bio123.de/ladenfinder which seems to be all germany

The data seems to be part of a big json blog that is included when the html is rendered.

**Comment by CloCkWeRX** [comment]
https://www.meinbioberlin.de/ - can't be reached
https://www.bio123.de/ladenfinder 404

https://www.bio123.de/anbieter does exist.
https://www.bio123.de/anbieter/munchen/basic-biomarkt-munchen-city - structured data available, no coords in the structured data / might have to extract from the map.

https://www.bio123.de/sitemap.xml lists everything under /anbieten/

Problem: There's a huge number of categories

**Comment by CloCkWeRX** [comment]
https://www.bio123.de/anbieter/online-shop/hautwohl example to ignore
