### ISSUE TITLE
sushi_sushi_au: coordinates are junk

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#8683]
sushi_sushi_au coordinates are useless junk (most in the middle of the ocean or not at all near their true location), and it's not a case of flipped coordinates. Coordinates for this spider should likely be dropped. If address data is also found to be garbage, the whole spider should be deleted.

**Comment by CloCkWeRX** [comment]
https://github.com/alltheplaces/alltheplaces/blob/e066aea434f62242f5b3592a17695eda85089277/locations/spiders/sushi_sushi_au.py#L9
https://github.com/alltheplaces/alltheplaces/pull/8564

**Comment by CloCkWeRX** [comment]
From the original PR
![image](https://github.com/user-attachments/assets/5bbe88bc-ba50-4930-9c6d-d16437c5a4b5)

Looking at some Adelaide ones, the coordinates def don't match the addresses
![image](https://github.com/user-attachments/assets/e6d326c0-ad83-499a-bcd2-0a95ed322fc3)


But the addresses seem legit

**Comment by davidhicks** [comment]
We do keep some spiders with addresses only (no coordinates) so that is what I'd propose to do here.

**Comment by iandees** [comment]
Yep we can drop the coordinates if they're terrible.
