### ISSUE TITLE
Clarify license (around produced data)

### ISSUE THREAD

**Issue by nvkelso** [alltheplaces/alltheplaces#869]
On the website we say:

**License:** `CC-0` with the text `The downloads provided above and the data contained therein are released under Creative Commons’ CC-0 waiver.`

The readme in this repo and the license file should also reference the same, in a similar way to OpenAddresses setup:

- https://github.com/openaddresses/openaddresses/blob/master/README.md#license

**Comment by iandees** [comment]
Updated the readme and license to describe the data and software licensing.

**Comment by Cj-Malone** [comment]
Can the data be released under the CC0? Surely the copyright is actually owned by the websites it's scraped from and the vast majority of them state something like "All Rights Reserved".

**Comment by iandees** [comment]
Hi @Cj-Malone! I encourage you to read about the [Feist v. Rural](https://en.wikipedia.org/wiki/Feist_Publications,_Inc.,_v._Rural_Telephone_Service_Co.) Supreme Court case. It shows that information alone (like in a phone book or on a place listing website) is not copyrightable. Having said that, I'm not a lawyer so I encourage you to work with a lawyer if you're worried about usage of this data.

**Comment by Cj-Malone** [comment]
I think when these sites have TOS/other legalese it's a contract on using the site that overrides raw rights.

For example, [Walmart TOU](https://www.walmart.com/help/article/walmart-com-terms-of-use/3b75080af40340d6bbd596f116fae5a0)

> In connection with the Walmart Sites, you will not:

> Use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, index, “scrape,” “data mine” or otherwise gather any Materials, or reproduce or circumvent the navigational structure or presentation of the Walmart Sites, without Walmart’s express prior written consent.

I don't think there is anyway that data scraped from Walmart could be released under CC0. Sorry to be a party pooper.

I'm from the UK where there are [Database rights](https://en.wikipedia.org/wiki/Database_right) too. Also not a lawyer so no idea how this works in an international context.

Anyway, I have been working on a [similar project](https://gitlab.com/KAFF/places), but now I've learnt about this I'll probably end up writing scrapers here if that's OK.

**Comment by iandees** [comment]
It'd be great to have your help on more spiders. Let me know if you have any questions!
