### ISSUE TITLE
audi, ford, kpmg: lat/lon switched.

### ISSUE THREAD

**Issue by j9d3it** [alltheplaces/alltheplaces#8690]
just look at [the map](https://www.alltheplaces.xyz/map/#3.37/-80.74/21.99) down in Antarctica, there's a bunch of examples. These are out in the [middle of the Pacific Ocean](https://www.alltheplaces.xyz/map/#13.42/13.83333/171.75) too.

**Comment by Cj-Malone** [comment]
Source data has errors, especially coords. If you need better coords for some POIs, geocode them. If you don't want them, filter them out.

**Comment by matkoniecz** [comment]
> If you need better coords for some POIs, geocode them

though does have a potential trap of ending with more plausible but still bad location

**Comment by matkoniecz** [comment]
See also #8689 - not sure whether this kind of strategy should be applied more widely

**Comment by Cj-Malone** [comment]
And whitelisting coords doesn't scale. And has the "potential trap" of throwing away any useful data. If [theses](https://github.com/alltheplaces/alltheplaces/blob/b62bc57e440f7b0ceca1e97fca89a6e92e7fe6ff/locations/spiders/cube_smart_us.py#L16) coords were thrown I would have assumed they were junk. If [these](https://github.com/alltheplaces/alltheplaces/blob/b62bc57e440f7b0ceca1e97fca89a6e92e7fe6ff/locations/spiders/salvatore_ca.py#L31) coords were thrown away I wouldn't have known to filp them.

**Comment by Cj-Malone** [comment]
Adding an `if` for 1 broken url doesn't scale. Every dataset has errors, including source data.

**Comment by matkoniecz** [comment]
well, for at least some uses you want to skip known errors

and you need to put it somewhere, and ATP would be a nice place (as otherwise several projects like this will need to coordinate somewhere else or repeat the same work)
