### ISSUE TITLE
Brookshire's

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#870]
http://brookshires.mywebgrocer.com/Stores/?mobile=0

**Comment by davidhicks** [comment]
New URL blocked by Cloudflare: https://www.brookshires.com/store

**Comment by CloCkWeRX** [comment]
### Brand name

Brookshire Grocery Company

American supermarket chain

### Wikidata ID

Q4975085
https://www.wikidata.org/wiki/Q4975085
https://www.wikidata.org/wiki/Special:EntityData/Q4975085.json

### Store finder url(s)

Official Url(s): https://www.brookshires.com/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q4975085 https://www.brookshires.com/`
```
```
