### ISSUE TITLE
  some inPost machines are post_office=post_partner and not a amenity=parcel_locker machine

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#8717]
https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/paczkomat_inpost_pl.py

https://inpost.pl/paczkomat-dobra-doa01app-dobra-paczkomaty-malopolskie

Paczkomat -> amenity=parcel_locker

https://inpost.pl/punkt-obslugi-paczek-pop-waw132-warszawa-solidarnosci

PaczkoPunkt -> post_office=post_partner

**Comment by ireun** [comment]
That coming from https://nsi.guide/index.html?t=brands&k=amenity&v=parcel_locker&tt=paczko#paczkomatinpost-ce4e28 I think
