### ISSUE TITLE
natwest_gb lists general phone number for (probably) every single branch

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#8740]
`phone = +44 345 788 8444` is listed for nearly all or all POIs

https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md promises

> The telephone number for the venue. Note that this is usually pulled from a website assuming local visitors, so it probably doesn't include the country code.

**Comment by trigpoint** [comment]
0345 numbers are not available from outside the UK.
Banks tend to give a normal geographic number that usually leads to the same call centre.

They have been making it difficult to contact someone at a specific branch for year.

If are number doesn't start 01/02 (+44 1 or +44 2) it probably doesn't relate to the specific POI.

**Comment by matkoniecz** [comment]
Looking at https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom - it seems that 07 prefix may be plausible for small shops and franchises with someone using personal phone number?
