### ISSUE TITLE
Food4Less

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#875]
https://www.food4less.com/stores/storeLocator

**Comment by davidhicks** [comment]
Sitemap.xml listing pages for each store: https://www.food4less.com/storelocator-sitemap.xml

**Comment by Cj-Malone** [comment]
It also contains StructuredData so it should be fairly straight forward.
`$ pipenv run scrapy sd https://www.food4less.com/stores/grocery/ca/riverside/riverside/704/00343`
```python
{'email': None,
 'image': 'https://www.kroger.com/content/v2/binary/image/food4less_svg_logo-desktop-1556238406166.svg',
 'lat': None,
 'lon': None,
 'name': 'Riverside',
 'opening_hours': 'Mo-Su 07:00-24:00',
 'phone': {'original': '9513528353',
           'pretty': '(951) 352-8353',
           'raw': '+19513528353'},
 'ref': 'https://www.food4less.com/stores/grocery/ca/riverside/riverside/704/00343',
 'website': 'https://www.food4less.com/stores/grocery/ca/riverside/riverside/704/00343'}
```
Although the phone address needs cleaning, and the lat/lon need extracting from: `//script[contains(., "window.__INITIAL_STATE__")]/text()`

**Comment by davidhicks** [comment]
Brand is included within the broken `kroger` spider. See #3369 for progress on fixing a spider for all Kroger brands, including Food4Less.
