### ISSUE TITLE
Add GeoParquet format

### ISSUE THREAD

**Issue by sfkeller** [alltheplaces/alltheplaces#8752]
How about adding GeoParquet format to the current output format GeoJSON?

Consuming GeoParquet is much more efficient than GeoJSON - even for "full-blown, row-oriented" data exchange needs.

This would improve the usability of ATP even more - together with issue #4255.

**Comment by iandees** [comment]
Yea, I'm working on getting Parquet output over on OpenAddresses and am also working on it for All the Places. I think I will probably get it working for ATP first because Python support for Parquet seems to be much more robust.
