### ISSUE TITLE
Harveys Supermarket

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#876]
https://www.harveyssupermarkets.com/Locator

**Comment by davidhicks** [comment]
Single API call appears to return all locations as JSON data: `curl 'https://www.harveyssupermarkets.com/V2/storelocator/getStores' -X POST -H 'Accept: application/json, text/plain, */*' -H 'Content-Type: application/json;charset=utf-8' -data-raw '{"search":"jacksonville, fl","strDefaultMiles":"25000","filter":""}'`

Some "Site is undergoing maintenance" HTML page data seems to incorrectly follow the JSON data, so response.json() could potentially not work without first stripping the erroneous HTML data suffixed to the JSON data.

**Comment by CloCkWeRX** [comment]
Is this the same as https://github.com/alltheplaces/alltheplaces/blob/4d5453f71f9d57db4969b9c77998ce054470878c/locations/spiders/winn_dixie.py#L14 ?

**Comment by davidhicks** [comment]
Same parent company Southeastern Grocers: https://www.segrocers.com/

They likely share the same ICT systems between both brands.

If the spiders are simple, I'd just copy+paste and make whatever adjustments are necessary. If they're complex, you can always have one spider inherit from the other and reuse common code.
