### ISSUE TITLE
New contributor - how do I run/test a spider?

### ISSUE THREAD

**Issue by ShinyDog2636** [alltheplaces/alltheplaces#8769]
Hello,

I am motivated to try contributing a spider but I am stuck just after the set up. How do I run and test a spider?

I followed all instructions in the [readme docs.](https://github.com/alltheplaces/alltheplaces/blob/master/README.md#ubuntu)

I thought I would try running an existing spider but it seems I am missing something. Running `pipenv run python locations/spiders/ymca.py` returns `ModuleNotFoundError: No module named 'locations'`

Thank you

**Comment by Cj-Malone** [comment]
`pipenv run scrapy crawl spider_name`

**Comment by ShinyDog2636** [comment]
Thank you!
