### ISSUE TITLE
"addr:street_address": "undefined" in teriyaki_madness_us

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#8830]
example:

```
{"type": "Feature", "id": "KdQOpHKKOkbVSBrFH9WgGs2jsXs=", "properties": {"ref": "14273349", "@spider": "teriyaki_madness_us", "amenity": "fast_food", "cuisine": "japanese", "takeaway": "yes", "addr:full": "Sherman Oaks, Los Angeles, CA, USA", "addr:street_address": "undefined", "addr:city": "Los Angeles", "addr:state": "CA", "addr:country": "US", "name": "CA  | Teriyaki Madness Sherman Oaks", "brand": "Teriyaki Madness", "brand:wikidata": "Q107692862", "nsi_id": "teriyakimadness-53d9d9"}, "geometry": {"type": "Point", "coordinates": [-118.451357, 34.1489719]}},
```

this field should be dropped or be `null`

**Comment by matkoniecz** [comment]
hmm, maybe I can submit PR for code that can detect highly suspicious entries like this

and potentially modify ATP entries to remove such bogus field

**Comment by iandees** [comment]
"undefined" sounds like a bug with the spidered site, and we should filter that out in the spider. If there's a bunch of these in other spidered sites then we could add something higher level (like a pipeline step).

**Comment by matkoniecz** [comment]
there are few of them, can generate full list 

I guess that general step to drop them would make sense, hopefully no chain will name itself Undefined or Null.

(we already have House chain trap)

**Comment by matkoniecz** [comment]
https://github.com/alltheplaces/alltheplaces/pull/8993#issuecomment-2254338471 has list of some other places detected by quick grep
