### ISSUE TITLE
Spider Imports Capitilization Issue

### ISSUE THREAD

**Issue by ckpiper** [alltheplaces/alltheplaces#8888]
@iandees It seems like an automatic cleanup process fixing spider class name's capitilzations have made imports error. Thus I cannot test new spiders I create. Any suggesstions how to ignore all other spiders and run the one I am currently working on?

**Comment by jhutton1** [comment]
Examples:  HSBCSpider vs newly named HsbcSpider.   Importing into hsbc_us using HSBCSpider.  
BPSpider --> BpSpider.  And so forth.

**Comment by iandees** [comment]
These should be fixed in #8887. Let me know if you run into other problems.
