### ISSUE TITLE
Weekly crawl not working since Mon Jul 8

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#8932]
Per https://data.alltheplaces.xyz/runs/latest.json the last run ID is 2024-07-06-13-31-59

**Comment by matkoniecz** [comment]
> 2,931,896 rows from 2597 spiders, updated Fri Jul 26 03:21:11 PM UTC 2024 

seems fixed!

**Comment by iandees** [comment]
Yep, but the Parquet output is still broken. I'm going to keep this open to try and resolve that.

**Comment by CloCkWeRX** [comment]
Resolved?
