### ISSUE TITLE
`contact:twitter=www.twitter.com` and similar should not be included, as these link main social media website rather than specific profile

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#8978]
```
{
    'ref': '741',
    'contact:pinterest': 'www.pinterest.com',
    'contact:youtube': 'www.youtube.com',
    'shop': 'mall',
    '@spider': 'mall_maverick',
    'addr:street_address': '10 Watercress Court',
    'addr:city': 'Kitchener',
    'addr:state': 'ON',
    'addr:postcode': 'N2E 3S8',
    'addr:country': 'CA',
    'name': '10 Watercress Court',
    'contact:twitter': 'www.twitter.com',
    'contact:facebook': 'www.facebook.com'
}
```

https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/mall_maverick.py

**Comment by iandees** [comment]
Can you be more specific? The [OSM wiki page](https://wiki.openstreetmap.org/wiki/Key:contact:twitter) says it should be a full URL.

**Comment by matkoniecz** [comment]
I would expect it to link to specific profile at Facebook/twitter/youtube - not to the main website

In the same way as theoretical `contact:github=https://github.com/` would not be correct for ATP but `contact:github=https://github.com/alltheplaces/alltheplaces/` would make sense

**Comment by matkoniecz** [comment]
> The [OSM wiki page](https://wiki.openstreetmap.org/wiki/Key:contact:twitter) says it should be a full URL.

see

> The value is the Page-URL or the Twittername (without '@'). 

see also https://taginfo.openstreetmap.org/keys/contact:twitter#values

**Comment by iandees** [comment]
Yep, I interpret "The value is the Page-URL" to be "https://twitter.com/username".

**Comment by iandees** [comment]
> I would expect it to link to specific profile at Facebook/twitter/youtube - not to the main website

Yes, this is a bug. Maybe the call to `add_social_media()` is being used incorrectly here:

https://github.com/alltheplaces/alltheplaces/pull/8061/files#diff-a33ec592b48c883b6f109781e3604df134eb5664034c2a9bc7982c7f5555b98dR45

**Comment by matkoniecz** [comment]
from looking at source data: they have bare link to main site also there

**Comment by iandees** [comment]
Yep, source data was less than perfect and I added a filter for it. Thanks for spotting it.
