### ISSUE TITLE
There is issue with the seven eleven spider.

### ISSUE THREAD

**Issue by vdkotian** [alltheplaces/alltheplaces#899]
I was trying to scrape seven eleven website, but to my notice that the spider was not able to fetch and scrape data. I tried digging a bit and found that the API mentioned in the no code was no logger working. I have created spider for seven eleven which is scraping data, it would be wonderful if you could review and let me contribute towards this project.

**Comment by iandees** [comment]
Hello! Please file a pull request so that we can see your updated scraper and include it.
