### ISSUE TITLE
Disco (Argentina)

### ISSUE THREAD

**Issue by nicolas17** [alltheplaces/alltheplaces#90]
Supermarket chain, owned by Cencosud.

The [webpage with the list of branches](https://www.disco.com.ar/Login/Sucursales.aspx) uses some client-side-template Javascript monstrosity. The data can be retrieved with:
```curl -H "Content-Type: application/json" -d "{}" https://www.disco.com.ar/Login/PreHomeService.aspx/TraerLocales```
which will return a JSON object with a "d" key with a string with more JSON (?!)

Has address, phone number, lat, lon (at least one pointing to null island), payment methods. No opening hours.

**Comment by sweetdream0729** [comment]
working on this
