### ISSUE TITLE
Remedy'sRx

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#902]
https://www.remedys.ca/en/find-a-pharmacy

**Comment by davidhicks** [comment]
New website has a combined store locator for Remedy'sRx, Guardian and IDA pharmacies in Canada.

Single request to API returning all location data as JSON data: `https://www.guardian-ida-remedysrx.ca/api/sitecore/Pharmacy/Pharmacies?id=%7B73B789E3-C922-483E-9E5A-C1D2BC52D6D4%7D`
