### ISSUE TITLE
Albert

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#919]
https://www.albert.cz/nase-prodejny/mapa-prodejen

(supermarket in Czech Republic)

**Comment by CloCkWeRX** [comment]
### Brand name

Albert Česká republika

Czech supermarket chain

### Wikidata ID

Q9144241
https://www.wikidata.org/wiki/Q9144241
https://www.wikidata.org/wiki/Special:EntityData/Q9144241.json

### Store finder url(s)

Official Url(s): http://www.albert.cz/
- [x] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q9144241 http://www.albert.cz/`
```
```

**Comment by CloCkWeRX** [comment]
https://www.albert.cz/nase-prodejny

**Comment by CloCkWeRX** [comment]
https://www.albert.cz/sitemap/albertcz_sitemap_stores-0.xml.gz

**Comment by CloCkWeRX** [comment]
https://www.albert.cz/nase-prodejny/supermarket-brno-bystr-ecerova
