### ISSUE TITLE
Wienerschnitzel (Crawl, Structured Data)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#9267]
### Brand name

Wienerschnitzel

American fast food restaurant chain

### Wikidata ID

Q324679
https://www.wikidata.org/wiki/Q324679
https://www.wikidata.org/wiki/Special:EntityData/Q324679.json

### Store finder url(s)

Official Url(s): http://www.wienerschnitzel.com
- [ ] I have run the below and if anything in generated, added it.
- [ ] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy links http://www.wienerschnitzel.com`
`pipenv run scrapy sitemap --pages http://www.wienerschnitzel.com`
`pipenv run scrapy sf --brand-wikidata=Q324679 http://www.wienerschnitzel.com`
pipenv run scrapy sf https://www.wienerschnitzel.com/locations-all/
pipenv run scrapy sf https://www.wienerschnitzel.com/locations/

**Comment by CloCkWeRX** [comment]
https://www.wienerschnitzel.com/locations-all/ seems the best bet.
https://www.wienerschnitzel.com/location/881-central-pittman-fairfield-4490-central-way-fairfield-ca-94534/
https://validator.schema.org/#url=https%3A%2F%2Fwww.wienerschnitzel.com%2Flocation%2F881-central-pittman-fairfield-4490-central-way-fairfield-ca-94534%2F

**Comment by impiaaa** [comment]
The structured data doesn't include coordinates, but does include opening hours. The storefinder does include coordinates, but doesn't include opening hours. [Here](/impiaaa/alltheplaces/tree/wienerschnitzel)'s an implementation that uses the storefinder. Are the coordinates or the hours more important? Is a hybrid solution necessary?

**Comment by CloCkWeRX** [comment]
I wonder why this one didn't autodetect. I think my vote is for coordinates

**Comment by impiaaa** [comment]
The website only shows a map after you've entered a search query, so e.g. `scrapy sf "https://www.wienerschnitzel.com/location-results/?address=90210"` works for me. I had to modify the autogenerated spider to get good results though.
