### ISSUE TITLE
Jumbo (Argentina)

### ISSUE THREAD

**Issue by nicolas17** [alltheplaces/alltheplaces#93]
Supermarket chain, also owned by Cencosud.

Webpage is https://www.jumbo.com.ar/Login/Sucursales.aspx but the website code is almost identical as [Disco](#90). Branch list can be retrieved as JSON in the same way:
```curl -H "Content-Type: application/json" -d "{}" https://www.jumbo.com.ar/Login/PreHomeService.aspx/TraerLocales```

**Comment by iandees** [comment]
Removing the assignee on this because there's been no update for 9 days.

**Comment by sweetdream0729** [comment]
working on this
