### ISSUE TITLE
Crew Clothing spider is missing branches

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#9315]
The spider for Crew Clothing `crew_clothing_gb` is missing a number of branches due to an incorrect assumption about the store URLs.

The spider looks at https://www.crewclothing.co.uk/customer-services/stores/ for possible store links, and then checks links matching the regex `/customer-services/stores/[-\w]+/$`. However (for some reason) not all the Crew Clothing branches have URLs of this form. A number simply have the store slug directly following the domain name, e.g.

- https://www.crewclothing.co.uk/affinity-staffordshire-/
- https://www.crewclothing.co.uk/amersham/
- https://www.crewclothing.co.uk/bowness-on-windermere/
- https://www.crewclothing.co.uk/cannock-outlet-/
- https://www.crewclothing.co.uk/evesham/

So the regex needs to be relaxed to include both links of the original form and top-level directories. I don't know if this will run into problems with it fetching non-store pages too though.

**Comment by CloCkWeRX** [comment]
https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/crew_clothing_gb.py#L13

**Comment by CloCkWeRX** [comment]
Targeting ```<div id="storelistall" class="storelistall nogaps">``` via //div[@id="storelistall"]/div/a may be a better approach
