### ISSUE TITLE
Gong Cha (US) (Storepoint)

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#9317]
### Brand name

Gong Cha

Taiwan tea shops

### Wikidata ID

Q5581670
https://www.wikidata.org/wiki/Q5581670
https://www.wikidata.org/wiki/Special:EntityData/Q5581670.json

### Store finder url(s)

Official Url(s): https://gongchausa.com/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [x] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy links https://gongchausa.com/`
`pipenv run scrapy sitemap --pages https://gongchausa.com/`
`pipenv run scrapy sf --brand-wikidata=Q5581670 https://gongchausa.com/`
pipenv run scrapy sf https://gongchausa.com/locations/
https://api.storepoint.co/v1/161d1d5abc0b7c/locations?lat=41.8069&long=-72.5457&radius=200
```
```

**Comment by CloCkWeRX** [comment]
#9196

**Comment by CloCkWeRX** [comment]
@davidhicks this one didn't autodetect due to...

`https://api.storepoint.co/v1/161d1d5abc0b7c/locations?rq`
vs
```
        DetectionRequestRule(url=r"^https?:\/\/api\.storepoint\.co\/v1\/(?P<key>[0-9a-f]{14})\/locations(?:\?|\/|$)")
```

**Comment by davidhicks** [comment]
The regex matches OK.

Try `pipenv run scrapy sf --brand-wikidata=Q5581670 https://gongchausa.com/locations/` because that subpage calls out to `api.storepoint.co` whereas `pipenv run scrapy sf --brand-wikidata=Q5581670 https://gongchausa.com/` doesn't call out to `api.storepoint.co`.

**Comment by CloCkWeRX** [comment]
ubuntu@codespaces-88a392:/workspaces/alltheplaces$ pipenv run scrapy sf https://gongchausa.com/locations/
ubuntu@codespaces-88a392:/workspaces/alltheplaces$

**Comment by davidhicks** [comment]
> ubuntu@codespaces-88a392:/workspaces/alltheplaces$ pipenv run scrapy sf https://gongchausa.com/locations/ ubuntu@codespaces-88a392:/workspaces/alltheplaces$

I can't see a reason why this would happen from a glance over the code.

One possibility is that there is a modal popup on the page that is blocking the API call to `api.storepoint.co` until the modal popup is closed. You could add some debug/print outputs in the detection code to see what API calls are intercepted via Playwright, to confirm whether `api.storepoint.co` is requested by the Playwright instance.

Unfortunately Playwright doesn't support loading extensions such as ublock-origin to minimise the amount of junk, popups, etc that Playwright then has to deal with.
