### ISSUE TITLE
Add an issue template for "broken" or "bad output" spiders?

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#9349]
More and more people are consuming the data.

The automated bot is okay but noisy for "spider doesn't work"

Having an issue template to prompt for:
* Spider name (could we guess the spider code path from this? Maybe?)
* Output link (#4255)
* Example malformed data
* Expected output & why
* Date, if not time of raising issue?
* Auto label as bug/most wanted to fix?

**Comment by matkoniecz** [comment]
Template may also warn that proxy spider failing are a known issue.

Is it possible to have at ATP website link that for given spider would preload spider name, path, output link?

> Date, if not time of raising issue?

That is in issue metadata. Why add it manually?
