### ISSUE TITLE
Houlihan's

### ISSUE THREAD

**Issue by brentajones** [alltheplaces/alltheplaces#94]
http://www.houlihans.com/find-a-location

**Comment by nicolas17** [comment]
* POSTing `{'storeNumber': '623'}` to http://www.houlihans.com/DataHelper.aspx/GetStoreLocationsByNumber gives stores near the given store
* POSTing `{'lat': '40.71', 'lon': '-74'}` to http://www.houlihans.com/DataHelper.aspx/GetStoreLocations gives stores near that point
* Must include a `Content-Type: application/json` request header
* Search radius unknown
* Like [Disco](#90), it returns a JSON object with a "d" key with a string with more JSON; it might be a generic .NET thing.

**Comment by iandees** [comment]
No progress for 2 days, re-opening this for others.
