### ISSUE TITLE
Daylight Donuts

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#941]
http://www.daylightdonuts.com/find-your-daylight/

**Comment by davidhicks** [comment]
WPStoreLocator is used per `https://daylightdonuts.com/wp-admin/admin-ajax.php?action=store_search&lat=36.153982&lng=-95.992775&max_results=2500&search_radius=5000&autoload=1`

WPStoreLocator has been configured with a maximum of 50 results returned, so a radius geographic search is needed across the US with a density ensuring 49 or less results are returned per API call.

**Comment by CloCkWeRX** [comment]
https://daylightdonuts.com/wp-admin/admin-ajax.php?action=store_search&max_results=25&search_radius=50&autoload=1 gives ~646 stores for me

**Comment by CloCkWeRX** [comment]
```
from locations.storefinders.wp_store_locator import WPStoreLocatorSpider


class DaylightDonutsUSSpider(WPStoreLocatorSpider):
        name = "daylight_donuts_us"
        item_attributes = {
                "brand_wikidata": "Q48970508",
                "brand": "Daylight Donuts",
        }
        allowed_domains = [
                "daylightdonuts.com",
        ]

```
