### ISSUE TITLE
bevmo_us - at least some (maybe all) shop-specific sites are gone and they redirect to the main page (they have now JS blob as data source)

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#9493]
Say https://www.bevmo.com/stores/elk-grove from ATP redirects to https://bevmo.com/

https://www.bevmo.com/stores/fremont from ATP redirects to https://bevmo.com/

https://www.bevmo.com/stores/corona from ATP redirects to https://bevmo.com/

**Comment by CloCkWeRX** [comment]
Freshop spider, so I wonder if they changed or upgraded

**Comment by CloCkWeRX** [comment]
https://bevmo.com/pages/store-locator

**Comment by CloCkWeRX** [comment]
Now a JS Blob on page load; so I bet they changed storefinders and just haven't deleted their old data yet.

Either short term, override parse_item and item['website'] = None or worth a rewrite.
