### ISSUE TITLE
Questions about the published data

### ISSUE THREAD

**Issue by thismakessand** [alltheplaces/alltheplaces#953]
Love the project, thanks for setting it up!  I'm hoping someone can help answer a few questions I have regarding the generated data.  I've looked through the Issues and documentation in github but haven't seen the following questions addressed. 
- Do the scrapers run and publish generated data to alltheplaces.xyz on a regular schedule?

- It looks like ~90 of the geojson files from the latest output.tar.gz are empty (presumably due to broken scrapers).  Is any of the archived data accessible publicly?

- Are there any open data projects that ingest this data? ie, should we be going to OSM or some other source for these scraped POIs?

I'm hoping to write some more scrapers and get a few others involved as well, I just wanted to see about the availability/reliability of the generated data, or if it's something we would need to run on or own or what.  
Thanks!

**Comment by iandees** [comment]
Thanks for your contributions, @thismakessand! These are great questions.

- Right now I have to kick off the scrapers manually. The data gets published to an S3 bucket and posted on the website here: https://www.alltheplaces.xyz/

- Yep, the output files are blank when the scrapers fail for whatever reason. If you change the `output.tar.gz` to `logs.tar.gz` in the download link you can grab the logs from the runs. There is some archived data, but I don't have a great way of publishing it yet.

- I don't know of any projects that ingest this data yet. I started this as a potential source for OSM imports or to add to [Who's On First](https://www.whosonfirst.org/) back when I was at Mapzen. When [Mapzen shut down](https://mapzen.com/blog/shutdown/) I had to change focus away from this project.

**Comment by thismakessand** [comment]
@iandees Thanks for the response - is running the scrapers manually just due a time/energy/money constraint, or something else?  If it's time/energy/money, is it something I/others could help with?

**Comment by iandees** [comment]
> is running the scrapers manually just due a time/energy/money constraint?

It's mostly because I haven't had a chance to automate it yet.

Also, it's running on my personal AWS account – even though it only costs $0.50-1.00 to run, if I did it on any frequency it would add up. Also, I don't think this data changes all that often and I'd like to see a better interface into the downloaded data than I have now. It'd be nice to see reports of which spiders are working, how many objects they output, etc. and then get alerts when spiders show significant change of output.
