### ISSUE TITLE
Gigi’s Cupcakes

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#954]
https://gigiscupcakesusa.com/pages/stores-in-store-pickup

**Comment by davidhicks** [comment]
Uses [Easy Locator](https://easylocator.net/) store finder which hasn't yet been implemented by ATP. The only documentation I could find for Easy Locator is a REST API document `https://easylocator.net/Easy%20Locator%20REST%20API%20documentation.pdf` which does not appear to be applicable as this brand is not using a REST API.

Request format for returning all location data is:
`https://easylocator.net/ajax/search_by_lat_lon_geojson/{key}/{lat}/{lon}/0/{number_of_results_to_return)/null/null`

`{number_of_results_to_return} = 0` appears to return all locations?

For this brand, all locations appear to be returned as JSON data with:
`https://easylocator.net/ajax/search_by_lat_lon_geojson/gigiscupcakesusa/-37.7333/145.1167/0/0/null/null`
