### ISSUE TITLE
Some Chase POIs are not processed

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#9557]
```
{
    'type': 'Feature',
    'id': '791UxC52VIRP7nhHVSisEz_KmNE=',
    'properties': {
        'ref': '1010121875',
        '@source_uri': 'https://locator.chase.com/ny/corona/8-meridian-rd-Branch-20114',
        '@spider': 'chase_us',
        'addr:street_address': '8 Meridian Rd',
        'addr:city': 'Corona',
        'addr:state': 'NY',
        'addr:postcode': '11368',
        'addr:country': 'US',
        'name': 'USTA 2023 - New branch',
        'website': 'https://locator.chase.com/ny/corona/8-meridian-rd-Branch-20114',
        'brand': 'Chase',
        'brand:wikidata': 'Q524629'
    },
    'geometry': {'type': 'Point', 'coordinates': [-73.845629, 40.750372]}
```

it seems to have at least ATM based on linked website

**Comment by CloCkWeRX** [comment]
https://github.com/alltheplaces/alltheplaces/blob/ea42cff3e0c0f2e53bd088cd59776d130d0b187f/locations/spiders/chase_us.py#L15

https://validator.schema.org/#url=https%3A%2F%2Flocator.chase.com%2Fny%2Fcorona%2F8-meridian-rd-Branch-20114

Might be worth adding support to the structured data spider to know more about certain types

**Comment by Cj-Malone** [comment]
amenityFeature values aren't standardised, each site will be different. We could add some logging (preferably stats) to find out if there are frequent ones, but it's not possible rn without some refactoring.
