### ISSUE TITLE
@spider and file name matching

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#9687]
https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md

> @spider
> The name of the spider that produced this feature. It is [specified in each spider](https://github.com/alltheplaces/alltheplaces/blob/11d9be56515ef0f6419e001b1950f69d28d4f400/locations/spiders/apple.py#L9), so it isn't necessarily related to the file name of the spider.

1) maybe giving example where spider name and file name mismatches would be a good idea?

2) is it even a good idea to have mismatching spider codes and filenames? Can it be avoided?

How someone may get filename where given spider is defined if `@spider` field should not be used for that?

**Comment by iandees** [comment]
What are you trying to do that you need the file name?

**Comment by matkoniecz** [comment]
Look at data/spider code when some issues are detected with data. My typical PR is done this way.

See https://codeberg.org/matkoniecz/list_how_openstreetmap_can_be_improved_with_alltheplaces_data/src/branch/master/0_config.py#L639

Or https://codeberg.org/matkoniecz/list_how_openstreetmap_can_be_improved_with_alltheplaces_data/src/commit/14fef393c406d8b9bdc14a8ff52b3e330401a211/qa.py#L66 for actual use of that function.

Also, say https://matkoniecz.codeberg.page/improving_openstreetmap_using_alltheplaces_dataset/missing_shops_circle_k_pl.html links back to atp spider code (sidebar at the bottom).

**Comment by CloCkWeRX** [comment]
I think the 99bikes spider was a good example where class didn't/couldn't match spider

**Comment by CloCkWeRX** [comment]
Other: there are now checks in CI to detect mismatches, so this is less common of an issue

**Comment by iandees** [comment]
There's a `scrapy spider_filename <spider name>` command ([defined here](https://github.com/alltheplaces/alltheplaces/blob/master/locations/commands/spider_filename.py)) that gives you the file name for a spider name. I use it in the weekly run to build output metadata ([here](https://github.com/alltheplaces/alltheplaces/blob/cc0e3973bdea2412f5168764e6da918c0e2a190d/ci/run_all_spiders.sh#L115)). Is that useful?

There's also the "results" JSON available from https://data.alltheplaces.xyz/runs/latest.json. It points to https://alltheplaces-data.openaddresses.io/runs/2024-08-17-13-32-02/stats/_results.json right now, which gives you a list of all the spiders and their filenames.

**Comment by matkoniecz** [comment]
Thanks! 

And yes, https://alltheplaces-data.openaddresses.io/runs/2024-08-17-13-32-02/stats/_results.json is very useful, I will use it (and in future whatever https://data.alltheplaces.xyz/runs/latest.json is pointed to).

I opened https://codeberg.org/matkoniecz/list_how_openstreetmap_can_be_improved_with_alltheplaces_data/issues/10 if that assumption was actually faulty at least for some spiders.
