### ISSUE TITLE
Cato

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#976]
https://www.catofashions.com/catostores.cfm

**Comment by davidhicks** [comment]
Most or all locations appear to be returned by an API request with radius of 2500 miles (?) to `curl 'https://stores.catofashions.com/search-api?q=39.11553139999999%2C-94.62678729999999&qp=Kansas%20City%2C%20KS%2C%20USA&r=2500&l=en'`

It's possible that the 2500 mile radius isn't large enough to capture all locations, and a small number of additional coordinates need to be searched too.

**Comment by davidhicks** [comment]
Added in PR #6827
