### ISSUE TITLE
McDonald's (Argentina)

### ISSUE THREAD

**Issue by nicolas17** [alltheplaces/alltheplaces#98]
The website is: http://www.mcdonalds.com.ar/locales
(which is broken. It queries a JSON endpoint, but throws an exception saying es_AR is not a supported language (!). Turns out this is due to an hl=es_AR cookie; leaving out the cookie works.)

JSON endpoint:
http://www.mcdonalds.com.ar/api/restaurants?country=AR&latitude=-34.76&longitude=-58.43

I have no idea if it has a limit of number of items returned, or what's the radius searched.

**Comment by sledjama** [comment]
i think this should go with the mcdonalds crawler, i can take this up

**Comment by SelfnessAid** [comment]
this issue was solved already via mcdonalds-localizer.py.
@iandees could you possibly look at this?
this issue is same as http://www.mcdonalds.com.pr/locales.
thanks.

**Comment by iandees** [comment]
Fixed in #355 .
