### ISSUE TITLE
La Genovesa (Argentina)

### ISSUE THREAD

**Issue by nicolas17** [alltheplaces/alltheplaces#99]
Regional supermarket.

Locations (only 5 at the moment) can be HTML-scraped from:
http://lagenovesasuper.com.ar/index.php/empresa/sucursales

**Comment by nicolas17** [comment]
In case it's not clear: when the phone number says "4240-8711 / 8714" it means "4240-8711" and "4240-8714".

**Comment by alfbrown** [comment]
Has this been assigned yet?
