### ISSUE TITLE
 Budnikowsky

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#9913]
### Brand name

Budnikowsky

German drug store chain

### Wikidata ID

Q1001516
https://www.wikidata.org/wiki/Q1001516
https://www.wikidata.org/wiki/Special:EntityData/Q1001516.json

### Store finder url(s
https://www.budni.de/filialen

Official Url(s): https://www.budni.de/
- [x] I have run the below and if anything in generated, added it.
- [x] I have manually checked for a storefinder
- [ ] This is not a manufacturer listing outlets operating under their own brands / this will not create duplicates
`pipenv run scrapy sf --brand-wikidata=Q1001516 https://www.budni.de/`
```
```

### Sample store page url

https://www.budni.de/filialen/22926-rathausplatz-15?

### Countries?

DE

### Difficulty?

Medium

### Number of POI?

None

### Behaviours

- [x] Has coordinates?
- [x] Has opening hours?
- [ ] JSON API?
- [ ] Embedded JSON?
- [ ] HTML markup?
- [ ] Structured Data? (`pipenv run scrapy sd (specific page url)`) or [validator](https://validator.schema.org/) has content
- [ ] Open Graph Data?
- [ ] Sitemap? (`pipenv run scrapy sitemap (url)`)
- [ ] Requires proxy?
- [ ] Has 'bot protection' (Cloudflare, etc)?

**Comment by hfs** [comment]
Fixed in #11353
