### ISSUE TITLE
Virgin Active AU

### ISSUE THREAD

**Issue by arrival-spring** [alltheplaces/alltheplaces#9973]
### Brand name

Virgin Active

### Wikidata ID

Q4013942

### Store finder url(s)

https://www.virginactive.com.au/locations

https://www.virginactive.com.au/_next/data/Me_Je-QRiZvkL3eQ4S-EO/locations.json

e.g. https://www.virginactive.com.au/_next/data/Me_Je-QRiZvkL3eQ4S-EO/locations/wynyard.json

### Countries?

AU

### Difficulty?

Medium - some customisation or data cleansing

### Number of POI?

0-10

### Behaviours

- [ ] Has coordinates?
- [ ] Has opening hours?
- [X] JSON API?
- [ ] Embedded JSON?
- [ ] HTML markup?
- [ ] Structured Data? (`pipenv run scrapy sd (specific page url)`) or [validator](https://validator.schema.org/) has content
- [ ] Open Graph Data?
- [ ] Sitemap? (`pipenv run scrapy sitemap (url)`)
- [ ] Requires proxy?
- [ ] Has 'bot protection' (Cloudflare, etc)?

**Comment by CloCkWeRX** [comment]
There's a few others that follow this pattern with:
```
        for location in json.loads(
            response.xpath('//script[@id="__NEXT_DATA__" and @type="application/json"]/text()').get()
```
